import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {house} from './house-data.js'; // kept external: edit the single data file, no rebuild required
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&#39;'}[c]));
let state={view:'whole',floor:'f1',room:null,lens:'model',quality:'sd',wall:'auto',builtins:true,furniture:true};
function readURL(){state={...state,view:'whole',floor:'f1',room:null,lens:'model'};const q=new URLSearchParams(location.search);for(const [key,values]of Object.entries({view:['whole','f1','f2','exploded'],floor:['f1','f2'],lens:['model','plan','photo']}))if(values.includes(q.get(key)))state[key]=q.get(key);if(['f1','f2'].includes(state.view))state.floor=state.view;const room=house.rooms.find(r=>r.id===q.get('room'));state.room=room?.id||null;if(room){state.floor=room.floor;state.view=room.floor;}}
readURL();
const scene=new T.Scene();scene.background=new T.Color('#e9eef1');
const camera=new T.PerspectiveCamera(38,1,.05,120);camera.position.set(14,12,-16);
let renderer,controls,dirty=true;
try{renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.4));renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;$('#scene').append(renderer.domElement);controls=new OrbitControls(camera,renderer.domElement);controls.target.set(3.5,2.8,3.5);controls.minDistance=2;controls.maxDistance=38;controls.maxPolarAngle=Math.PI*.49;controls.enableDamping=!matchMedia('(prefers-reduced-motion: reduce)').matches;controls.addEventListener('change',()=>{dirty=true;});controls.update();}catch{state.lens='plan';$('#status').textContent='เปิด 3D ไม่ได้ ยังดูแปลนได้';}
scene.add(new T.HemisphereLight('#ffffff','#839582',2.5));const sun=new T.DirectionalLight('#fff1db',3.5);sun.position.set(-5,14,-6);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-15,right:15,top:15,bottom:-15,near:1,far:40});sun.shadow.bias=-.0005;scene.add(sun);
const mat=(color,roughness=.75,metalness=0)=>new T.MeshStandardMaterial({color,roughness,metalness});
const materials={wall:mat('#f1efe9'),frame:mat('#334647',.3,.4),wood:mat('#b8a185'),fabric:mat('#bdc9c5'),white:mat('#ffffff',.2),roof:mat('#9b7164'),ground:mat('#bdcbb1'),glass:new T.MeshPhysicalMaterial({color:'#cce2e5',transparent:true,opacity:.3,roughness:.1,depthWrite:false})};
const box=(parent,w,h,d,x,y,z,material)=>{const mesh=new T.Mesh(new T.BoxGeometry(w,h,d),material);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;};
box(scene,11,.2,11,3.5,-.3,3.5,materials.ground);
const floors=new Map(),wallRecords=[],picks=[],roomMaterials=[];
for(const floor of house.floors){const group=new T.Group();group.position.y=floor.elevation;scene.add(group);floors.set(floor.id,group);}
for(const r of house.rooms){const group=floors.get(r.floor),m=mat(r.color);roomMaterials.push({id:r.id,m,color:r.color});
 const shape=new T.Shape();shape.moveTo(r.x,r.z);shape.lineTo(r.x+r.w,r.z);shape.lineTo(r.x+r.w,r.z+r.d);shape.lineTo(r.x,r.z+r.d);shape.closePath();
 if(r.void){const v=r.void,hole=new T.Path();hole.moveTo(v.x,v.z);hole.lineTo(v.x,v.z+v.d);hole.lineTo(v.x+v.w,v.z+v.d);hole.lineTo(v.x+v.w,v.z);hole.closePath();shape.holes.push(hole);}
 const geometry=new T.ExtrudeGeometry(shape,{depth:.13,bevelEnabled:false});geometry.rotateX(Math.PI/2);const floorMesh=new T.Mesh(geometry,m);floorMesh.position.y=.02;floorMesh.userData.room=r.id;floorMesh.receiveShadow=true;group.add(floorMesh);picks.push(floorMesh);
 const furniture=new T.Group();furniture.name='furniture';furniture.position.set(r.x+r.w/2,0,r.z+r.d/2);group.add(furniture);
 if(r.furniture==='sofa'){box(furniture,2,.34,.9,0,.28,0,materials.fabric);box(furniture,2,.7,.17,0,.64,.39,materials.fabric);box(furniture,.17,.65,.9,-.92,.5,0,materials.fabric);box(furniture,.17,.65,.9,.92,.5,0,materials.fabric);box(furniture,1.1,.12,.55,0,.42,-.95,materials.wood);}
 if(r.furniture==='table'){box(furniture,1.65,.12,.85,0,.86,0,materials.wood);for(const x of [-.65,.65])box(furniture,.09,.78,.65,x,.4,0,materials.frame);for(const x of [-.5,.5])for(const z of [-.8,.8]){box(furniture,.45,.13,.45,x,.48,z,materials.fabric);box(furniture,.45,.55,.08,x,.68,z+Math.sign(z)*.2,materials.fabric);}}
 if(r.furniture==='bed'){box(furniture,1.85,.25,2.1,0,.22,0,materials.wood);box(furniture,1.78,.25,2.03,0,.45,0,materials.white);box(furniture,1.9,1,.15,0,.57,.98,materials.fabric);for(const x of [-.43,.43])box(furniture,.69,.13,.44,x,.64,.65,materials.fabric);}
 if(r.furniture==='bath'){box(furniture,.7,.8,.5,-.65,.4,.7,materials.white);box(furniture,.6,.45,.72,.7,.28,.7,materials.white);box(furniture,1.5,.07,1.05,0,.06,-.7,materials.white);box(furniture,1.5,1.9,.025,0,1,-.18,materials.glass);}
 if(r.builtIn){const g=new T.Group();g.name='builtins';group.add(g);box(g,r.w-.4,.9,.6,r.x+r.w/2,.45,r.z+r.d-.4,materials.white);box(g,r.w-.3,.07,.68,r.x+r.w/2,.94,r.z+r.d-.4,materials.wood);}
 if(r.stairs)for(let i=0;i<16;i++)box(group,1.15,.12,.15,r.x+1.6,.14+i*.2,r.z+.2+i*.15,materials.wood);
 if(r.void){const v=r.void;for(const x of [v.x,v.x+v.w]){box(group,.035,.95,v.d,x,.53,v.z+v.d/2,materials.frame);box(group,.02,.8,v.d-.06,x,.45,v.z+v.d/2,materials.glass);}}
}
for(const w of house.walls){const len=Math.hypot(w.b[0]-w.a[0],w.b[1]-w.a[1]),group=new T.Group();group.position.set(w.a[0],0,w.a[1]);group.rotation.y=-Math.atan2(w.b[1]-w.a[1],w.b[0]-w.a[0]);floors.get(w.floor).add(group);
 const full=new T.Group(),low=new T.Group();group.add(full,low);const segment=(parent,a,b,bottom,h)=>{if(b-a>.005&&h>.005)box(parent,b-a,h,.13,(a+b)/2,bottom+h/2,0,materials.wall);};let at=0;
 for(const o of [...w.openings].sort((a,b)=>a.at-b.at)){
  segment(full,at,o.at,0,3.09);segment(low,at,o.at,0,.5);segment(full,o.at,o.at+o.w,0,o.bottom);segment(full,o.at,o.at+o.w,o.bottom+o.h,3.09-o.bottom-o.h);segment(low,o.at,o.at+o.w,0,Math.min(o.bottom,.5));
  if(!o.passage){const surface=new T.Group();full.add(surface);for(const x of [o.at,o.at+o.w])box(surface,.045,o.h,.06,x,o.bottom+o.h/2,0,materials.frame);for(const y of [o.bottom,o.bottom+o.h])box(surface,o.w,.045,.06,o.at+o.w/2,y,0,materials.frame);if(o.door){const hinge=new T.Group();hinge.position.set(o.at,o.bottom,.02);hinge.rotation.y=-Math.PI/3;surface.add(hinge);box(hinge,o.w-.06,o.h-.07,.045,(o.w-.06)/2,o.h/2,0,materials.wood);}else{box(surface,o.w-.07,o.h-.07,.02,o.at+o.w/2,o.bottom+o.h/2,0,materials.glass);box(surface,.035,o.h,.04,o.at+o.w/2,o.bottom+o.h/2,0,materials.frame);}}
  at=o.at+o.w;
 }segment(full,at,len,0,3.09);segment(low,at,len,0,.5);wallRecords.push({full,low,group,floor:w.floor,mid:new T.Vector3((w.a[0]+w.b[0])/2,0,(w.a[1]+w.b[1])/2)});
}
const roofGeometry=new T.BufferGeometry();const vertices=[],p=[[-.3,6.35,-.3],[7.3,6.35,-.3],[7.3,6.35,7.3],[-.3,6.35,7.3]],apex=[3.5,8.2,3.5];for(let i=0;i<4;i++)vertices.push(...p[i],...apex,...p[(i+1)%4]);roofGeometry.setAttribute('position',new T.Float32BufferAttribute(vertices,3));roofGeometry.computeVertexNormals();materials.roof.side=T.DoubleSide;const roof=new T.Mesh(roofGeometry,materials.roof);roof.castShadow=true;scene.add(roof);
function fit(){if(!controls)return;camera.position.set(14,12,-16);controls.target.set(3.5,2.8,3.5);controls.update();dirty=true;}
function applyWalls(){for(const w of wallRecords){const near=new T.Vector3().subVectors(camera.position,controls?.target||new T.Vector3(3.5,0,3.5)).dot(new T.Vector3(w.mid.x-3.5,0,w.mid.z-3.5))>0;const lower=state.view!=='whole'&&(state.wall==='low'||state.wall==='auto'&&near);w.full.visible=!lower;w.low.visible=lower;}}
function render(write=true){
 for(const floor of house.floors){const g=floors.get(floor.id);g.visible=state.view==='whole'||state.view==='exploded'||state.view===floor.id;g.position.y=floor.elevation+(state.view==='exploded'&&floor.id==='f2'?3:0);g.traverse(o=>{if(o.name==='furniture')o.visible=state.furniture;if(o.name==='builtins')o.visible=state.builtins;});}
 roof.visible=state.view==='whole';applyWalls();if(renderer){renderer.shadowMap.enabled=state.quality==='hd';renderer.setPixelRatio(Math.min(devicePixelRatio,state.quality==='hd'?2:1.4));materials.fabric.roughness=state.quality==='hd'?.93:.7;materials.wood.roughness=state.quality==='hd'?.45:.8;dirty=true;}
 for(const item of roomMaterials)item.m.color.set(item.id===state.room?'#8eaeaa':item.color);
 $('#title').textContent=house.title;$('#description').textContent=house.subtitle;$('#room-name').textContent=house.rooms.find(r=>r.id===state.room)?.name||'ลองเปิดดูข้างใน';$('#inside').hidden=state.view!=='whole';
 $('#scene').hidden=state.lens!=='model';$('#plan').hidden=state.lens!=='plan';$('#photos').hidden=state.lens!=='photo';$('.camera').hidden=state.lens!=='model';$('.dock').hidden=state.lens==='photo';$('.quality').hidden=state.lens!=='model';$('#walls').hidden=state.lens!=='model'||state.view==='whole';
 for(const [attribute,key]of [['view','view'],['quality','quality'],['wall','wall'],['lens','lens']])document.querySelectorAll(`[data-${attribute}]`).forEach(b=>b.setAttribute('aria-pressed',String(b.dataset[attribute]===state[key])));
 $('#rooms').innerHTML=house.rooms.filter(r=>r.floor===state.floor).map(r=>`<button data-room="${esc(r.id)}" aria-pressed="${r.id===state.room}">${esc(r.name)}</button>`).join('');
 $('#plan').innerHTML=`<svg viewBox="-.4 -.4 7.8 7.8" aria-label="แปลนบ้านสมมติ">${house.rooms.filter(r=>r.floor===state.floor).map(r=>`<g data-room="${esc(r.id)}" tabindex="0" role="button" aria-label="${esc(r.name)}"><rect x="${r.x}" y="${r.z}" width="${r.w}" height="${r.d}" fill="${r.id===state.room?'#8eaeaa':r.color}" stroke="#f7fafb" stroke-width=".06"/><text x="${r.x+r.w/2}" y="${r.z+r.d/2}" text-anchor="middle">${esc(r.name)}</text></g>`).join('')}</svg>`;
 const photos=house.photos.filter(p=>!state.room||p.binding==='confirmed'&&p.roomId===state.room);$('#photos').innerHTML=photos.length?photos.map(p=>`<figure><img loading="lazy" src="${esc(p.src)}" alt="${esc(p.alt||'ภาพบ้าน')}"><figcaption>${esc(p.alt||'ภาพที่เจ้าของให้มา')}</figcaption></figure>`).join(''):'<p>ยังไม่มีภาพที่ยืนยันห้องนี้</p><p>ให้ AI เตรียมสำเนาภาพที่อนุญาตไว้ใน media/ แล้วเพิ่มการจับคู่ใน house-data.js</p>';
 if(renderer)$('#status').textContent=state.lens==='model'?'ลากหมุน · ล้อเมาส์ / 2 นิ้วซูม · แตะพื้นห้อง':'ข้อมูลบ้านสมมติ · ให้ AI แทนด้วยหลักฐานของคุณ';
 if(write){const q=new URLSearchParams({view:state.view,floor:state.floor,lens:state.lens});if(state.room)q.set('room',state.room);if(location.search!=='?'+q)history.pushState(null,'','?'+q);}
}
function pickRoom(id){const r=house.rooms.find(r=>r.id===id);if(r){state.room=id;state.floor=r.floor;state.view=r.floor;render();}}
document.addEventListener('click',e=>{const b=e.target.closest('button,[data-room]');if(!b)return;if(b.dataset.room)return pickRoom(b.dataset.room);if(b.dataset.view){state.view=b.dataset.view;if(['f1','f2'].includes(state.view))state.floor=state.view;state.room=null;}if(b.dataset.lens)state.lens=b.dataset.lens;if(b.dataset.quality)state.quality=b.dataset.quality;if(b.dataset.wall)state.wall=b.dataset.wall;if(b.id==='inside')state.view=state.floor;if(b.dataset.camera){if(b.dataset.camera==='reset')fit();else if(controls){camera.position.sub(controls.target).multiplyScalar(b.dataset.camera==='in'?.82:1.22).add(controls.target);controls.update();}dirty=true;return;}render();});
for(const key of ['builtins','furniture'])$('#'+key).addEventListener('change',e=>{state[key]=e.target.checked;render(false);});
document.addEventListener('keydown',e=>{if(e.target.matches('[data-room]')&&['Enter',' '].includes(e.key)){e.preventDefault();pickRoom(e.target.dataset.room);}if(e.target===$('#scene')&&e.key.toLowerCase()==='r')fit();});
addEventListener('popstate',()=>{readURL();render(false);});
if(renderer){let start=null;const ray=new T.Raycaster();renderer.domElement.addEventListener('pointerdown',e=>{start={x:e.clientX,y:e.clientY};});renderer.domElement.addEventListener('pointerup',e=>{if(!start||Math.hypot(e.clientX-start.x,e.clientY-start.y)>5||state.view==='whole')return;const r=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=ray.intersectObjects(picks.filter(p=>p.parent.visible))[0];if(hit)pickRoom(hit.object.userData.room);});new ResizeObserver(()=>{const r=$('#scene').getBoundingClientRect();if(r.width&&r.height){camera.aspect=r.width/r.height;camera.updateProjectionMatrix();renderer.setSize(r.width,r.height,false);dirty=true;}}).observe($('#scene'));function frame(){requestAnimationFrame(frame);if(document.hidden||state.lens!=='model')return;controls.update();if(dirty){applyWalls();renderer.render(scene,camera);dirty=false;}}frame();}
render(false);
