const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={CL:'มูสโฟมล้างหน้า',AC:'เซรั่มขวดขาว',BR:'เซรั่มขวดเหลืองเขียว',SU:'เซรั่มกันแดด',PO:'แป้งพัฟ'};
const status={awaiting_quote:'รอยืนยันสินค้าและแจ้งยอด',awaiting_payment:'รอชำระ',payment_review:'ตรวจสลิป',paid:'รับชำระแล้ว',packing:'กำลังแพ็ก',shipped:'จัดส่งแล้ว',cancelled:'ยกเลิกแล้ว'};
const errors={UNAUTHORIZED:'รหัสไม่ถูกต้องหรือหมดเวลา กรุณาเข้าสู่ระบบใหม่',LINE_NOT_READY:'LINE ยังไม่พร้อมส่งยอด กรุณาตั้งค่าการเชื่อมต่อก่อน',CHECK_PAYMENT_DETAILS:'ตรวจยอด รหัสรายการ เวลาโอน และช่องยืนยันเงินเข้าจริงให้ครบ',TRANSFER_OR_EVENT_ALREADY_USED:'รายการโอนนี้ถูกใช้แล้ว กรุณาตรวจรายการเดิม',TRANSFER_ALREADY_USED:'รายการโอนนี้ใช้กับ AI ใส่ซอสแล้ว',CONFIRM_STOCK_FIRST:'กรุณายืนยันว่ามีสินค้าพร้อมขาย',TRY_LATER:'ลองรหัสหลายครั้ง กรุณารอ 15 นาที',SERVICE_UNAVAILABLE:'ระบบยังไม่พร้อมหรือการเชื่อมต่อสะดุด กรุณาลองใหม่',ADMIN_NOT_CONFIGURED:'ยังไม่ได้ตั้งค่าหลังบ้าน',STATUS_CONFLICT:'สถานะเปลี่ยนแล้ว กรุณาโหลดรายการใหม่'};
let data={orders:[],handoffs:[]},active=null,busy=false;
async function api(action,body){const r=await fetch(`/api/mediral-commerce?action=${action}`,{method:body?'POST':'GET',credentials:'same-origin',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const j=await r.json();if(!r.ok||!j.ok)throw Error(errors[j.code]||`ทำรายการไม่ได้ (${j.code||r.status})`);return j;}
function note(s){$('#notice').textContent=s;}
async function load(){const [s,rows]=await Promise.all([api('status'),api('list')]);data=rows;$('#login').hidden=true;$('#workspace').hidden=false;$('#logout').hidden=false;$('#readiness').innerHTML=`<strong>${s.mode==='live'?'เปิดรับแชท Mediral':'พักรับแชท Mediral'}</strong><p>LINE: ${s.lineConfigured?'ตั้งค่าแล้ว':'ยังไม่ได้เชื่อม'} · ตรวจสลิป: ${s.slipConfigured?'ตั้งค่าแล้ว':'รอ EasySlip API'} · ส่งซ้ำอัตโนมัติ: ${s.retryConfigured?'ตั้งค่าแล้ว':'รอตั้งค่า'}</p><span class="muted">บัญชีเดียวกับ AI ใส่ซอส: ${esc(s.bank.name)} ${esc(s.bank.number)} · การมีค่าเชื่อมต่อยังไม่ใช่ผลทดสอบ OA จริง</span>`;
$('#outbox').innerHTML=s.outbox.length?s.outbox.map(x=>`<div class="delivery">${esc(x.kind)} · ${esc(x.status)} · ลอง ${x.attempts} ครั้ง · ${esc(x.error_code||'รอส่ง')}<br>${esc(x.id)}</div>`).join(''):'<p class="muted">ไม่มีข้อความค้างส่ง</p>';render();}
function render(){const topics={mediral:'ดูแลผิว',ai:'AI และการเรียนรู้',home:'ของใช้ในบ้าน'};$('#contacts').innerHTML=(data.contacts||[]).map(c=>`<div class="panel"><span class="muted">${esc(c.id)}</span><p>สนใจ: ${esc(Object.keys(c.house.interests||{}).map(k=>topics[k]||k).join(' · ')||'ยังไม่ระบุ')}</p><p>เลือกรับข่าว: ${esc(Object.keys(c.house.subscriptions||{}).map(k=>topics[k]||k).join(' · ')||'ยังไม่ได้เลือกรับ')}</p></div>`).join('')||'<p class="muted">ยังไม่มีข้อมูลความสนใจ</p>';const search=$('#search').value.toLowerCase(),filter=$('#filter').value;const rows=data.orders.filter(o=>(!filter||o.status===filter)&&`${o.id} ${o.name} ${o.phone}`.toLowerCase().includes(search));$('#orders').innerHTML=rows.length?rows.map(o=>`<article class="order"><span class="badge">${esc(status[o.status]||o.status)}</span><h2>${esc(o.id)}</h2><div class="facts"><div class="details">${esc(Object.entries(o.items).map(([k,q])=>`${names[k]} × ${q}`).join('\n'))}<p>${o.total?`รวม ${(o.total/100).toFixed(2)} บาท (ค่าส่ง ${(o.shipping/100).toFixed(2)})`:'ยังไม่แจ้งยอด'}</p></div><div>${esc(o.name)} · ${esc(o.phone)}<p>${esc(o.address)}</p></div></div>${o.paymentCheck?`<p class="muted">ตรวจสลิป: ${o.paymentCheck.ok?'ข้อมูลตรงเบื้องต้น — ยังต้องตรวจยอดเข้าจริง':esc(o.paymentCheck.reason)}<br>${o.hasReceipt?`<a href="/api/mediral-commerce?action=receipt&id=${encodeURIComponent(o.id)}">ดาวน์โหลดสลิปแบบส่วนตัว</a>`:'ไม่มีภาพสลิปในระบบ กรุณาตรวจในแชท LINE'}</p>`:''}${o.tracking?`<p>${esc(o.carrier)} · ${esc(o.tracking)}</p>`:''}<div class="actions">${(o.status==='awaiting_quote'?button(o,'quote','แจ้งยอดหลังเช็กของ'):'')}${(['awaiting_payment','payment_review'].includes(o.status)?button(o,'paid','ตรวจเงินเข้าแล้ว'):'')}${o.status==='paid'?button(o,'packing','เริ่มแพ็ก'):''}${['paid','packing'].includes(o.status)?button(o,'shipped','แจ้งเลขพัสดุ'):''}${['awaiting_quote','awaiting_payment'].includes(o.status)?button(o,'cancel','ยกเลิกรายการ'):''}${button(o,'pause','ให้คนดูแลรับช่วง')}</div></article>`).join(''):'<div class="panel">ยังไม่มีรายการในหมวดนี้</div>';
$('#handoffs').innerHTML=data.handoffs.map(x=>`<div class="panel">${esc(x.reason)}<p class="muted">LINE user: ${esc(x.id)} · ${esc(x.orderId||'ยังไม่มีออเดอร์')}</p><button data-user="${esc(x.id)}" data-command="resume">ให้บอทตอบต่อ</button></div>`).join('')||'<p class="muted">ไม่มีแชทรอรับช่วง</p>';}
function button(o,c,label){return `<button class="secondary" data-id="${esc(o.id)}" data-command="${c}">${label}</button>`;}
const thaiTime = ms => new Date(ms+7*3600000).toISOString().slice(0,19);
function field(label,name,value='',type='text'){return `<label>${esc(label)}<input name="${name}" type="${type}" value="${esc(value)}" required ${type==='number'?'min="0" step="0.01"':type==='datetime-local'?'step="1"':''}></label>`;}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-command]');if(!b||busy)return;const command=b.dataset.command,id=b.dataset.id,userId=b.dataset.user,o=data.orders.find(x=>x.id===id);active={command,id,userId};$('#editor-error').textContent='';$('#editor-title').textContent=({quote:'แจ้งยอดพร้อมบัญชีรับเงิน',paid:'ยืนยันยอดเข้าบัญชีจริง',shipped:'แจ้งเลขพัสดุ',packing:'เริ่มแพ็กสินค้า',cancel:'ยกเลิกรายการ',pause:'ให้คนดูแลรับช่วง',resume:'ให้บอทตอบต่อ'})[command];let fields='';
if(command==='quote')fields=Object.entries(o.items).map(([k,q])=>field(`${names[k]} × ${q} — ราคาต่อชิ้น (บาท)`,'price_'+k,o.prices?.[k]?o.prices[k]/100:'','number')).join('')+field('ค่าส่ง (บาท)','shipping',o.shipping!==undefined?o.shipping/100:'','number')+'<label><input type="checkbox" name="stockConfirmed" required>เช็กสินค้าพร้อมขายครบรายการแล้ว</label><p>ยอดนี้มีอายุ 24 ชั่วโมง ยืนยันแล้วระบบจะส่งบัญชีและยอดให้ลูกค้าทาง LINE</p>';
if(command==='paid')fields=field('ยอดที่เข้าจริง (บาท)','amount',o.total/100,'number')+field('รหัสธุรกรรมธนาคาร','transRef',o.paymentCheck?.transRef||'')+field('เวลาโอนตามสลิป (เวลาไทย)','transferredAt',o.paymentCheck?.transferredAt?thaiTime(o.paymentCheck.transferredAt):'','datetime-local')+'<label><input type="checkbox" name="confirmedReceived" required>ตรวจบัญชีธนาคารแล้ว ได้รับเงินเข้าจริงตรงออเดอร์นี้</label>';
if(command==='shipped')fields=field('บริษัทขนส่ง','carrier')+field('เลขพัสดุ','tracking');if(!fields)fields='<p>ตรวจแชทและรายการให้ตรงก่อนยืนยัน</p>';$('#editor-fields').innerHTML=fields;$('#editor').showModal();});
$('#editor-form').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;busy=true;$('#save').disabled=true;const f=new FormData(e.target),body={...active,prices:{}};for(const [k,v]of f){if(k.startsWith('price_'))body.prices[k.slice(6)]=v;else body[k]=k==='transferredAt'?v+'+07:00':v;}body.stockConfirmed=f.has('stockConfirmed');body.confirmedReceived=f.has('confirmedReceived');try{await api('update',body);$('#editor').close();await load();note('บันทึกแล้ว ตรวจแถบการแจ้งลูกค้าว่าข้อความส่งสำเร็จหรือยัง');}catch(err){$('#editor-error').textContent=err.message;}finally{busy=false;$('#save').disabled=false;}});
$('#close-editor').onclick=()=>$('#editor').close();$('#login-form').onsubmit=async e=>{e.preventDefault();const k=$('#key').value;$('#key').value='';try{await api('login',{key:k});await load();note('');}catch(err){note(err.message);}};$('#refresh').onclick=()=>load().then(()=>note('อัปเดตแล้ว')).catch(e=>note(e.message));$('#retry').onclick=()=>api('retry',{}).then(load).catch(e=>note(e.message));$('#logout').onclick=async()=>{await api('logout',{});location.reload();};$('#filter').onchange=render;$('#search').oninput=render;load().catch(()=>{});
