import {somchaiEpisodes as episodes} from './somchai-episodes.js';
const chapters=episodes.map(e=>e.pages);
export const somchaiWebtoon = {
  "id": "somchai",
  "title": "สมชาย เกิดใหม่ไปปลูกผัก",
  "posterTitle": "สมชาย\nเกิดใหม่ไปปลูกผัก",
  "format": "comic",
  "formatLabel": "เว็บตูน",
  "genres": [
    "แฟนตาซี",
    "เกิดใหม่",
    "ตลก",
    "อบอุ่น"
  ],
  "creator": "ทีมสมชาย",
  "studio": "Somchai Studio",
  "creatorKind": "team",
  "creatorId": "somchai",
  "city": "ไทย",
  "avatar": "ส",
  "avatarImage": "./assets/creators/logos/somchai.svg",
  "color": "#64824b",
  "poster": "./assets/somchai/brand/cover-art.webp",
  "position": "center 28%",
  episodes: episodes.length,
  edition: '100-v002',
  freeEpisodes: 5,
  episodePrice: 10,
  episodeCatalog: '/short/story/somchai/episodes/',
  episodeNames: episodes.map(e=>e.title),
  episodeDescriptions: episodes.map(e=>`ตอนที่ ${e.episode} · ${e.title}`),
  episodeCovers: episodes.map(e=>e.cover),
  episodeCards: episodes.map(e=>e.card),
  episodeThumbs: episodes.map(e=>e.thumb),
  episodeCoverSizes: episodes.map(e=>e.coverSize),
  episodeCardSizes: episodes.map(e=>e.cardSize),
  episodeThumbSizes: episodes.map(e=>e.thumbSize),
  "seriesLogo": "./assets/somchai/brand/logo-420.webp",
  "status": "พร้อมอ่าน 100 ตอน",
  "badge": "อ่านฟรี 5 ตอน",
  "age": "13+",
  "kicker": "ชีวิตแรกมีแต่งาน ชีวิตใหม่ขอมีสวน",
  "description": "สมชายทุ่มชีวิตให้การเรียนและการทำงาน จนถูกใช้งานหนัก ป่วย และจากไปโดยยังไม่ทันได้ใช้ชีวิต เมื่อเทพเจ้ามอบโอกาสเริ่มใหม่ในต่างโลก เขาจึงขอเพียงร่างกายแข็งแรง ที่เงียบสงบ และชีวิตเกษตรกร แต่ป่าที่ไม่มีใครกลับค่อย ๆ เต็มไปด้วยเรื่องชวนปวดหัวและความผูกพัน",
  "sampleLength": "100 ตอน · 1,339 หน้าเนื้อหา",
  "aiUsage": "ภาพและปกสร้างด้วย AI · เว็บตูนภาษาไทยดัดแปลงจากบทที่นำมาเรียบเรียง",
  "warnings": "มีฉากการเจ็บป่วยและเสียชีวิตในช่วงต้น ก่อนเริ่มชีวิตใหม่",
  "provenance": "เว็บตูนภาษาไทยดัดแปลง · ชุดสมชาย 1–100 ฉบับ v002",
  "readerNote": "ตอน 1–5 อ่านฟรี · ตอน 6–100 ปลดล็อกตอนละ 10 เหรียญทดลอง",
  "ongoing": true,
  "pilots": [],
  "heroLandscape": "./assets/somchai/brand/hero-wide.webp",
  "heroImage": "./assets/somchai/brand/hero-portrait.webp",
  "heroEpisode": 1,
  "heroCta": "อ่านฟรี 5 ตอน",
  "heroBadge": "100 ตอนพร้อมอ่าน",
  "heroKicker": "ชีวิตแรกมีแต่งาน ชีวิตใหม่ขอมีสวน",
  "heroDescription": "ขอแค่ชีวิตเงียบ ๆ กับจอบวิเศษหนึ่งด้าม แต่สวนในป่าต่างโลกกลับมีแขกที่ไม่ได้เชิญ… และพวกมันอาจไม่ใช่หมาธรรมดา",
  "shelfCta": "100 ตอนพร้อมอ่าน · ฟรี 5 ตอนแรก",
  "shareVersion": "v7",
  "shareImage": "./assets/somchai/brand/hero-wide.webp",
  "shareLayout": "wide",
  "sharePosition": "right center",
  "shareBadge": "100 ตอนพร้อมอ่าน · ฟรี 5 ตอนแรก",
  "shareDescription": "สมชายทุ่มชีวิตให้การเรียนและการทำงาน จนถูกใช้งานหนัก ป่วย และจากไปโดยยังไม่ทันได้ใช้ชีวิต เมื่อเทพเจ้ามอบโอกาสเริ่มใหม่ในต่างโลก เขาจึงขอเพียงร่างกายแข็งแรง ที่เงียบสงบ และชีวิตเกษตรกร แต่ป่าที่ไม่มีใครกลับค่อย ๆ เต็มไปด้วยเรื่องชวนปวดหัวและความผูกพัน · พร้อมอ่าน 100 ตอน · อ่านฟรีตอน 1–5 ตอน 6–100 ปลดล็อกตอนละ 10 เหรียญทดลอง",
  comicPages: chapters[0],
  comicChapters: chapters
};
