import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import {createPreviewServer} from './preview.mjs';
const {chromium}=await import(pathToFileURL(process.env.SHORT_PLAYWRIGHT||'/Users/Teem/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs').href);
const server=process.env.SHORT_BASE_URL?null:createPreviewServer();
if(server)await new Promise(r=>server.listen(0,'127.0.0.1',r));
const base=(process.env.SHORT_BASE_URL||`http://127.0.0.1:${server.address().port}`).replace(/\/$/,'');
const proof=process.env.SHORT_PROOF_DIR||'/private/tmp/torntor-sharing-qa';await mkdir(proof,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.SHORT_CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
const results=[];
async function run(name,task){try{await task();results.push({name,status:'pass'});console.log('PASS '+name);}catch(error){results.push({name,status:'fail',message:error.message});console.log('FAIL '+name+': '+error.message);}await writeFile(proof+'/results.json',JSON.stringify({base,results},null,2));}
async function setup(width,mode='native',id='somchai',ep=1){
 const c=await browser.newContext({viewport:{width,height:width<761?844:1000},isMobile:width<761,hasTouch:width<761,reducedMotion:'reduce'});
 await c.addInitScript(({mode})=>{
  window.shareCalls=[];window.copyCalls=[];
  Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async url=>{window.copyCalls.push(url);if(mode==='manual')throw new DOMException('Copy blocked','NotAllowedError');}}});
  Object.defineProperty(navigator,'share',{configurable:true,value:mode==='copy'||mode==='manual'?undefined:async data=>{window.shareCalls.push(data);if(mode==='cancel')throw new DOMException('Cancelled','AbortError');if(mode==='denied')throw new DOMException('Denied','NotAllowedError');}});
  Object.defineProperty(navigator,'canShare',{configurable:true,value:()=>mode!=='unsupported'});
  localStorage.setItem('tontor:prototype:v1',JSON.stringify({balance:120,saved:[],unlocked:['somchai:11'],progress:{}}));
 },{mode});
 const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto(base+`/short/story/${id}/?episode=${ep}`,{waitUntil:'networkidle'});
 return {c,p,errors};
}
async function geometry(p,selector){const box=await p.locator(selector).boundingBox();assert.ok(box&&box.width>=44&&box.height>=44,selector+' tap target');assert.ok(box.x>=0&&box.x+box.width<=p.viewportSize().width+1,selector+' fits viewport');assert.ok(await p.locator('#reader-toolbar').evaluate(e=>e.scrollWidth<=e.clientWidth+1));const close=await p.locator('[data-close="story-dialog"]').boundingBox();assert.ok(box.x+box.width<=close.x||box.y>=close.y+close.height||box.x>=close.x+close.width||box.y+box.height<=close.y,'no close-button overlap');}
try{
 for(const width of [320,390,1440])await run(`visible native share and current chapter link at ${width}`,async()=>{const {c,p,errors}=await setup(width);try{await geometry(p,'#reader-share');assert.equal(await p.locator('#reader-share').textContent(),'แชร์');await p.locator('#reader-share').click();await p.waitForFunction(()=>window.shareCalls.length===1);const first=await p.evaluate(()=>window.shareCalls[0]);assert.equal(first.url,'https://www.myclover.com/short/story/somchai/?episode=1');assert.match(first.title,/สมชาย/);assert.match(first.text,/มาอ่าน.*ตอนที่ 1.*3 ตอนแรกฟรี/);if(!await p.locator('[data-episode="2"]').isVisible())await p.locator('#reader-episodes').click();await p.locator('[data-episode="2"]').click();await p.locator('#reader-share').click();await p.waitForFunction(()=>window.shareCalls.length===2);assert.equal(await p.evaluate(()=>window.shareCalls[1].url),'https://www.myclover.com/short/story/somchai/?episode=2');assert.deepEqual(await p.evaluate(()=>window.copyCalls),[]);await p.screenshot({path:proof+`/reader-share-${width}.png`});if(width===1440){await p.locator('#reader-expand').click();await geometry(p,'#reader-share');await p.locator('#reader-share').click();await p.waitForFunction(()=>window.shareCalls.length===3);}assert.deepEqual(errors,[]);}finally{await c.close();}});
 await run('desktop copy fallback includes a visible confirmation above the reader',async()=>{const {c,p,errors}=await setup(1440,'copy','somchai',11);try{await p.locator('#reader-share').click();await p.waitForFunction(()=>window.copyCalls.length===1);assert.equal(await p.evaluate(()=>window.copyCalls[0]),'https://www.myclover.com/short/story/somchai/?episode=11');await p.locator('#toast').waitFor({state:'visible'});assert.equal(await p.locator('#toast').evaluate(e=>e.parentElement.id),'story-dialog');assert.ok(await p.locator('#toast').evaluate(e=>{const r=e.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return hit===e||e.contains(hit);}));await p.screenshot({path:proof+'/copy-confirmation-desktop.png'});assert.deepEqual(errors,[]);}finally{await c.close();}});
 for(const mode of ['denied','unsupported'])await run(`${mode} native sharing falls back to copying`,async()=>{const {c,p,errors}=await setup(390,mode);try{await p.locator('#reader-share').click();await p.waitForFunction(()=>window.copyCalls.length===1);assert.equal(await p.evaluate(()=>window.copyCalls[0]),'https://www.myclover.com/short/story/somchai/?episode=1');assert.deepEqual(errors,[]);}finally{await c.close();}});
 await run('cancel does not copy a link or show an error',async()=>{const {c,p,errors}=await setup(390,'cancel');try{await p.locator('#reader-share').click();await p.waitForFunction(()=>!document.querySelector('#reader-share').disabled);assert.equal(await p.evaluate(()=>window.shareCalls.length),1);assert.deepEqual(await p.evaluate(()=>window.copyCalls),[]);assert.equal(await p.locator('#toast').isVisible(),false);assert.equal(await p.locator('#share-link-dialog[open]').count(),0);assert.deepEqual(errors,[]);}finally{await c.close();}});
 await run('blocked clipboard offers a selectable link and a working retry',async()=>{const {c,p,errors}=await setup(320,'manual');try{await p.locator('#reader-share').click();await p.locator('#share-link-dialog[open]').waitFor();assert.equal(await p.locator('#share-link-input').inputValue(),'https://www.myclover.com/short/story/somchai/?episode=1');assert.ok(await p.locator('#share-link-dialog').evaluate(e=>e.scrollWidth<=e.clientWidth+1));await p.locator('#copy-share-link').click();assert.equal(await p.locator('#toast').evaluate(e=>e.parentElement.id),'share-link-dialog');await p.screenshot({path:proof+'/manual-share-mobile.png'});await p.evaluate(()=>navigator.clipboard.writeText=async url=>window.copyCalls.push(url));await p.locator('#copy-share-link').click();await p.waitForFunction(()=>!document.querySelector('#share-link-dialog').open);assert.equal(await p.locator('#toast').evaluate(e=>e.parentElement.id),'story-dialog');assert.deepEqual(errors,[]);}finally{await c.close();}});
 for(const [id,selector,pattern] of [['novel-ghost','#reader-share',/มาอ่าน.*บทที่ 1/],['village','#share-story',/มาดู.*ตอนที่ 1/]])await run(`sharing ${id} uses the correct invitation`,async()=>{const {c,p,errors}=await setup(320,'native',id);try{if(id.startsWith('novel'))await geometry(p,selector);await p.locator(selector).click();await p.waitForFunction(()=>window.shareCalls.length===1);const data=await p.evaluate(()=>window.shareCalls[0]);assert.equal(data.url,`https://www.myclover.com/short/story/${id}/?episode=1`);assert.match(data.text,pattern);assert.deepEqual(errors,[]);}finally{await c.close();}});
}finally{await browser.close();if(server)await new Promise(r=>server.close(r));}
if(results.some(r=>r.status==='fail'))process.exitCode=1;
