import assert from 'node:assert/strict';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {pathToFileURL} from 'node:url';
import {createPreviewServer} from './preview.mjs';
import {somchaiWebtoon as story} from './somchai-webtoon.js';
const {chromium}=await import(pathToFileURL(process.env.SHORT_PLAYWRIGHT||'/Users/Teem/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs').href);
const server=process.env.SHORT_BASE_URL?null:createPreviewServer();if(server)await new Promise(r=>server.listen(0,'127.0.0.1',r));
const base=(process.env.SHORT_BASE_URL||`http://127.0.0.1:${server.address().port}`).replace(/\/$/,'');
const proof=process.env.SHORT_PROOF_DIR||'/private/tmp/tontor-somchai-v001-qa';await mkdir(proof,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.SHORT_CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
const key='tontor:prototype:v1',results=[];
async function run(name,task){try{await task();results.push({name,status:'pass'});console.log('PASS '+name);}catch(e){results.push({name,status:'fail',message:e.message,stack:e.stack});console.log('FAIL '+name+': '+e.message);}await writeFile(proof+'/results.json',JSON.stringify({base,results},null,2));}
async function account(width,balance=70){const c=await browser.newContext({viewport:{width,height:width<760?844:1000},isMobile:width<760,hasTouch:width<760,reducedMotion:'reduce'});await c.addInitScript(({key,balance})=>{if(!localStorage.getItem(key))localStorage.setItem(key,JSON.stringify({balance,saved:[],unlocked:[],progress:{}}));if(!localStorage.getItem('torntor:platform:demo:v1'))localStorage.setItem('torntor:platform:demo:v1',JSON.stringify({migrated:true,free:balance,paid:0,unlocked:[],daily:[new Date(Date.now()+7*3600000).toISOString().slice(0,10)]}));},{key,balance});return c;}
const state=page=>page.evaluate(key=>JSON.parse(localStorage.getItem(key)),key);
async function geometry(p){for(const s of ['html','#story-dialog','#comic-reader','#reader-toolbar'])assert.ok(await p.locator(s).evaluate(e=>e.scrollWidth<=e.clientWidth+2),s+' overflow');}
async function chooseChapter(p,ep){const button=p.locator(`[data-episode="${ep}"]`);if(!await button.isVisible())await p.locator('#reader-episodes').click();await button.click();}
async function readChapter(p,ep,full=false){assert.match(await p.locator('.reader-heading strong').textContent(),new RegExp(story.episodeNames[ep-1].replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.equal(await p.locator('.webtoon-page').count(),story.comicChapters[ep-1].length);assert.equal(await p.locator('.comic-cover').count(),1);assert.equal(await p.locator('.webtoon-transcript').count(),0);assert.equal(await p.locator('#comic-reader details').count(),0);assert.match(await p.locator('.comic-cover img').getAttribute('src'),new RegExp(`episode-${String(ep).padStart(2,'0')}\\.webp`));const imgs=full?await p.locator('#comic-reader img').all():[p.locator('.comic-cover img'),p.locator('.webtoon-page img').first()];for(const img of imgs){await img.evaluate(e=>e.scrollIntoView({block:'start'}));assert.ok(await img.evaluate(async e=>{await e.decode();return e.naturalWidth>700&&e.naturalHeight>1500;}));}await geometry(p);}
try{
 await run('223 pages, 20 covers; preserve originals and verify new WebP hashes',async()=>{assert.equal(story.episodes,20);assert.equal(story.comicChapters.flat().length,223);assert.equal(story.episodeCovers.length,20);assert.equal(story.episodeCards.length,20);const receipt=JSON.parse(await readFile(new URL('./docs/somchai-v001.json',import.meta.url)));for(const f of receipt.files){const b=await readFile(new URL('./assets/somchai/v001/'+f.file,import.meta.url));assert.equal(createHash('sha256').update(b).digest('hex'),f.sha256,f.file);}const added=JSON.parse(await readFile(new URL('./docs/somchai-v002.json',import.meta.url)));assert.equal(added.storyPages,115);for(const f of added.files){const b=await readFile(new URL('./assets/somchai/v002/'+f.file,import.meta.url));assert.equal(createHash('sha256').update(b).digest('hex'),f.sha256,f.file);}});
 for(const width of [320,390,992,1440])await run(`responsive hero, episode covers and free reading ${width}`,async()=>{const c=await account(width,0);try{const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/short/',{waitUntil:'networkidle'});const ids=await p.locator('.hc-slide').evaluateAll(es=>es.map(e=>e.dataset.hcId));assert.equal(ids.length,5);assert.equal(await p.locator('.community-card').count(),4);await p.locator(`[data-hc-index="${ids.indexOf('somchai')}"]`).click();await p.waitForFunction(()=>document.querySelector('.hc-hero').dataset.hcActive==='somchai');const h=p.locator('[data-hc-id="somchai"]');assert.match(await h.locator('.hc-eyebrow').textContent(),/SPOTLIGHT.*มาแรง/s);await h.locator('.hc-series-logo').evaluate(e=>e.decode());await h.locator('.hc-visual img').evaluate(e=>e.decode());assert.equal(await h.locator('video').count(),0);await p.screenshot({path:proof+`/hero-${width}.png`});await h.locator('.hc-watch').click();assert.match(p.url(),/episode=1/);assert.equal(await p.locator('.episode-cover-card').count(),20);assert.equal(await p.locator('.episode-cover-card.locked').count(),17);await p.locator('#story-series-logo').evaluate(e=>e.decode());await readChapter(p,1);await p.locator('#comic-reader').evaluate(e=>e.scrollTop=0);if(width<760)await p.locator('#reader-episodes').click();await p.locator('.episode-cover-card img').first().evaluate(e=>e.decode());await p.screenshot({path:proof+`/episode-covers-${width}.png`});if(width<760)await p.locator('#reader-panel-close').click();for(const ep of [2,3]){await chooseChapter(p,ep);await readChapter(p,ep);}assert.equal((await state(p)).balance,0);assert.equal(await p.locator('#unlock-dialog[open]').count(),0);await p.locator('[data-read-next]').click();assert.equal(await p.locator('#unlock-dialog[open]').count(),1);assert.match(await p.locator('#unlock-description').textContent(),/ตอนที่ 4/);assert.match(await p.locator('#confirm-unlock').textContent(),/รับเหรียญทดลองเพิ่ม/);assert.match(await p.locator('.reader-heading strong').textContent(),/มื้อแรก/);assert.deepEqual(errors,[]);}finally{await c.close();}});
 await run('all twenty chapters, each paid unlock deducts once and persists',async()=>{const c=await account(390,170);try{const p=await c.newPage(),errors=[],missing=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)missing.push(r.url());});await p.goto(base+'/short/story/somchai/?episode=1',{waitUntil:'networkidle'});for(let ep=1;ep<=20;ep++){if(ep>1)await chooseChapter(p,ep);if(ep>3){assert.equal(await p.locator('#unlock-dialog[open]').count(),1);assert.match(await p.locator('#unlock-cover').getAttribute('src'),new RegExp(`episode-${String(ep).padStart(2,'0')}-card`));const before=await state(p);assert.equal(before.balance,170-(ep-4)*10);await p.locator('#confirm-unlock').click();await p.waitForFunction(()=>!document.querySelector('#unlock-dialog').open);assert.equal((await state(p)).balance,before.balance-10);}await readChapter(p,ep,true);assert.match(p.url(),new RegExp(`episode=${ep}$`));}assert.equal((await state(p)).balance,0);assert.equal((await state(p)).unlocked.length,17);assert.equal(await p.locator('[data-read-next]').count(),0);assert.equal(await p.locator('[data-reader-finish]').count(),1);assert.match(await p.locator('#completion-price').textContent(),/ปลดล็อกครบแล้ว/);await p.reload({waitUntil:'networkidle'});await readChapter(p,20);for(const ep of [7,4,11,20]){await chooseChapter(p,ep);assert.equal(await p.locator('#unlock-dialog[open]').count(),0);assert.equal((await state(p)).balance,0);await readChapter(p,ep);}await p.locator('.webtoon-page img').first().evaluate(e=>e.decode());if(await p.locator('#reader-expand').isVisible())await p.locator('#reader-expand').click();await p.locator('#comic-reader').evaluate(e=>e.scrollTop=(e.scrollHeight-e.clientHeight)*.36);await p.waitForFunction(key=>JSON.parse(localStorage.getItem(key)).progress.somchai?.episode===20&&JSON.parse(localStorage.getItem(key)).progress.somchai?.time>0,key);await p.locator('[data-close="story-dialog"]').click();await p.goto(base+'/short/story/somchai/?episode=20',{waitUntil:'networkidle'});await p.waitForFunction(()=>document.querySelector('#comic-reader').scrollTop>0);const fraction=await p.locator('#comic-reader').evaluate(e=>e.scrollTop/(e.scrollHeight-e.clientHeight));assert.ok(Math.abs(fraction-.36)<.03,'resume '+fraction);assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);}finally{await c.close();}});
 await run('paid direct link, cancel, insufficient coins and simulated checkout credit',async()=>{const c=await account(390,9);try{const p=await c.newPage();await p.goto(base+'/short/story/somchai/?episode=11',{waitUntil:'networkidle'});assert.equal(await p.locator('#unlock-dialog[open]').count(),1);assert.equal((await state(p)).balance,9);assert.match(await p.locator('.webtoon-page img').first().getAttribute('src'),/episodes\/01\/pages/);await p.locator('[data-close="unlock-dialog"]').click();assert.equal((await state(p)).unlocked.length,0);await chooseChapter(p,11);await p.locator('#confirm-unlock').click();assert.equal(await p.locator('#wallet-dialog[open]').count(),1);await p.locator('[data-pack]').first().click();await p.locator('#checkout-pay').click();await p.locator('#simulate-paid').click();await p.waitForFunction(()=>document.querySelector('#payment-result').textContent.includes('ได้รับ'));await p.locator('#checkout-close').click();const before=(await state(p)).balance;assert.ok(before>10);await chooseChapter(p,11);await p.locator('#confirm-unlock').click();await p.waitForFunction(()=>!document.querySelector('#unlock-dialog').open);assert.equal((await state(p)).balance,before-10);await readChapter(p,11);await p.screenshot({path:proof+'/unlocked-episode11-mobile.png'});}finally{await c.close();}});
 await run('new social card and static metadata',async()=>{const c=await browser.newContext();try{const p=await c.newPage();const html=await(await p.request.get(base+'/short/story/somchai/')).text();assert.match(html,/og:image[^>]+somchai-v5/);assert.match(html,/og:description[^>]+อ่านฟรีตอน 1–3/);await p.setContent(`<img src="${base}/short/assets/og/somchai-v5.jpg">`);assert.deepEqual(await p.locator('img').evaluate(async e=>{await e.decode();return[e.naturalWidth,e.naturalHeight]}),[1200,630]);}finally{await c.close();}});
}finally{await browser.close();if(server)await new Promise(r=>server.close(r));}
if(results.some(r=>r.status==='fail'))process.exitCode=1;
