import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import {createPreviewServer} from './preview.mjs';
const {chromium}=await import(pathToFileURL(process.env.SHORT_PLAYWRIGHT||'/Users/Teem/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs').href);
const server=process.env.SHORT_BASE_URL?null:createPreviewServer();if(server)await new Promise(r=>server.listen(0,'127.0.0.1',r));
const base=process.env.SHORT_BASE_URL||`http://127.0.0.1:${server.address().port}`,proof=process.env.SHORT_PROOF_DIR||'/private/tmp/tontor-clean-shell';await mkdir(proof,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.SHORT_CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),results=[];
async function run(name,task){try{await task();results.push({name,status:'pass'});console.log('PASS '+name);}catch(e){results.push({name,status:'fail',message:e.message,stack:e.stack});console.log('FAIL '+name+': '+e.message);}await writeFile(proof+'/results.json',JSON.stringify({base,results},null,2));}
try{
 for(const width of [320,390,760,992,1440,2560])await run(`clean browse and reader drawer ${width}`,async()=>{const c=await browser.newContext({viewport:{width,height:width<=760?844:1000},isMobile:width<=760,hasTouch:width<=760,reducedMotion:'reduce'});try{const p=await c.newPage(),errors=[],missing=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)missing.push(r.url());});await p.goto(base+'/short/',{waitUntil:'networkidle'});assert.equal(await p.locator('#catalog-grid .story-card').count(),9);assert.equal(await p.locator('.community-card').count(),4);assert.ok(await p.locator('#catalog').evaluate(e=>e.getBoundingClientRect().top<document.querySelector('#pilots').getBoundingClientRect().top));assert.equal(await p.locator('.section-kicker:visible').count(),0);assert.ok(await p.locator('html').evaluate(e=>e.scrollWidth<=e.clientWidth+1));await p.screenshot({path:proof+`/browse-${width}.png`});await p.goto(base+'/short/story/somchai/?episode=2',{waitUntil:'networkidle'});assert.equal(await p.locator('#story-about').getAttribute('open'),null);assert.equal(await p.locator('#reader-settings').isVisible(),false);assert.equal(await p.locator('.webtoon-transcript').count(),0);assert.ok(await p.locator('#comic-reader').evaluate(e=>e.scrollWidth<=e.clientWidth+1));await p.locator('.comic-cover img').evaluate(e=>e.decode());if(width<=760){assert.equal(await p.locator('#story-panel').isVisible(),false);const h=await p.locator('#comic-reader').evaluate(e=>e.clientHeight);assert.ok(h>innerHeightForTest(width)-90,'mobile reader uses viewport');await p.screenshot({path:proof+`/reader-${width}.png`});await p.locator('#reader-episodes').click();assert.equal(await p.locator('#reader-episodes').getAttribute('aria-expanded'),'true');await p.waitForFunction(()=>document.activeElement?.dataset.episode==='2');await p.keyboard.press('Escape');assert.equal(await p.locator('#story-panel').isVisible(),false);assert.equal(await p.locator('#story-dialog').getAttribute('open'),'');assert.equal(await p.locator('#reader-episodes').evaluate(e=>e===document.activeElement),true);await p.locator('#reader-episodes').click();}else{assert.equal(await p.locator('#story-panel').isVisible(),true);const a=await p.locator('#comic-reader').boundingBox(),b=await p.locator('#story-panel').boundingBox();assert.ok(a.width>b.width*.95,'desktop gives reading equal or greater space');}
 await p.locator('.episode-cover-card img').first().evaluate(e=>e.decode());await p.screenshot({path:proof+`/chapters-${width}.png`});await p.locator('#story-about > summary').click();assert.equal(await p.locator('#story-description').isVisible(),true);await p.locator('#story-about > summary').click();await p.locator('[data-episode="3"]').click();assert.equal(await p.locator('#reader-episodes').textContent(),'ตอน 3 / 10 ▾');if(width<=760)assert.equal(await p.locator('#story-panel').isVisible(),false);else{await p.locator('#reader-expand').click();assert.equal(await p.locator('#story-panel').isVisible(),false);await p.locator('#reader-episodes').click();assert.equal(await p.locator('#story-panel').isVisible(),true);await p.locator('#reader-panel-close').click();assert.equal(await p.locator('#story-panel').isVisible(),false);assert.equal(await p.locator('#story-dialog').getAttribute('open'),'');await p.locator('#reader-expand').click();}await p.locator('[data-close="story-dialog"]').click();await p.goto(base+'/short/story/novel-ghost/?episode=1',{waitUntil:'networkidle'});assert.equal(await p.locator('#reader-preferences').isVisible(),false);await p.locator('#reader-settings').click();assert.equal(await p.locator('#reader-preferences').isVisible(),true);await p.locator('[data-reader-theme="night"]').click();await p.locator('[data-reader-size="1"]').click();assert.equal(await p.locator('#comic-reader').getAttribute('data-theme'),'night');assert.equal(await p.locator('#reader-size-value').textContent(),'19');await p.keyboard.press('Escape');assert.equal(await p.locator('#reader-preferences').isVisible(),false);assert.equal(await p.locator('#story-dialog').getAttribute('open'),'');await p.locator('[data-close="story-dialog"]').click();await p.goto(base+'/short/story/north/?episode=1',{waitUntil:'networkidle'});assert.equal(await p.locator('#story-dialog').evaluate(e=>e.classList.contains('reading-mode')),false);assert.equal(await p.locator('#story-panel').isVisible(),true);assert.equal(await p.locator('#video-navigation').isVisible(),true);await p.screenshot({path:proof+`/movie-${width}.png`});assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);
 }finally{await c.close();}});
}finally{await browser.close();if(server)await new Promise(r=>server.close(r));}
function innerHeightForTest(width){return width<=760?844:1000;}
if(results.some(r=>r.status==='fail'))process.exitCode=1;
