import assert from 'node:assert/strict';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {pathToFileURL} from 'node:url';
import {createPreviewServer} from './preview.mjs';
import {somchaiWebtoon as story} from './somchai-webtoon.js';
import {freeEpisodeCount,episodeCost} from './platform/rules.js';
const {chromium}=await import(pathToFileURL(process.env.SHORT_PLAYWRIGHT||'/Users/Teem/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs').href);
const server=process.env.SHORT_BASE_URL?null:createPreviewServer();if(server)await new Promise(r=>server.listen(0,'127.0.0.1',r));
const base=(process.env.SHORT_BASE_URL||`http://127.0.0.1:${server.address().port}`).replace(/\/$/,'');
const proof=process.env.SHORT_PROOF_DIR||'/private/tmp/somchai-100-qa';await mkdir(proof,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.SHORT_CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),key='tontor:prototype:v1',results=[];
async function run(name,fn){if(process.env.SHORT_SOMCHAI_VERIFY&&!new RegExp(process.env.SHORT_SOMCHAI_VERIFY).test(name))return;try{await fn();results.push({name,status:'pass'});console.log('PASS '+name)}catch(e){results.push({name,status:'fail',error:e.stack});console.log('FAIL '+name+': '+e.message)}await writeFile(proof+'/results.json',JSON.stringify({base,results},null,2))}
async function account(width,balance=0){const c=await browser.newContext({viewport:{width,height:width<760?844:1000},isMobile:width<760,hasTouch:width<760,reducedMotion:'reduce'});await c.addInitScript(({key,balance})=>{if(!localStorage.getItem(key))localStorage.setItem(key,JSON.stringify({balance,saved:[],unlocked:[],progress:{},contentEditions:{somchai:'100-v002'}}));if(!localStorage.getItem('torntor:platform:demo:v1'))localStorage.setItem('torntor:platform:demo:v1',JSON.stringify({migrated:true,free:balance,paid:0,unlocked:[],daily:[new Date(Date.now()+7*3600000).toISOString().slice(0,10)]}));},{key,balance});return c}
const state=p=>p.evaluate(key=>JSON.parse(localStorage.getItem(key)),key);
async function choose(p,ep){const b=p.locator(`[data-episode="${ep}"]`);if(!await b.isVisible())await p.locator('#reader-episodes').click();await b.click()}
async function read(p,ep,last=false){assert.equal(await p.locator('.webtoon-page').count(),story.comicChapters[ep-1].length);assert.equal(await p.locator('.comic-cover').count(),1);assert.equal(await p.locator('.webtoon-transcript').count(),0);assert.match(await p.locator('.reader-heading strong').textContent(),new RegExp(story.episodeNames[ep-1].replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));const imgs=[p.locator('.comic-cover img'),p.locator('.webtoon-page img').first(),...(last?[p.locator('.webtoon-page img').last()]:[])];for(const img of imgs){await img.evaluate(e=>e.scrollIntoView({block:'start'}));assert.ok(await img.evaluate(async e=>{await e.decode();return e.naturalWidth===Number(e.getAttribute("width"))&&e.naturalHeight===Number(e.getAttribute("height"))}),`chapter ${ep}: decoded image matches supplied dimensions`);assert.match(await img.getAttribute('src'),/100-v002/)}assert.ok(await p.locator('#comic-reader').evaluate(e=>e.scrollWidth<=e.clientWidth+2))}
try{
 await run('canonical 100 chapters / 1,339 pages, optimized hashes, pricing and retired assets',async()=>{assert.equal(story.episodes,100);assert.equal(story.comicChapters.flat().length,1339);assert.equal(story.episodeCovers.length,100);assert.equal(freeEpisodeCount(story),5);assert.equal(episodeCost(story,5),0);assert.equal(episodeCost(story,6),10);assert.equal(episodeCost(story,100),10);const receipt=JSON.parse(await readFile(new URL('./docs/somchai-100-v002.json',import.meta.url)));assert.ok(receipt.reductionPercent>60);for(const f of receipt.files){const b=await readFile(new URL('./assets/somchai/100-v002/'+f.file,import.meta.url));assert.equal(createHash('sha256').update(b).digest('hex'),f.sha256,f.file)}for(const v of ['v001','v002','v003'])await assert.rejects(readFile(new URL(`./assets/somchai/${v}/assets/covers/episode-01.webp`,import.meta.url)));});
 for(const width of [320,390,1440])await run('large cover catalogue, ranges, search and reader navigation '+width,async()=>{const c=await account(width);try{const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/short/',{waitUntil:'networkidle'});const h=p.locator('[data-hc-id="somchai"]');assert.match(await h.textContent(),/อ่านฟรี 5 ตอน/);await h.locator('.hc-details').click();await p.waitForURL('**/somchai/episodes/');assert.equal(await p.locator('.episode-tile').count(),20);assert.equal(await p.locator('.episode-status.free').count(),5);await p.locator('.episode-tile img').first().evaluate(e=>e.decode());assert.ok((await p.locator('.episode-art').first().boundingBox()).width>=130);assert.ok(await p.locator('html').evaluate(e=>e.scrollWidth<=e.clientWidth+1));await p.screenshot({path:proof+`/catalog-${width}.png`,fullPage:false});await p.locator('[data-range="81"]').click();assert.equal(await p.locator('.episode-tile').count(),20);assert.equal(await p.locator('.episode-tile').last().getAttribute('data-episode'),'100');await p.locator('#find-episode').fill('จอมมารบ่นในใจ ช่วงหลัง');assert.equal(await p.locator('.episode-tile').count(),1);await p.locator('#find-episode').fill('ไม่มีตอนชื่อนี้');assert.ok(await p.locator('#no-episodes').isVisible());await p.locator('[data-range="all"]').click();assert.equal(await p.locator('.episode-tile').count(),100);await p.locator('[data-range="1"]').click();await p.locator('[data-episode="5"]').click();await p.waitForSelector('#story-dialog[open]');await read(p,5);assert.equal(await p.locator('#unlock-dialog[open]').count(),0);assert.equal(await p.locator('.episode-cover-card.locked').count(),95);await p.locator('#comic-reader').evaluate(e=>e.scrollTop=0);if(width<760)await p.locator('#reader-episodes').click();assert.ok((await p.locator('.episode-cover-card').first().boundingBox()).width>=120);assert.equal(await p.locator('#reader-all-episodes').getAttribute('href'),'/short/story/somchai/episodes/');await p.screenshot({path:proof+`/picker-${width}.png`});assert.deepEqual(errors,[]);}finally{await c.close()}});
 await run('all 100 chapters mapped, 95 paid unlocks deduct once and survive reload',async()=>{const c=await account(390,950);try{const p=await c.newPage(),errors=[],missing=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)missing.push(r.url())});await p.goto(base+'/short/story/somchai/?episode=1',{waitUntil:'networkidle'});const chosen=process.env.SHORT_BASE_URL?[1,4,5,6,21,30,31,50,75,99,100]:Array.from({length:100},(_,i)=>i+1);for(const ep of chosen){if(ep>1)await choose(p,ep);if(ep>5){assert.equal(await p.locator('#unlock-dialog[open]').count(),1);const before=(await state(p)).balance;await p.locator('#confirm-unlock').click();await p.waitForFunction(()=>!document.querySelector('#unlock-dialog').open);assert.equal((await state(p)).balance,before-10)}await read(p,ep,true);assert.match(p.url(),new RegExp(`episode=${ep}$`));if(ep%20===0)console.log('Checked chapter '+ep)}if(!process.env.SHORT_BASE_URL){assert.equal((await state(p)).balance,0);assert.equal((await state(p)).unlocked.length,95)}const balance=(await state(p)).balance;assert.equal(await p.locator('[data-read-next]').count(),0);await p.reload({waitUntil:'networkidle'});await read(p,100);for(const ep of [5,6,100]){await choose(p,ep);assert.equal(await p.locator('#unlock-dialog[open]').count(),0);assert.equal((await state(p)).balance,balance);await read(p,ep)}await p.locator('#comic-reader').evaluate(e=>e.scrollTop=(e.scrollHeight-e.clientHeight)*.36);await p.waitForFunction(key=>JSON.parse(localStorage.getItem(key)).progress.somchai?.episode===100&&JSON.parse(localStorage.getItem(key)).progress.somchai?.time>0,key);await p.reload({waitUntil:'networkidle'});await p.waitForFunction(()=>document.querySelector('#comic-reader').scrollTop>0);assert.ok(Math.abs(await p.locator('#comic-reader').evaluate(e=>e.scrollTop/(e.scrollHeight-e.clientHeight))-.36)<.03);assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);}finally{await c.close()}});
 await run('free direct links and paid direct link with insufficient coins',async()=>{const c=await account(390,9);try{const p=await c.newPage();for(const ep of [4,5]){await p.goto(base+`/short/story/somchai/?episode=${ep}`,{waitUntil:'networkidle'});await read(p,ep);assert.equal(await p.locator('#unlock-dialog[open]').count(),0);assert.equal((await state(p)).balance,9)}await p.goto(base+'/short/story/somchai/?episode=6',{waitUntil:'networkidle'});assert.equal(await p.locator('#unlock-dialog[open]').count(),1);await p.locator('#confirm-unlock').click();assert.equal(await p.locator('#wallet-dialog[open]').count(),1);assert.equal((await state(p)).balance,9);}finally{await c.close()}});
 await run('new 100-episode OG metadata and share image',async()=>{const c=await browser.newContext();try{const p=await c.newPage();const source=await(await p.request.get(base+'/short/story/somchai/')).text();assert.match(source,/somchai-v7/);assert.match(source,/100 ตอน/);assert.match(source,/อ่านฟรีตอน 1–5/);await p.setContent(`<img src="${base}/short/assets/og/somchai-v7.jpg">`);assert.deepEqual(await p.locator('img').evaluate(async e=>{await e.decode();return [e.naturalWidth,e.naturalHeight]}),[1200,630]);}finally{await c.close()}});
}finally{await browser.close();if(server)await new Promise(r=>server.close(r));}
if(results.some(r=>r.status==='fail'))process.exitCode=1;
