import {build} from 'esbuild';
import {copyFile,mkdir,writeFile,readdir,unlink} from 'node:fs/promises';
import path from 'node:path';
process.chdir(path.resolve(import.meta.dirname,'..'));
await mkdir('assets',{recursive:true});
await mkdir('reports',{recursive:true});
const result=await build({entryPoints:['app/main.js'],bundle:true,format:'esm',splitting:true,outdir:'assets',entryNames:'home',chunkNames:'[name]-[hash]',minify:true,sourcemap:false,target:['es2022'],metafile:true,legalComments:'eof'});
await writeFile('reports/build.json',JSON.stringify(result.metafile,null,2));
for(const name of await readdir('assets'))if(/^(scene|chunk)-[\w-]+\.js$/.test(name)&&!result.metafile.outputs[`assets/${name}`])await unlink(`assets/${name}`);
await copyFile('app/index.html','index.html');
await copyFile('app/styles.css','assets/home.css');
console.log('Built static route /showcase/house/');
