const API='/api/command';
const AUTH='/api/backoffice-auth';
const TEAMBOOK_COMMAND='https://teambook.me/command/';
let brief=null,mode='CREATE',chartKey='operations';
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmtDate=value=>{if(!value)return 'ยังไม่มีสัญญาณ';try{return new Intl.DateTimeFormat('th-TH',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value))}catch{return String(value)}};
function toast(message,bad=false){const el=$('toast');if(!el)return;el.textContent=message;el.style.background=bad?'#2a1514':'#15251b';el.style.borderColor=bad?'#6b3733':'#2c6040';el.style.color=bad?'#f1aaa4':'#a8e2bb';el.classList.add('show');clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>el.classList.remove('show'),3800)}
function unlock(){document.body.classList.remove('locked');$('gate')?.classList.add('hidden')}
function lock(message=''){document.body.classList.add('locked');$('gate')?.classList.remove('hidden');if(message)$('gateMsg').textContent=message}
async function request(url,options={}){const response=await fetch(url,{cache:'no-store',...options});let data={};try{data=await response.json()}catch{}return{response,data}}
function packetText(op){return `# MYCLOVER OPERATION\nID: ${op.id||''}\nMODE: ${op.mode}\nCHAIN: ${op.chainState||'ACTION'}\nPROJECT: ${op.project}\nGOAL: ${op.goal}\nNEXT ACTION: ${op.nextAction||'-'}\nOWNER / AGENT: ${op.owner||'-'}\nSOURCE TO OBEY: ${op.source||'-'}\nEXPECTED OUTPUT: ${op.output||'-'}\nSUCCESS CHECK: ${op.successCheck||'-'}\nDO NOT BREAK: ${op.guardrails||'-'}\nSTATUS: ${op.status||'QUEUED'}\n\nTCG FLOW\nACTION = execute current move.\nPASS = hand priority/context forward.\nGO AGAIN = action resolved but chain continues.\nCLOSE CHAIN = success check passed.\n\nHOUSE RULE\nThis queue belongs to myClover. TeamBook work lives at ${TEAMBOOK_COMMAND}.`}
async function copyText(text){try{await navigator.clipboard.writeText(text);return true}catch{return false}}
function formData(){return{action:'create',mode,project:$('project').value.trim(),goal:$('goal').value.trim(),nextAction:$('nextAction').value.trim(),owner:$('owner').value.trim(),source:$('source').value.trim(),output:$('output').value.trim(),successCheck:$('success').value.trim(),guardrails:$('guardrails').value.trim()}}
async function saveOperation(openKeen=false){const data=formData();if(!data.project||!data.goal){toast('ต้องมี PROJECT และ GOAL ก่อน',true);return}if(/^teambook$/i.test(data.project.trim())){toast('TeamBook แยกบ้านแล้ว · ไปออกคำสั่งที่ TeamBook House Command',true);window.open(TEAMBOOK_COMMAND,'_blank','noopener');return}const {response,data:j}=await request(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(response.status===401){lock('Session หมดอายุ · ใส่รหัสอีกครั้ง');return}if(!response.ok||!j.ok){toast('บันทึกไม่สำเร็จ: '+(j.error||response.status),true);return}await copyText(packetText(j.operation));toast(`สร้าง ${j.operation.id} แล้ว · packet ถูก copy`);clearForm();await loadBrief();if(openKeen)location.href='/keen/?op='+encodeURIComponent(j.operation.id)}
function clearForm(){['project','goal','nextAction','owner','source','output','success','guardrails'].forEach(id=>{const el=$(id);if(el)el.value=''})}
async function operationAction(action,payload){const {response,data}=await request(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});if(response.status===401){lock('Session หมดอายุ · ใส่รหัสอีกครั้ง');return null}if(!response.ok||!data.ok){toast(data.error||'อัปเดตไม่สำเร็จ',true);return null}await loadBrief();return data}
async function setFlow(id,flow){await operationAction('flow',{id,flow})}
async function deleteOperation(id,project){if(!confirm(`ลบ Operation ของ ${project} ทิ้งถาวร?\n\nใช้ตอนกดซ้ำหรือ Task นี้ไม่เอาแล้ว`))return;const result=await operationAction('delete',{id});if(result)toast(`ลบ ${id} แล้ว`)}
function coach(op){const missing=[];if(!op.nextAction)missing.push('Next Action');if(!op.source)missing.push('Source');if(!op.successCheck)missing.push('Success Check');if(!op.output)missing.push('Expected Output');const state=op.chainState||'ACTION';const guide={ACTION:'ลงมือกับ Next Action เพียงก้อนเดียว อย่าขยาย scope ระหว่าง resolve action',PASS:'หยุดแก้ของ เพิ่ม context ที่จำเป็น แล้วส่ง priority ให้คน/AI ถัดไปตรวจ',GO_AGAIN:'งานย่อย resolve แล้ว แต่ Goal ยังไม่จบ กำหนด Next Action ใหม่ก่อนเล่นต่อ',CLOSE_CHAIN:'ปิดได้เมื่อ Success Check ผ่านจริงและ output อยู่ในที่ที่คนถัดไปหาเจอ',BLOCK:'ระบุ blocker ให้ชัดว่า “รออะไร/ใคร” ก่อนส่งกลับเข้า chain'};return `<b>${esc(state)}</b> — ${guide[state]||guide.ACTION}${missing.length?`<br><br><b>Coach:</b> packet นี้ยังขาด ${missing.map(esc).join(', ')} · เติมก่อน PASS/CLOSE CHAIN จะลดงานย้อนกลับ`:''}`}
function renderOps(ops=[]){const box=$('ops');$('queueCount').textContent=`${ops.length} recent · ${brief?.operations?.open||0} open`;if(!ops.length){box.innerHTML='<div class="empty">ยังไม่มี Operation · ออกคำสั่งแรกได้จาก Dispatch Console</div>';return}box.innerHTML=ops.map(op=>`<article class="op"><div class="op-top"><div><span class="op-mode">${esc(op.mode)} · ${esc(op.status)}</span><h3>${esc(op.project)}</h3><p>${esc(op.goal)}</p></div><span class="op-id">${esc(op.id)}</span></div><div class="op-meta"><span class="chain-badge">${esc(op.chainState||'ACTION')}</span><span>${esc(op.owner||'unassigned')}</span><span>${esc(op.nextAction||'ยังไม่มี next action')}</span></div><div class="op-actions"><button class="btn small" data-copy="${esc(op.id)}">COPY</button><a class="btn small blue" href="/keen/?op=${encodeURIComponent(op.id)}">KEEN DESK</a><button class="btn small" data-flow="ACTION" data-id="${esc(op.id)}">ACTION</button><button class="btn small" data-flow="PASS" data-id="${esc(op.id)}">PASS</button><button class="btn small" data-flow="GO_AGAIN" data-id="${esc(op.id)}">GO AGAIN</button><button class="btn small" data-flow="CLOSE_CHAIN" data-id="${esc(op.id)}">CLOSE CHAIN</button><button class="btn small danger" data-delete="${esc(op.id)}" data-project="${esc(op.project)}">DELETE</button></div><details><summary>HOW TO PLAY THIS CHAIN · เปิดคำอธิบายให้คนทำงาน/คีน</summary><div class="coach">${coach(op)}</div></details></article>`).join('');box.querySelectorAll('[data-flow]').forEach(b=>b.onclick=()=>setFlow(b.dataset.id,b.dataset.flow));box.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteOperation(b.dataset.delete,b.dataset.project));box.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{const op=ops.find(x=>x.id===b.dataset.copy);if(op){await copyText(packetText(op));toast('copy Operation packet แล้ว')}})}
function polyline(values,width=900,height=210,pad=24,maxOverride=null){const max=maxOverride||Math.max(1,...values);return values.map((v,i)=>{const x=pad+(i*(width-pad*2))/Math.max(1,values.length-1);const y=height-pad-(Number(v||0)/max)*(height-pad*2);return[x,y]}).map(p=>p.join(',')).join(' ')}
function renderChart(key=chartKey){if(!brief?.charts)return;const chart=brief.charts[key]||brief.charts.operations;if(!chart)return;chartKey=key;document.querySelectorAll('.chart-tab').forEach(el=>el.classList.toggle('active',el.dataset.chart===key));$('chartTitle').textContent=chart.title;$('chartReason').textContent=chart.reason||'';const labels=chart.labels||[],primary=chart.primary||[],secondary=chart.secondary||[],max=Math.max(1,...primary,...secondary),width=900,height=210,pad=24;const grid=[.25,.5,.75,1].map(r=>{const y=height-pad-r*(height-pad*2);return `<line x1="${pad}" y1="${y}" x2="${width-pad}" y2="${y}"></line>`}).join('');const axes=labels.map((label,i)=>{const x=pad+(i*(width-pad*2))/Math.max(1,labels.length-1);return `<text x="${x}" y="204" text-anchor="middle" class="chart-axis">${esc(label.slice(5))}</text>`}).join('');const p1=polyline(primary,width,height,pad,max),p2=secondary.length?polyline(secondary,width,height,pad,max):'';$('focusChart').innerHTML=`<g class="chart-grid">${grid}</g>${p2?`<polyline points="${p2}" class="chart-line secondary"></polyline>`:''}<polyline points="${p1}" class="chart-line"></polyline>${primary.map((v,i)=>{const [x,y]=p1.split(' ')[i].split(',');return `<circle cx="${x}" cy="${y}" r="5" class="chart-dot"><title>${esc(labels[i])}: ${v} ${esc(chart.primaryLabel||'')}</title></circle>`}).join('')}${axes}`;$('chartSummary').innerHTML=`<span><strong>${esc(chart.primaryLabel||'Primary')}</strong> ${primary.reduce((a,b)=>a+Number(b||0),0)}</span>${secondary.length?`<span><strong>${esc(chart.secondaryLabel||'Secondary')}</strong> ${secondary.reduce((a,b)=>a+Number(b||0),0)}</span>`:''}<span>กราฟนี้อ่านเฉพาะบ้าน myClover · TeamBook มีกราฟของตัวเอง</span>`}
function renderChartTabs(){const box=$('chartTabs'),charts=brief?.charts||{};box.innerHTML=Object.entries(charts).map(([key,c])=>`<button class="chart-tab" data-chart="${esc(key)}">${esc(c.short||c.title)}</button>`).join('');box.querySelectorAll('[data-chart]').forEach(b=>b.onclick=()=>renderChart(b.dataset.chart));chartKey=brief?.attention?.chartKey&&charts[brief.attention.chartKey]?brief.attention.chartKey:Object.keys(charts)[0]||'operations';renderChart(chartKey)}
function renderAlerts(){const alerts=brief?.attention?.items||[];$('attentionCount').textContent=alerts.length;$('alerts').innerHTML=alerts.length?alerts.map(a=>`<article class="alert" data-level="${esc(a.level||'info')}"><strong>${esc(a.title)}</strong><p>${esc(a.detail)}</p>${a.advice?`<div class="advice">→ ${esc(a.advice)}</div>`:''}</article>`).join(''):'<article class="alert"><strong>ไม่มีสัญญาณวิกฤต</strong><p>บ้าน myClover ยังไม่มีเรื่องเร่งด่วนที่ควรแทรก chain ตอนนี้</p></article>'}
function renderMetrics(){const p=brief.population||{},l=brief.learning||{},o=brief.operations||{};const data=[['MYCLOVER ACCOUNTS',p.accounts,'ประชากรบ้านนี้'],['NEW ACCOUNTS 7D',p.newAccounts7d,'ผู้มาใหม่'],['FIRST CLASS',l.firstClassRegistrations,'ลงทะเบียน'],['GRANTED',l.firstClassGranted,'เปิดสิทธิ์แล้ว'],['OPEN CHAINS',o.open,'งานที่ยังเล่นอยู่'],['CLOSED 7D',o.closed7d,'งานที่ resolve แล้ว']];$('metrics').innerHTML=data.map(([a,b,c])=>`<article class="metric"><span>${esc(a)}</span><strong>${Number(b||0)}</strong><small>${esc(c)}</small></article>`).join('')}
function stateClass(state){const s=String(state||'').toLowerCase();if(['configured','runtime','connected','healthy','online','ready','active'].some(x=>s.includes(x)))return'ok';if(['missing','error','down','critical'].some(x=>s.includes(x)))return'bad';return'warn'}
function renderInfrastructure(){const list=brief.infrastructure||[];$('serviceStack').innerHTML=list.map(s=>`<a class="service" href="${esc(s.url||'#')}" target="_blank" rel="noopener"><div><div class="service-head"><b>${esc(s.name)}</b><span class="chip ${stateClass(s.state)}">${esc(s.state)}</span></div><p>${esc(s.role||'')}</p></div><p>${esc(s.lastEvent||'')}<br><span style="color:#7f8a99">checked ${esc(fmtDate(s.lastCheckedAt))}</span></p></a>`).join('')}
function renderBuildings(){const list=brief.buildings||[];$('cityGrid').innerHTML=list.map((b,i)=>`<article class="building"><div class="building-top"><div class="icon">${esc(b.icon||String(i+1).padStart(2,'0'))}</div><span class="chip ${stateClass(b.state)}">${esc(b.state)}</span></div><h3>${esc(b.name)}</h3><p>${esc(b.role||'')}</p><div class="building-meta"><span>LAST UPDATE · ${esc(fmtDate(b.lastUpdatedAt))}</span><span>${esc(b.lastEvent||'ไม่มี event ล่าสุด')}</span></div>${b.recommendation?`<div class="recommend"><b>ADVICE</b> · ${esc(b.recommendation)}</div>`:''}${b.url?`<a class="btn small" style="margin-top:10px" href="${esc(b.url)}" target="_blank" rel="noopener">OPEN HOUSE COMMAND ↗</a>`:''}</article>`).join('')}
function renderAchievements(){const list=brief.achievements||[];$('achievements').innerHTML=list.map(a=>`<article class="achievement"><div class="medal">${esc(a.icon||'🏅')}</div><strong>${esc(a.title)}</strong><p><b>${esc(a.value)}</b> · ${esc(a.detail)}</p></article>`).join('')}
function renderBriefCards(){const p=brief.population||{},o=brief.operations||{},l=brief.learning||{};$('changeTitle').textContent=brief.lastChange?.title||'กำลังอ่าน GitHub';$('changeText').textContent=brief.lastChange?.detail||'source history';const debt=(o.blocked||0)+(o.stale||0);$('healthTitle').textContent=debt?`${debt} chain ต้อง attention`:'Command chain ปกติ';$('healthText').textContent=debt?`${o.blocked||0} blocked · ${o.stale||0} stale`:'TeamBook health แยกดูที่บ้าน TeamBook';$('populationTitle').textContent=`${p.accounts||0} myClover accounts`;$('populationText').textContent=`${l.firstClassGranted||0} First Class granted · TeamBook ไม่รวมในตัวเลขนี้`;const open=o.open||0;$('focusTitle').textContent=open?`${open} Operation ยังเปิด`:'Chain ว่าง';const active=(o.recent||[]).find(x=>!['LIVE','ARCHIVED'].includes(x.status));$('focusText').textContent=active?`${active.project} · ${active.chainState||'ACTION'} · ${active.nextAction||active.goal}`:'พร้อมออกคำสั่งใหม่เมื่อมีงานที่ควรทำจริง'}
async function loadGithub(){try{const {response,data}=await request('https://api.github.com/repos/TeemClover/Teem/commits?per_page=1',{headers:{Accept:'application/vnd.github+json'}});if(!response.ok||!Array.isArray(data)||!data[0])return;const c=data[0];brief.lastChange={title:(c.commit?.message||'latest commit').split('\n')[0],detail:`${String(c.sha||'').slice(0,8)} · ${fmtDate(c.commit?.author?.date)}`};renderBriefCards()}catch{}}
function rewriteHouseLinks(){document.querySelectorAll('a[href^="/xty/"]').forEach(a=>{a.href=TEAMBOOK_COMMAND;a.target='_blank';a.rel='noopener';const b=a.querySelector('b');if(b)b.textContent='TeamBook House Command';const p=a.querySelector('p');if(p)p.textContent='TeamBook แยก server และ database · เข้าหลังบ้านจากบ้านของมันเอง'});const watch=document.querySelector('.attention-card .more-link');if(watch){watch.href=TEAMBOOK_COMMAND;watch.target='_blank';watch.rel='noopener';watch.textContent='ไป TeamBook House Command ↗'}}
function renderAll(){renderMetrics();renderBriefCards();renderAlerts();renderChartTabs();renderInfrastructure();renderBuildings();renderAchievements();renderOps(brief.operations?.recent||[]);rewriteHouseLinks();$('onlineText').textContent='MYCLOVER HOUSE ONLINE';loadGithub()}
async function loadBrief(){const {response,data}=await request(API);if(response.status===401){lock();return false}if(!response.ok||!data.ok){toast('Command API มีปัญหา: '+(data.error||response.status),true);$('onlineText').textContent='CONTROL PLANE DEGRADED';return false}brief=data;unlock();renderAll();return true}
function openChartsModal(){const charts=brief?.charts||{};$('modalBody').innerHTML=Object.entries(charts).map(([key,c])=>`<article class="building" style="min-height:140px"><div class="building-top"><div class="icon">↗</div><span class="chip ok">7D</span></div><h3>${esc(c.title)}</h3><p>${esc(c.reason||'')}</p><div class="building-meta"><span>${esc(c.primaryLabel)} TOTAL · ${(c.primary||[]).reduce((a,b)=>a+Number(b||0),0)}</span>${c.secondary?.length?`<span>${esc(c.secondaryLabel)} TOTAL · ${c.secondary.reduce((a,b)=>a+Number(b||0),0)}</span>`:''}</div><button class="btn small" style="margin-top:10px" data-open-chart="${esc(key)}">ดูบนกราฟหลัก</button></article>`).join('');$('modal').classList.add('show');$('modalBody').querySelectorAll('[data-open-chart]').forEach(b=>b.onclick=()=>{renderChart(b.dataset.openChart);$('modal').classList.remove('show');location.hash='#pulse'})}
async function boot(){rewriteHouseLinks();try{const {response,data}=await request(AUTH);if(response.ok&&data.authenticated){unlock();$('onlineText').textContent='LOADING MYCLOVER…';loadBrief();return}lock()}catch{lock('ตรวจ session ไม่สำเร็จ · ลองใส่รหัสอีกครั้ง')}}
function bind(){document.querySelectorAll('.mode').forEach(el=>{const pick=()=>{mode=el.dataset.mode;document.querySelectorAll('.mode').forEach(x=>x.classList.toggle('active',x===el))};el.onclick=pick;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();pick()}}});$('saveOperation').onclick=()=>saveOperation(false);$('saveKeen').onclick=()=>saveOperation(true);$('moreCharts').onclick=openChartsModal;$('modalClose').onclick=()=>$('modal').classList.remove('show');$('modal').onclick=e=>{if(e.target===$('modal'))$('modal').classList.remove('show')};$('logout').onclick=async()=>{await request(AUTH,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});location.reload()};$('gateForm').onsubmit=async e=>{e.preventDefault();$('gateMsg').textContent='กำลังตรวจรหัส…';const {response,data}=await request(AUTH,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'login',password:$('gatePassword').value})});if(response.ok&&data.authenticated){$('gateMsg').textContent='';$('gatePassword').value='';unlock();$('onlineText').textContent='LOADING MYCLOVER…';loadBrief()}else if(response.status===429)$('gateMsg').textContent='ลองรหัสถี่เกินไป รอสักครู่แล้วลองใหม่';else $('gateMsg').textContent='รหัสไม่ถูก'}}
bind();boot();