import {DatabaseSync} from 'node:sqlite';
import {createStore} from '../../api/_lib/mediral-commerce/store.js';
import {createHandler} from '../../api/_lib/mediral-commerce/handler.js';
import {hmac,BANK} from '../../api/_lib/mediral-commerce/domain.js';
export function adapter(db){const query=(text,params=[])=>db.prepare(text).all(Object.fromEntries(params.map((v,i)=>['$'+(i+1),v===undefined?null:v])));return {query:async(...a)=>query(...a),transaction:async fn=>{const parts=fn({query:(text,params=[])=>({text,params})});db.exec('BEGIN');try{const rows=parts.map(p=>query(p.text,p.params));db.exec('COMMIT');return rows;}catch(e){db.exec('ROLLBACK');throw e;}}};}
export async function fixture({sql,ai:injectedAI}={}){const db=sql?null:new DatabaseSync(':memory:');sql ||= adapter(db);await sql.query('CREATE TABLE mc_ai_source_registrations (reference TEXT,bank_transaction_id TEXT)');const store=createStore(sql);await store.ensure();let now=Date.parse('2026-10-01T10:00:00+07:00'),seq=0;const sent=[];const env={MEDIRAL_ADMIN_KEY:'test-only-admin-secret-32-characters',MEDIRAL_MODE:'live',MEDIRAL_LINE_SECRET:'test-line-secret',MEDIRAL_LINE_ACCESS_TOKEN:'test-token',MEDIRAL_LINE_BOT_ID:'U'+'a'.repeat(32),MEDIRAL_EASYSLIP_KEY:'test-slip',CRON_SECRET:'test-cron'};
const ai=injectedAI||{status:()=>({configured:false,enabled:false,model:'mock-disabled',dailyLimit:100}),respond:async()=>{throw Error('UNEXPECTED_AI_CALL');}};
const user='U'+'b'.repeat(32);const providers={image:async()=>({mime:'image/png',base64:'iVBORw0KGgo='}),verify:async(_,order)=>validSlip(order,now),send:async row=>{sent.push(row);return {ok:true};}};const handler=createHandler({store,providers,env,clock:()=>now,ai});let cookie='';
async function call(action,{method='GET',body,headers={}}={}){let output,code,hs={};const req={url:'/api/mediral-commerce?action='+action,method,headers:{host:'www.myclover.com',origin:'https://www.myclover.com',cookie,...headers},body:body===undefined?Buffer.from('{}'):Buffer.isBuffer(body)?body:Buffer.from(JSON.stringify(body))};const res={setHeader:(k,v)=>hs[k.toLowerCase()]=v,set statusCode(v){code=v;},end(v){output=Buffer.isBuffer(v)?v:JSON.parse(v);}};await handler(req,res);return {code,body:output,headers:hs};}
async function login(){const r=await call('login',{method:'POST',body:{key:env.MEDIRAL_ADMIN_KEY}});cookie=r.headers['set-cookie']?.split(';')[0]||'';return r;}
async function event(text,{image,id,userId=user,type='message'}={}){now+=1000;const e={type,timestamp:now,webhookEventId:id||'event-'+(++seq).toString().padStart(8,'0'),source:{type:'user',userId},replyToken:'reply-'+seq,message:image?{type:'image',id:image}:{type:'text',text}};const bytes=Buffer.from(JSON.stringify({destination:env.MEDIRAL_LINE_BOT_ID,events:[e]}));const result=await call('webhook',{method:'POST',body:bytes,headers:{'x-line-signature':hmac(bytes,env.MEDIRAL_LINE_SECRET)}});return {...result,event:e};}
async function checkout(){for(const text of ['ชุด 5 ชิ้น','ยืนยันสินค้า','ยินยอมทำรายการ','ผู้รับ ทดสอบ','0812345678','99 ถนนตัวอย่าง แขวงตัวอย่าง เขตตัวอย่าง กรุงเทพ 10100','ส่งรายการให้ร้าน']){const r=await event(text);if(r.code!==200)throw Error(JSON.stringify(r));}return (await store.list()).orders[0];}
return {db,store,env,providers,ai,sent,user,call,login,event,checkout,now:()=>now,advance:n=>now+=n};}
export function validSlip(order,now){return {success:true,data:{isDuplicate:false,matchedAccount:{bank:{code:BANK.code},bankNumber:BANK.number},amountInSlip:order.total/100,isAmountMatched:true,rawSlip:{transRef:'TEST-BANK-12345678',date:new Date(now).toISOString(),countryCode:'TH',amount:{amount:order.total/100,local:{currency:'THB',amount:order.total/100}},receiver:{bank:{id:BANK.code}}}}};}
