import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture} from './fixture.mjs';
import {webPrice} from '../../api/_lib/mediral-commerce/web-checkout.js';
const body={items:{CL:1,AC:1},name:'ผู้รับ ทดสอบ',phone:'0812345678',address:'99 ถนนตัวอย่าง แขวงตัวอย่าง กรุงเทพ 10100',consent:true,total:1};
async function shop(){const f=await fixture();f.env.MEDIRAL_LINE_SECRET='test-server-secret-at-least-32-characters';f.advance(86400000);const s=await f.call('shop-session',{method:'POST'});assert.equal(s.code,200);const cookie=s.headers['set-cookie'].split(';')[0];const call=(a,b={})=>f.call('shop-'+a,{method:'POST',body:b,headers:{cookie}});return {...f,shop:call};}
test('server coupon boundaries and invalid quantities',()=>{assert.equal(webPrice({CL:1},Date.parse('2026-10-15T23:59:59+07:00')).subtotal,40000);assert.equal(webPrice({CL:1},Date.parse('2026-10-16T00:00:00+07:00')).subtotal,50000);for(const items of [{},{CL:-1},{CL:1.5},{BAD:1},{CL:6}])assert.throws(()=>webPrice(items,Date.now()));});
test('web checkout immediately quotes shipping, retries create one order and never pushes to LINE',async()=>{const f=await shop();const first=await f.shop('create',body);assert.equal(first.code,200);assert.equal(first.body.order.subtotal,80000);assert.ok(first.body.order.bank.number);assert.equal(first.body.order.status,'awaiting_payment');assert.equal((await f.shop('create',body)).body.order.id,first.body.order.id);assert.equal((await f.store.list()).orders.length,1);assert.equal(first.body.order.address,undefined);await f.login();const q=await f.call('update',{method:'POST',body:{id:first.body.order.id,command:'quote',stockConfirmed:true,prices:{CL:1,AC:1},shipping:40}});assert.equal(q.code,409);const status=(await f.shop('status')).body.order;assert.equal(status.total,85000);assert.ok(status.bank.number);assert.equal(f.sent.length,0);assert.equal((await f.shop('slip',{image:Buffer.from('<svg/>').toString('base64')})).code,400);assert.equal((await f.shop('slip',{image:'iVBORw0KGgo='})).body.order.status,'payment_review');assert.equal((await f.shop('status')).body.order.bank,null);assert.equal(f.sent.length,0);});
test('origin, session, consent and cross-browser isolation',async()=>{const f=await shop();assert.equal((await f.call('shop-create',{method:'POST',body})).code,401);assert.equal((await f.call('shop-session',{method:'POST',headers:{origin:'https://evil.test'}})).code,403);assert.equal((await f.shop('create',{...body,consent:false})).code,400);await f.shop('create',body);const s=await f.call('shop-session',{method:'POST'});const r=await f.call('shop-status',{method:'POST',headers:{cookie:s.headers['set-cookie'].split(';')[0]}});assert.equal(r.body.order,null);});
test('quoted campaign deadline, expired bank visibility and new-order gate',async()=>{const f=await shop();const first=(await f.shop('create',body)).body.order;assert.equal((await f.shop('new')).code,409);await f.login();assert.equal((await f.call('update',{method:'POST',body:{id:first.id,command:'quote',stockConfirmed:true,shipping:0}})).code,409);f.advance(25*3600000);const expired=(await f.shop('status')).body.order;assert.equal(expired.status,'quote_expired');assert.equal(expired.bank,null);await f.login();await f.call('update',{method:'POST',body:{id:first.id,command:'cancel'}});assert.equal((await f.shop('new')).body.order,null);assert.notEqual((await f.shop('create',body)).body.order.id,first.id);});
test('web coupon ends at Bangkok midnight after two following days and refresh never extends it',async()=>{const {webCouponDeadline}=await import('../../api/_lib/mediral-commerce/web-checkout.js');for(const time of ['2026-10-02T00:00:00+07:00','2026-10-02T15:30:00+07:00','2026-10-02T23:59:59+07:00']){const start=Date.parse(time),end=webCouponDeadline(start);assert.equal(end,Date.parse('2026-10-05T00:00:00+07:00'));assert.ok(end-start>48*3600000&&end-start<=72*3600000);}const f=await shop();const a=await f.shop('session');f.advance(3600000);const b=await f.shop('session');assert.equal(a.body.couponExpiresAt,b.body.couponExpiresAt);f.advance(4*86400000);assert.equal((await f.shop('session')).body.discountPercent,0);assert.equal((await f.shop('create',body)).body.order.subtotal,100000);});
test('shipping is 50 through 1500 and free only above the discounted threshold',async()=>{const {shippingFor}=await import('../../mediral/checkout/shipping.js');assert.equal(shippingFor(150000),5000);assert.equal(shippingFor(150001),0);assert.equal(shippingFor(0),0);const one=await shop();assert.equal((await one.shop('create',{...body,items:{CL:1},shipping:0,total:1})).body.order.total,45000);const below=await shop();assert.equal((await below.shop('create',{...body,items:{CL:3}})).body.order.total,125000);const over=await shop();const o=(await over.shop('create',{...body,items:{CL:4}})).body.order;assert.equal(o.shipping,0);assert.equal(o.total,160000);assert.ok(o.bank.number);});
test('an older unquoted web order becomes payable when customer returns',async()=>{const f=await shop();const made=(await f.shop('create',body)).body.order;const stored=await f.store.order(made.id);const c=await f.store.claim(stored.userId,f.now());stored.status='awaiting_quote';delete stored.shipping;delete stored.total;delete stored.quotedAt;delete stored.expiresAt;await f.store.commit(c,{state:c.state,order:stored},f.now());const refreshed=(await f.shop('status')).body.order;assert.equal(refreshed.status,'awaiting_payment');assert.equal(refreshed.total,85000);assert.ok(refreshed.bank.number);});
