// Generated by tools/build-ako-recipes.mjs; edit recipes.js instead.
export const RECIPE_LINKS = Object.freeze([
  {
    "id": "tomato-lime",
    "path": "/ako/kitchen/tomato-lime/",
    "name": "มะเขือเทศฉ่ำ · มะนาวสด",
    "minutes": 5,
    "category": "salad"
  },
  {
    "id": "tomato-sesame",
    "path": "/ako/kitchen/tomato-sesame/",
    "name": "มะเขือเทศแตงกวา · งาคั่ว",
    "minutes": 7,
    "category": "salad"
  },
  {
    "id": "egg-crunch",
    "path": "/ako/kitchen/egg-crunch/",
    "name": "สลัดไข่ต้ม · โยเกิร์ตมัสตาร์ด",
    "minutes": 15,
    "category": "salad"
  },
  {
    "id": "tofu-rice",
    "path": "/ako/kitchen/tofu-rice/",
    "name": "ข้าวเต้าหู้เห็ด · ซีอิ๊วมะนาว",
    "minutes": 20,
    "category": "meal"
  },
  {
    "id": "yogurt-mustard",
    "path": "/ako/kitchen/yogurt-mustard/",
    "name": "โยเกิร์ตมัสตาร์ด · คนแล้วจบ",
    "minutes": 3,
    "category": "dressing"
  },
  {
    "id": "soy-lime",
    "path": "/ako/kitchen/soy-lime/",
    "name": "ซีอิ๊วมะนาว · เบาและสด",
    "minutes": 3,
    "category": "dressing"
  },
  {
    "id": "peanut-lime",
    "path": "/ako/kitchen/peanut-lime/",
    "name": "ถั่วลิสงมะนาว · ข้นนัว",
    "minutes": 5,
    "category": "dressing"
  },
  {
    "id": "ginger-chicken-cabbage",
    "path": "/ako/kitchen/ginger-chicken-cabbage/",
    "name": "ไก่ขิงกะหล่ำปลี · กระทะเดียว",
    "minutes": 20,
    "category": "meal"
  },
  {
    "id": "chicken-egg-bowl",
    "path": "/ako/kitchen/chicken-egg-bowl/",
    "name": "ข้าวไก่ไข่ · ชามอุ่นแบบญี่ปุ่น",
    "minutes": 20,
    "category": "meal"
  },
  {
    "id": "tofu-mushroom-pan",
    "path": "/ako/kitchen/tofu-mushroom-pan/",
    "name": "เต้าหู้จี่ · เห็ดซอสหอม",
    "minutes": 20,
    "category": "meal"
  },
  {
    "id": "cabbage-egg-pan",
    "path": "/ako/kitchen/cabbage-egg-pan/",
    "name": "แพนเค้กกะหล่ำปลี · ไข่หอม",
    "minutes": 20,
    "category": "meal"
  },
  {
    "id": "cucumber-sesame-vinegar",
    "path": "/ako/kitchen/cucumber-sesame-vinegar/",
    "name": "แตงกวางาคั่ว · เปรี้ยวใส",
    "minutes": 7,
    "category": "salad"
  },
  {
    "id": "mushroom-egg-soup",
    "path": "/ako/kitchen/mushroom-egg-soup/",
    "name": "ซุปเห็ดไข่ริ้ว · ชามเบา ๆ",
    "minutes": 15,
    "category": "meal"
  },
  {
    "id": "carrot-tuna-pan",
    "path": "/ako/kitchen/carrot-tuna-pan/",
    "name": "แครอตทูน่า · ผัดหอมงา",
    "minutes": 10,
    "category": "meal"
  },
  {
    "id": "tofu-tomato-cool",
    "path": "/ako/kitchen/tofu-tomato-cool/",
    "name": "เต้าหู้เย็นมะเขือเทศ · ซีอิ๊วมะนาว",
    "minutes": 5,
    "category": "salad"
  }
]);
