/** Actual local browser -> shared Meet/SQLite -> separate D1 outcomes -> protected Stat. */
import assert from 'node:assert/strict';
import {mkdir,writeFile,mkdtemp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {pathToFileURL} from 'node:url';
import {startPreview} from '../../core7/tests/frontdoor-preview.mjs';
const {chromium}=await import(pathToFileURL(process.env.FRONTDOOR_PLAYWRIGHT).href);
const output=process.env.FRONTDOOR_PROOF_DIR||await mkdtemp(tmpdir()+'/frontdoor-complete-');await mkdir(output,{recursive:true});
const server=await startPreview({port:0}),db=await server.mf.getD1Database('DB');
const browser=await chromium.launch({executablePath:process.env.FRONTDOOR_CHROME,headless:true});
const report={checks:[],errors:[],screenshots:[],base:server.base};
const pass=s=>{report.checks.push(s);console.log('PASS '+s);};
async function surface(width=1440){const context=await browser.newContext({viewport:{width,height:width<700?844:900},reducedMotion:'reduce',timezoneId:'Asia/Bangkok'});await context.route('**/*',r=>r.request().url().startsWith(server.base)||/^https:\/\/fonts\./.test(r.request().url())||/^(blob|data):/.test(r.request().url())?r.continue():r.abort());const page=await context.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>report.errors.push(e.message));return {context,page};}
async function shot(p,name){await p.screenshot({path:`${output}/${name}.png`});report.screenshots.push(name+'.png');}
async function begin(p){await p.goto(server.base+'/frontdoor/');await p.locator('#pickup').click();await p.locator('#continue-discovery').click();}
async function choose(p,color){await p.locator(`[data-answer=${color}]`).click();await p.waitForFunction(()=>!document.body.classList.contains('path-assembling'));await p.locator('#cross-seed').click();await p.locator('#seed-reward > section').waitFor({state:'visible'});await p.waitForFunction(()=>!document.body.classList.contains('path-assembling'));}
async function save(p){await p.locator('#save-path').click();await p.getByText('เก็บไว้แล้วบนเครื่องนี้',{exact:true}).waitFor();}
async function network(p){await p.getByRole('button',{name:'หาโอกาสต่อยอด',exact:true}).click();await p.getByRole('button',{name:'โปรเจกต์ที่เริ่มแล้ว',exact:true}).click();await p.getByRole('button',{name:'คนร่วมทำ',exact:true}).click();}
async function book(p){await p.locator('#booking-root').waitFor({state:'visible'});await p.getByRole('button',{name:/^ออนไลน์/}).click();await p.getByRole('button',{name:/^วันไหนก็ได้/}).click();await p.getByRole('button',{name:/^เวลาไหนก็ได้/}).click();await p.locator('#session-name').fill('Local journey fixture');await p.locator('#session-contact').fill('journey@example.test');await p.locator('#booking-next').click();await p.getByRole('checkbox').check();const waiting=p.waitForResponse(r=>r.url()===server.base+'/api/meet'&&r.request().method()==='POST');await p.locator('#booking-next').click();const response=await waiting;assert.equal(response.status(),201);await p.getByRole('heading',{name:'บันทึกคำขอทดลองแล้ว 🍀',exact:true}).waitFor();return response.json();}
async function eventually(fn){for(let i=0;i<50;i++){if(await fn())return;await new Promise(r=>setTimeout(r,150));}throw Error('Expected persisted outcome did not arrive');}
try{
 const {context,page:p}=await surface();await begin(p);await choose(p,'silver');await p.locator('[data-collection=garden]').click();await p.getByRole('button',{name:'ให้ภาพนำ',exact:true}).click();await p.locator('.seed-craft-edit summary').click();await p.getByLabel('ชื่อบนหน้าเว็บ',{exact:true}).fill('บ้านเล็กของฉัน');await p.getByRole('button',{name:'ใช้ชื่อนี้',exact:true}).click();await save(p);
 await p.locator('#open-path').click();await p.getByText('อยากดูข้างใน? เปิดโค้ดของเว็บนี้',{exact:true}).click();await p.locator('#compass-craft-code').waitFor();const source='<!doctype html><html lang="th"><body><h1>งานที่ฉันเก็บและกลับมาต่อจริง</h1></body></html>';await p.locator('#compass-craft-code').fill(source);await p.getByRole('button',{name:'เก็บเว็บชิ้นนี้',exact:true}).click();await p.locator('.craft-status[data-state=saved]').waitFor();
 await p.goto(server.base+'/frontdoor/');await p.locator('[data-answer=resume]').click();await p.locator('#rebuild-path').click();await choose(p,'blue');await network(p);await save(p);await shot(p,'network-world-desktop');
 await p.locator('#keepsake-toggle').click();assert.equal(await p.locator('[data-keepsake]').count(),2);await shot(p,'keepsakes-desktop');await p.locator('[data-keepsake=silver]').click();await p.locator('[data-answer=resume]').click();await p.locator('#open-path').click();await p.locator('#compass-craft-code').waitFor();assert.equal(await p.locator('#compass-craft-code').inputValue(),source);await shot(p,'keepsake-actual-edited-work');pass('Saved discoveries in two colors reopen; continuing an old craft forks its exact edited HTML and preserves the original');
 await p.goto(server.base+'/frontdoor/');await p.locator('#keepsake-toggle').click();await p.locator('[data-keepsake=blue]').click();await p.locator('[data-answer=resume]').click();await p.locator('#open-path').click();const hid=new URL(p.url()).searchParams.get('fdh');assert.ok(hid);const receipt=await book(p);assert.equal(server.meet.sqlite.prepare('SELECT intent FROM mc_meet_bookings WHERE reference=?').get(receipt.reference).intent,'opportunity');await eventually(async()=>!!await db.prepare("SELECT 1 FROM fd_v2_outcomes WHERE handoff_id=? AND name='MEET_REQUEST_ACCEPTED'").bind(hid).first());await shot(p,'network-local-receipt');pass('Actual Compass network plan -> contextual Meet -> successful SQLite request -> correlated local D1 receipt');
 await context.close();
 const mobile=await surface(390),m=mobile.page;await begin(m);await choose(m,'green');await m.getByRole('button',{name:'การขยับ',exact:true}).click();await m.getByRole('button',{name:'หลังจบงานชิ้นถัดไป',exact:true}).click();await save(m);await shot(m,'green-rhythm-mobile');await m.setViewportSize({width:1440,height:900});await m.locator('#seed-exhibit .seed-reward-rhythm').waitFor({state:'visible'});await shot(m,'green-rhythm-world');await m.setViewportSize({width:390,height:844});await m.locator('#seed-reward .seed-reward-rhythm').waitFor({state:'visible'});await m.locator('#open-path').click();const healthHid=new URL(m.url()).searchParams.get('fdh');
 await m.locator('[data-sleep=middle]').click();await m.locator('#shutter').click();await m.locator('[data-move=some]').click();await m.locator('#expand-days').click();await m.locator('[data-context=work]').click();await m.locator('#see-yours').click();await m.locator('#book-link').click();assert.equal(new URL(m.url()).searchParams.get('fdh'),healthHid);const healthReceipt=await book(m);assert.equal(server.meet.sqlite.prepare('SELECT intent FROM mc_meet_bookings WHERE reference=?').get(healthReceipt.reference).intent,'health');await eventually(async()=>!!await db.prepare("SELECT 1 FROM fd_v2_outcomes WHERE handoff_id=? AND name='MEET_REQUEST_ACCEPTED'").bind(healthHid).first());pass('Mobile personal rhythm -> actual V3 six-action experience -> scoped health request, with same opaque handoff across both rooms');await mobile.context.close();
 const review=await browser.newContext({viewport:{width:390,height:844},httpCredentials:{username:'teem',password:'local-fixture-only'}}),sp=await review.newPage();await sp.goto(server.base+'/stat/frontdoor/');await sp.locator('#dashboard').waitFor({state:'visible'});assert.match(await sp.locator('#outcome-rows').innerText(),/meet/);const rows=(await db.prepare('SELECT name,COUNT(*) count FROM fd_v2_outcomes GROUP BY name').all()).results;assert.equal(rows.find(r=>r.name==='MEET_REQUEST_ACCEPTED').count,2);report.outcomes=rows;report.productionRows=(await db.prepare("SELECT COUNT(*) n FROM fd_v2_outcomes WHERE env='prod'").first()).n;assert.equal(report.productionRows,0);await shot(sp,'stat-conversion-mobile');pass('Protected responsive Stat displays persisted destination/accepted-request outcomes; no prod rows or booking contact data in telemetry');await review.close();
 assert.deepEqual(report.errors,[]);
}finally{await writeFile(`${output}/proof.json`,JSON.stringify(report,null,2));await browser.close();await server.close();}
