import {products} from './products.js';
const $=s=>document.querySelector(s),notice=$('#notice'),form=$('#checkout');
const names={CL:'มูสล้างหน้า',AC:'เซรั่มขวดขาว',BR:'เซรั่มขวดเหลืองเขียว',SU:'เซรั่มกันแดด',PO:'แป้งพัฟ'};
const money=n=>(n/100).toLocaleString('th-TH')+' บาท';let catalog,activeOrder,busy=false,clockOffset=0;
async function api(action,body={}){const r=await fetch('/api/mediral-commerce?action=shop-'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),credentials:'same-origin'});let data;try{data=await r.json();}catch{throw Error('ยังเชื่อมต่อร้านไม่ได้ ลองอีกครั้ง หรือสั่งผ่าน LINE ได้เลย');}if(!r.ok)throw Error(({CHECK_CUSTOMER_DETAILS:'กรุณาตรวจชื่อ เบอร์โทร และที่อยู่ให้ครบ',INVALID_CART:'เลือกสินค้าอย่างน้อย 1 ชิ้น',INVALID_IMAGE:'ใช้ไฟล์ JPG หรือ PNG ขนาดไม่เกิน 3 MB',TRY_LATER:'มีรายการมากในขณะนี้ รอสักครู่แล้วลองอีกครั้ง',SHOP_NOT_READY:'ร้านบนเว็บยังไม่เปิดรับรายการ สั่งผ่าน LINE ได้เลย',SHOP_SESSION_REQUIRED:'หมดเวลาการเชื่อมต่อ กรุณาโหลดหน้าใหม่',CUSTOMER_BUSY:'กำลังบันทึกรายการ รอสักครู่แล้วลองอีกครั้ง'})[data.code]||'ยังทำรายการไม่สำเร็จ ลองอีกครั้ง หรือติดต่อเราใน LINE');return data;}
function cart(){return Object.fromEntries([...document.querySelectorAll('[data-sku]')].map(x=>[x.dataset.sku,Number(x.value)]).filter(([,n])=>n>0));}
function update(){if(!catalog)return;const active=Date.now()+clockOffset<catalog.couponExpiresAt&&catalog.discountPercent===20,count=Object.values(cart()).reduce((a,b)=>a+b,0),total=count*(active?40000:50000);const remaining=Math.max(0,Math.ceil((catalog.couponExpiresAt-Date.now()-clockOffset)/1000)),hours=Math.floor(remaining/3600),minutes=Math.floor(remaining%3600/60),seconds=remaining%60;$('#promotion').textContent=active?'ใช้คูปองลด 20% แล้ว':'คูปองหมดอายุแล้ว';$('#coupon-clock').textContent=active?`เหลือ ${String(hours).padStart(2,'0')} : ${String(minutes).padStart(2,'0')} : ${String(seconds).padStart(2,'0')}`:'ราคาปกติ 500 บาท / ชิ้น';$('#coupon-deadline').textContent=active?'ใช้ได้ถึง '+new Date(catalog.couponExpiresAt-1).toLocaleDateString('th-TH',{day:'numeric',month:'short',year:'numeric',timeZone:'Asia/Bangkok'})+' เวลา 23:59 น.':'';if($('#total').textContent!==money(total))$('#total').textContent=money(total);$('#regular-total').textContent=money(count*50000);$('#discount-total').textContent='−'+money(active?count*10000:0);$('#item-count').textContent=count+' ชิ้น';$('#mobile-count').textContent=count+' ชิ้น';$('#mobile-total').textContent=money(total);document.querySelectorAll('.product').forEach(row=>{const input=row.querySelector('[data-sku]');row.classList.toggle('selected',Number(input.value)>0);row.querySelector('.product-price').textContent=money(active?40000:50000);row.querySelector('del').hidden=!active;row.querySelector('[data-delta="-1"]').disabled=busy||Number(input.value)<=0;row.querySelector('[data-delta="1"]').disabled=busy||Number(input.value)>=5;});}
function show(o){activeOrder=o;if(!o){form.hidden=false;$('#order').hidden=true;return;}form.hidden=true;$('#order').hidden=false;$('#new-order').hidden=!['cancelled','shipped'].includes(o.status);$('#order-id').textContent=o.id;$('#order-items').replaceChildren(...Object.entries(o.items).map(([sku,n])=>{const li=document.createElement('li');li.textContent=names[sku]+' × '+n;return li;}));$('#order-state').textContent=({awaiting_quote:'รับรายการแล้ว กำลังเช็กของและค่าส่ง ยังไม่ต้องโอนเงิน',awaiting_payment:'ยอดพร้อมชำระแล้ว กรุณาตรวจยอดก่อนโอน',quote_expired:'ยอดนี้หมดเวลาชำระแล้ว กรุณาติดต่อ LINE เพื่อยืนยันยอดใหม่ก่อนโอน',payment_review:'ได้รับสลิปแล้ว กำลังตรวจยอดเงินเข้า ไม่ต้องโอนซ้ำ',paid:'รับชำระแล้ว ขอบคุณที่ให้เราดูแล',packing:'กำลังเตรียมจัดส่ง',shipped:'ส่งสินค้าแล้ว',cancelled:'รายการนี้ยกเลิกแล้ว'})[o.status]||'กำลังตรวจรายการ';$('#order-total').textContent='ค่าสินค้า '+money(o.subtotal)+(o.discount?' · ลดแล้ว '+money(o.discount):'');$('#shipping').textContent=o.shipping===null?'รอยืนยันค่าส่ง':'ค่าส่ง '+money(o.shipping)+' · ยอดรวม '+money(o.total);$('#bank').hidden=!o.bank;if(o.bank){$('#bank-info').textContent=o.bank.name+'\n'+o.bank.number+'\n'+o.bank.owner;$('#deadline').textContent='ชำระภายใน '+new Date(o.expiresAt).toLocaleString('th-TH',{timeZone:'Asia/Bangkok'});}$('#tracking').textContent=o.tracking?`${o.carrier} · เลขพัสดุ ${o.tracking}`:'';}
async function run(fn){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();notice.textContent='';}catch(e){notice.textContent=e.message;}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);update();}}
for(const [index,p]of products.entries()){
 const sku=p.id,name=names[sku],b=p.bounds,row=document.createElement('article');row.className='product';
 row.innerHTML=`<a class="product-art" href="../${sku.toLowerCase()}/" aria-label="ดูรายละเอียด ${name}"><span class="pack" style="aspect-ratio:${b.aspect}${sku==='PO'?';height:80px':''}"><img src="${p.image}" alt="${name} Mediral" style="width:${100/(b.x1-b.x0)}%;height:${100/(b.y1-b.y0)}%;left:${-100*b.x0/(b.x1-b.x0)}%;top:${-100*b.y0/(b.y1-b.y0)}%" loading="${index<2?'eager':'lazy'}"></span></a><div class="product-info"><p class="product-step">0${index+1} · ${p.step}</p><h3>${name}</h3><p class="product-description">${p.description}</p><a class="details" href="../${sku.toLowerCase()}/">รายละเอียดสินค้า ↗</a><div class="product-bottom"><div><strong class="product-price">500 บาท</strong><del hidden>500 บาท</del></div><div class="quantity"><button type="button" data-delta="-1" aria-label="ลดจำนวน ${name}">−</button><input id="qty-${sku}" type="number" min="0" max="5" step="1" value="0" data-sku="${sku}" aria-label="จำนวน ${name}" inputmode="numeric"><button type="button" data-delta="1" aria-label="เพิ่มจำนวน ${name}">＋</button></div></div></div>`;
 const input=row.querySelector('input');input.addEventListener('change',()=>{input.value=String(Math.max(0,Math.min(5,Math.trunc(Number(input.value)||0))));update();});input.addEventListener('input',()=>{if(input.validity.valid)update();});row.querySelectorAll('[data-delta]').forEach(button=>button.onclick=()=>{input.value=String(Math.max(0,Math.min(5,(Number(input.value)||0)+Number(button.dataset.delta))));update();});$('#products').append(row);
}
$('#continue').onclick=()=>{if(form.checkValidity()&&Object.keys(cart()).length){form.requestSubmit();return;}$('#delivery').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});$('#delivery input').focus({preventScroll:true});};
$('#set').onclick=()=>{document.querySelectorAll('[data-sku]').forEach(x=>x.value='1');update();};
form.onsubmit=e=>{e.preventDefault();run(async()=>{const d=new FormData(form);const r=await api('create',{items:cart(),name:d.get('name'),phone:d.get('phone'),address:d.get('address'),consent:d.get('consent')==='on'});show(r.order);form.reset();$('#order').scrollIntoView({behavior:'smooth'});});};
$('#refresh').onclick=()=>run(async()=>show((await api('status')).order));
$('#slip').onsubmit=e=>{e.preventDefault();run(async()=>{const file=e.target.receipt.files[0];if(!file||file.size>3*1024*1024||!['image/jpeg','image/png'].includes(file.type))throw Error('ใช้ JPG หรือ PNG ไม่เกิน 3 MB');const image=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result.split(',')[1]);r.onerror=reject;r.readAsDataURL(file);});show((await api('slip',{image})).order);e.target.reset();});};
run(async()=>{catalog=await api('session');clockOffset=(catalog.serverNow||Date.now())-Date.now();update();show((await api('status')).order);});
setInterval(()=>{if(catalog)update();},1000);

$('#new-order').onclick=()=>run(async()=>{show((await api('new')).order);update();});

form.addEventListener('input',()=>{$('#continue').textContent=form.checkValidity()?'ส่งคำสั่งซื้อ →':'กรอกที่อยู่ →';});
