const $=s=>document.querySelector(s),notice=$('#notice'),form=$('#checkout');
const names={CL:'มูสล้างหน้า',AC:'เซรั่มขวดขาว',BR:'เซรั่มขวดเหลืองเขียว',SU:'เซรั่มกันแดด',PO:'แป้งพัฟ'};
const money=n=>(n/100).toLocaleString('th-TH')+' บาท';let catalog,activeOrder,busy=false;
async function api(action,body={}){const r=await fetch('/api/mediral-commerce?action=shop-'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),credentials:'same-origin'});let data;try{data=await r.json();}catch{throw Error('ยังเชื่อมต่อร้านไม่ได้ ลองอีกครั้ง หรือสั่งผ่าน LINE ได้เลย');}if(!r.ok)throw Error(({CHECK_CUSTOMER_DETAILS:'กรุณาตรวจชื่อ เบอร์โทร และที่อยู่ให้ครบ',INVALID_CART:'เลือกสินค้าอย่างน้อย 1 ชิ้น',INVALID_IMAGE:'ใช้ไฟล์ JPG หรือ PNG ขนาดไม่เกิน 3 MB',TRY_LATER:'มีรายการมากในขณะนี้ รอสักครู่แล้วลองอีกครั้ง',SHOP_NOT_READY:'ร้านบนเว็บยังไม่เปิดรับรายการ สั่งผ่าน LINE ได้เลย',SHOP_SESSION_REQUIRED:'หมดเวลาการเชื่อมต่อ กรุณาโหลดหน้าใหม่',CUSTOMER_BUSY:'กำลังบันทึกรายการ รอสักครู่แล้วลองอีกครั้ง'})[data.code]||'ยังทำรายการไม่สำเร็จ ลองอีกครั้ง หรือติดต่อเราใน LINE');return data;}
function cart(){return Object.fromEntries([...document.querySelectorAll('[data-sku]')].map(x=>[x.dataset.sku,Number(x.value)]).filter(([,n])=>n>0));}
function update(){const active=Date.now()<catalog.couponExpiresAt&&catalog.discountPercent===20;$('#promotion').textContent=active?'ใช้คูปองลด 20% ให้อัตโนมัติ · 500 → 400 บาท/ชิ้น ถึง 15 ต.ค. 2569':'ชิ้นละ 500 บาท';$('#total').textContent=money(Object.values(cart()).reduce((a,b)=>a+b,0)*(active?40000:50000));}
function show(o){activeOrder=o;if(!o){form.hidden=false;$('#order').hidden=true;return;}form.hidden=true;$('#order').hidden=false;$('#new-order').hidden=!['cancelled','shipped'].includes(o.status);$('#order-id').textContent=o.id;$('#order-items').replaceChildren(...Object.entries(o.items).map(([sku,n])=>{const li=document.createElement('li');li.textContent=names[sku]+' × '+n;return li;}));$('#order-state').textContent=({awaiting_quote:'รับรายการแล้ว กำลังเช็กของและค่าส่ง ยังไม่ต้องโอนเงิน',awaiting_payment:'ยอดพร้อมชำระแล้ว กรุณาตรวจยอดก่อนโอน',quote_expired:'ยอดนี้หมดเวลาชำระแล้ว กรุณาติดต่อ LINE เพื่อยืนยันยอดใหม่ก่อนโอน',payment_review:'ได้รับสลิปแล้ว กำลังตรวจยอดเงินเข้า ไม่ต้องโอนซ้ำ',paid:'รับชำระแล้ว ขอบคุณที่ให้เราดูแล',packing:'กำลังเตรียมจัดส่ง',shipped:'ส่งสินค้าแล้ว',cancelled:'รายการนี้ยกเลิกแล้ว'})[o.status]||'กำลังตรวจรายการ';$('#order-total').textContent='ค่าสินค้า '+money(o.subtotal)+(o.discount?' · ลดแล้ว '+money(o.discount):'');$('#shipping').textContent=o.shipping===null?'รอยืนยันค่าส่ง':'ค่าส่ง '+money(o.shipping)+' · ยอดรวม '+money(o.total);$('#bank').hidden=!o.bank;if(o.bank){$('#bank-info').textContent=o.bank.name+'\n'+o.bank.number+'\n'+o.bank.owner;$('#deadline').textContent='ชำระภายใน '+new Date(o.expiresAt).toLocaleString('th-TH',{timeZone:'Asia/Bangkok'});}$('#tracking').textContent=o.tracking?`${o.carrier} · เลขพัสดุ ${o.tracking}`:'';}
async function run(fn){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();notice.textContent='';}catch(e){notice.textContent=e.message;}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
for(const [sku,name]of Object.entries(names)){const row=document.createElement('div');row.className='product';const label=document.createElement('label');label.htmlFor='qty-'+sku;label.textContent=name;const input=document.createElement('input');Object.assign(input,{id:'qty-'+sku,type:'number',min:'0',max:'5',value:'0'});input.dataset.sku=sku;input.setAttribute('aria-label','จำนวน '+name);input.addEventListener('input',update);row.append(label,input);$('#products').append(row);}
$('#set').onclick=()=>{document.querySelectorAll('[data-sku]').forEach(x=>x.value='1');update();};
form.onsubmit=e=>{e.preventDefault();run(async()=>{const d=new FormData(form);const r=await api('create',{items:cart(),name:d.get('name'),phone:d.get('phone'),address:d.get('address'),consent:d.get('consent')==='on'});show(r.order);form.reset();$('#order').scrollIntoView({behavior:'smooth'});});};
$('#refresh').onclick=()=>run(async()=>show((await api('status')).order));
$('#slip').onsubmit=e=>{e.preventDefault();run(async()=>{const file=e.target.receipt.files[0];if(!file||file.size>3*1024*1024||!['image/jpeg','image/png'].includes(file.type))throw Error('ใช้ JPG หรือ PNG ไม่เกิน 3 MB');const image=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result.split(',')[1]);r.onerror=reject;r.readAsDataURL(file);});show((await api('slip',{image})).order);e.target.reset();});};
run(async()=>{catalog=await api('session');update();show((await api('status')).order);});
setInterval(()=>{if(catalog)update();},30000);

$('#new-order').onclick=()=>run(async()=>{show((await api('new')).order);update();});
