import {demo} from './demo.js';
let configPromise;
export async function config(){return configPromise ||= fetch('/api/torntor?action=config').then(r=>{if(!r.ok)throw Error('service');return r.json()}).catch(()=>({mode:'unavailable',auth:null,payments:false}));}
export function token(){try{return sessionStorage.getItem('torntor:access')||''}catch{return ''}}
export async function api(action,data,method=data?'POST':'GET'){const response=await fetch(`/api/torntor?action=${encodeURIComponent(action)}`,{method,headers:{'Content-Type':'application/json',...(token()?{Authorization:`Bearer ${token()}`}:{})},...(data?{body:JSON.stringify(data)}:{})});const value=await response.json();if(!response.ok)throw Error(value.error||'เชื่อมต่อไม่สำเร็จ');return value;}
export async function call(action,...args){const c=await config();if(c.mode==='unavailable')throw Error('เชื่อมต่อระบบไม่ได้ ลองใหม่อีกครั้ง');if(c.mode==='demo')return demo[action](...args);const payload={wallet:null,daily:{},unlock:{story:args[0],episode:args[1]},order:{pack:args[0],method:args[1],token:args[2]},works:null,stats:null,view:args[0],moderate:{id:args[0],decision:args[1],note:args[2]}}[action];const value=await api(action,payload);return action==='works'?value.works:value;}
export async function signIn(email,password){const c=await config();if(!c.auth)throw Error('ระบบบัญชียังไม่ได้เชื่อมต่อ');const response=await fetch(`${c.auth.url}/auth/v1/token?grant_type=password`,{method:'POST',headers:{'Content-Type':'application/json',apikey:c.auth.key},body:JSON.stringify({email,password})});const data=await response.json();if(!response.ok)throw Error('อีเมลหรือรหัสผ่านไม่ถูกต้อง');sessionStorage.setItem('torntor:access',data.access_token);}
export async function submit(data,cover,files){const c=await config();if(c.mode==='demo')return demo.submit(data,cover,files);const assets=[];for(const [index,file] of [cover,...files].entries()){const intent=await api('upload',{type:file.type,size:file.size,format:data.format,role:index?'page':'cover'});const res=await fetch(intent.url,{method:'PUT',headers:{'Content-Type':file.type},body:file});if(!res.ok)throw Error('อัปโหลดไม่สำเร็จ');assets.push(intent.id);}return api('submit',{...data,assets});}
export async function asset(file){const c=await config();if(c.mode==='demo')return demo.asset(file);const r=await api('asset',{id:file.id});return r.url;}
