import {stories} from '../library.js';
import {bangkokDay,validateFile,validateSubmission,packs,methods,qualifiedView,episodeCost} from './rules.js';
const key='torntor:platform:demo:v1', oldKey='tontor:prototype:v1';
const empty=()=>({works:[],events:[],orders:[],spends:[],daily:[],free:0,paid:0,unlocked:[]});
function read(){try{return {...empty(),...JSON.parse(localStorage.getItem(key)||'{}')}}catch{return empty()}}
async function locked(fn){if(navigator.locks)return navigator.locks.request(key,()=>fn());return fn();}
function write(db){localStorage.setItem(key,JSON.stringify(db));window.dispatchEvent(new Event('torntor:update'));}
function legacy(){try{return JSON.parse(localStorage.getItem(oldKey)||'{}')}catch{return {}}}
function synchronize(db){const old=legacy();old.balance=db.free+db.paid;old.unlocked=[...new Set([...(old.unlocked||[]),...db.unlocked])];localStorage.setItem(oldKey,JSON.stringify(old));}
function wallet(db){return {balance:db.free+db.paid,free:db.free,paid:db.paid,unlocked:db.unlocked,claimed:db.daily.includes(bangkokDay()),mode:'demo'};}
function filesDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open('torntor-demo-media',1);req.onupgradeneeded=()=>req.result.createObjectStore('files');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(Error('อุปกรณ์นี้ไม่รองรับการเก็บไฟล์ทดลอง'));});}
async function media(op,id,value){const db=await filesDB();return new Promise((resolve,reject)=>{const tx=db.transaction('files',op==='get'?'readonly':'readwrite');const req=op==='get'?tx.objectStore('files').get(id):tx.objectStore('files').put(value,id);tx.oncomplete=()=>{resolve(req.result);db.close()};tx.onerror=()=>{reject(Error('เก็บไฟล์ไม่สำเร็จ พื้นที่อาจไม่พอ'));db.close()};});}
export const demo={
  async wallet(){return locked(()=>{const db=read();if(!db.migrated){db.free=Math.max(0,Number(legacy().balance??120));db.unlocked=legacy().unlocked||[];db.migrated=true;write(db);}return wallet(db)})},
  async daily(){return locked(()=>{const db=read();const day=bangkokDay();if(!db.daily.includes(day)){db.daily.push(day);db.free+=20;synchronize(db);write(db);}return wallet(db)})},
  async unlock(story,episode,price=10){return locked(()=>{const db=read(),id=`${story}:${episode}`,catalog=stories.find(s=>s.id===story),work=db.works.find(w=>w.id===story&&w.episode===episode&&w.status==='published');if(!Number.isInteger(episode)||episode<1||(catalog?episode>catalog.episodes:!work))throw Error('ไม่พบตอนนี้');price=catalog?episodeCost(catalog,episode):work.price;if(!price)return wallet(db);if(!db.unlocked.includes(id)){if(db.free+db.paid<price)throw Error('เหรียญไม่พอ เติมเหรียญหรือรับเหรียญรายวัน');const free=Math.min(price,db.free),paid=price-free;db.free-=free;db.paid-=paid;db.unlocked.push(id);db.spends.push({story,episode,free,paid,at:Date.now()});synchronize(db);write(db);}return wallet(db)})},
  async order(pack,method){if(!methods.includes(method))throw Error('ช่องทางไม่ถูกต้อง');const p=packs.find(p=>p.id===pack);if(!p)throw Error('แพ็กไม่ถูกต้อง');return locked(()=>{const db=read(),order={...p,id:crypto.randomUUID(),pack:p.id,method,status:'pending',at:Date.now(),mode:'demo'};db.orders.push(order);write(db);return order})},
  async settle(id,status){return locked(()=>{const db=read(),order=db.orders.find(o=>o.id===id);if(!order)throw Error('ไม่พบรายการ');if(order.status==='pending'){order.status=status==='paid'?'paid':'failed';if(order.status==='paid')db.paid+=order.coins;synchronize(db);write(db);}return {...order,wallet:wallet(db)}})},
  async submit(input,cover,files){const data=validateSubmission(input);if(!cover||!files.length||files.length>100)throw Error('ใส่ปกและไฟล์เนื้อหา 1–100 ไฟล์');validateFile(cover,data.format,'cover');files.forEach(f=>validateFile(f,data.format));if(data.format!=='comic'&&files.length!==1)throw Error('วิดีโอและนิยายใช้ไฟล์เดียวต่อตอน');const id=crypto.randomUUID();await media('put',`${id}:cover`,cover);for(let i=0;i<files.length;i++)await media('put',`${id}:${i}`,files[i]);return locked(()=>{const db=read();const item={id,...data,status:'pending',note:'',owner:'demo-creator',revision:1,created:Date.now(),files:files.map((f,i)=>({id:`${id}:${i}`,name:f.name,type:f.type,size:f.size})),cover:{id:`${id}:cover`,type:cover.type,name:cover.name}};db.works.unshift(item);write(db);return item})},
  async moderate(id,decision,note){return locked(()=>{const db=read(),item=db.works.find(w=>w.id===id);if(!item||item.status!=='pending')throw Error('งานนี้ได้รับการตรวจแล้ว');if(!['published','rejected'].includes(decision))throw Error('ผลตรวจไม่ถูกต้อง');if(decision==='rejected'&&!note?.trim())throw Error('ใส่คำแนะนำให้ Creator');item.status=decision;item.note=String(note||'').slice(0,1000);item.reviewed=Date.now();write(db);return item})},
  async works(published=false){return read().works.filter(w=>!published||w.status==='published')},
  async asset(file){const blob=await media('get',file.id);if(!blob)throw Error('ไฟล์ทดลองหายจากอุปกรณ์');return URL.createObjectURL(blob)},
  async view(data){if(!data.session||!data.story||!Number.isInteger(data.episode))return;return locked(()=>{const db=read(),id=`${data.story}:${data.episode}:${data.session}`;let event=db.events.find(e=>e.id===id);if(!event){event={id,...data,seconds:0,complete:false,at:Date.now()};db.events.push(event)}event.seconds=Math.min(86400,Math.max(event.seconds,Number(data.seconds)||0));event.complete=event.complete||data.complete===true;write(db);})},
  async stats(){const db=read();return {events:db.events.filter(e=>qualifiedView(e.seconds,e.complete,e.format)),spends:db.spends,orders:db.orders,mode:'demo'}}
};
