import {config,call,submit,asset,signIn,token,api} from './client.js';
import {metrics} from './metrics.js';
import {html} from './rules.js';
import {stories} from '../library.js';
import {demo} from './demo.js';
const $=s=>document.querySelector(s),admin=document.body.dataset.portal==='admin',number=n=>Number(n||0).toLocaleString('th-TH'),money=n=>'฿'+Number(n||0).toLocaleString('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2});
let works=[],selected=null,filter='pending',report=null,c,urls=[];
let statsStory=new URLSearchParams(location.search).get('story')||'',tableRows=[];
function notify(message){(document.querySelector('dialog[open]')||document.body).append($('#status'));$('#status').textContent=message;clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#status').textContent='',5000)}
async function busy(button,fn){button.disabled=true;try{await fn()}catch(e){notify(e.message)}finally{button.disabled=false}}
function name(id){return stories.find(s=>s.id===id)?.title||works.find(w=>w.id===id)?.title||id}
function status(s){return {pending:'รอตรวจ',published:'เผยแพร่แล้ว',rejected:'ให้แก้ไข'}[s]||s}
async function renderWorks(){const list=admin?works.filter(w=>w.status===filter):works;$('#pending-count')&&($('#pending-count').textContent=works.filter(w=>w.status==='pending').length);$('#works').innerHTML=list.length?list.map(w=>`<article class="work"><img class="work-cover" data-cover="${html(w.id)}" alt=""><div class="copy"><strong>${html(w.title)}</strong><p>${html(w.team)} · ตอน ${w.episode} · ${w.price?'10 เหรียญ':'ฟรี'}</p><span class="badge ${html(w.status)}">${status(w.status)}</span>${w.note?`<p>${html(w.note)}</p>`:''}</div><button data-preview="${html(w.id)}">${admin&&w.status==='pending'?'ตรวจงาน':'ดูผลงาน'}</button></article>`).join(''):`<div class="empty"><span class="symbol">✦</span>${admin?'ไม่มีผลงานในคิวนี้':'เรื่องแรกของคุณเริ่มที่นี่'}<br><small>${admin?'งานใหม่จะเข้าคิวเมื่อ Creator ส่งให้ตรวจ':'ใส่ปก อัปโหลดตอน แล้วส่งให้ทีมตอนต่อ'}</small></div>`;for(const w of list){try{const url=await asset(w.cover);urls.push(url);const img=$(`[data-cover="${w.id}"]`);if(img)img.src=url}catch{}}}
function renderStats(data){report=metrics(data);const m=report;$('#metrics').innerHTML=[['ยอดชม',number(m.views),'จากการดู / อ่านจริง'],['เวลาที่อยู่กับเรื่อง',number(Math.round(m.seconds/60))+' นาที','รวมรายตอน'],['ปลดล็อกตอน',number(m.unlocks),'ซื้อ + เหรียญแจก'],[admin?'ยอดเติมสำเร็จ':'รายได้ประมาณการ',money(admin?m.gross:m.revenue),c.mode==='demo'?'รายการทดลอง ไม่ใช่รายได้จริง':'รอตรวจยอดก่อนจ่าย']].map(([label,value,note])=>`<div class="metric"><span>${label}</span><strong>${value}</strong><small>${note}</small></div>`).join('');$('#creator-income')&&($('#creator-income').textContent=money(m.revenue));$('#revenue')&&($('#revenue').innerHTML=[['ยอดเติมสำเร็จ',m.gross],['ค่าธรรมเนียม',m.fees],['คืนเงิน',m.refunds],['ยอดรับสุทธิ',m.net]].map(([label,value])=>`<div class="integration"><span>${label}</span><strong>${money(value)}</strong></div>`).join(''));renderEpisodeStats();$('#orders').innerHTML=(data.orders||[]).length?(data.orders||[]).slice().reverse().map(o=>`<tr><td>${new Date(o.at).toLocaleString('th-TH',{timeZone:'Asia/Bangkok'})}</td><td>${html(o.method)}</td><td>${money(o.amount/100)}</td><td>${number(o.coins)}</td><td>${html(o.status)} <small>${html(o.mode||'demo')}</small></td></tr>`).join(''):'<tr><td colspan="5" class="empty">ยังไม่มีรายการเติม</td></tr>'}
function chapterName(r){return stories.find(s=>s.id===r.story)?.episodeNames?.[r.episode-1]||works.find(w=>w.id===r.story&&w.episode===Number(r.episode))?.title||''}
function renderEpisodeStats(){
  const ids=new Set(report.rows.map(r=>r.story));
  // Built-in catalogue is visible to Admin only; Creator sees returned owned rows.
  if(admin)for(const s of stories)ids.add(s.id);
  for(const w of works)ids.add(w.id);
  const select=$('#stats-story');
  if(!ids.has(statsStory))statsStory='';
  select.innerHTML='<option value="">ทุกเรื่อง</option>'+[...ids].map(id=>`<option value="${html(id)}">${html(name(id))}</option>`).join('');
  select.value=statsStory;
  tableRows=report.rows.filter(r=>!statsStory||r.story===statsStory).map(r=>({...r}));
  const story=admin&&stories.find(s=>s.id===statsStory);
  if(story)for(let episode=1;episode<=story.episodes;episode++)if(!tableRows.some(r=>Number(r.episode)===episode))tableRows.push({story:story.id,episode,views:0,viewers:0,seconds:0,completes:0,unlocks:0,paid:0,free:0});
  tableRows.sort((a,b)=>statsStory?Number(a.episode)-Number(b.episode):b.views-a.views);
  const reading=story&&story.format!=='drama';
  $('#stats-views-label').textContent=reading?'ยอดอ่าน':'ยอดชม / อ่าน';
  $('#stats-viewers-label').textContent=reading?'ผู้อ่าน':'ผู้ชม / อ่าน';
  $('#stats-summary').textContent=statsStory?`${name(statsStory)} · ${tableRows.length} ตอน · ${number(tableRows.reduce((n,r)=>n+Number(r.views),0))} ${reading?'ครั้งที่อ่าน':'ครั้งที่ชม / อ่าน'}`:'เลือกเรื่องเพื่อดูเรียงตามตอน รวมตอนที่ยังไม่มียอด';
  $('#episode-stats').innerHTML=tableRows.length?tableRows.map(r=>`<tr data-stat-story="${html(r.story)}" data-stat-episode="${r.episode}"><td>${html(name(r.story))}<small class="chapter-name">ตอน ${r.episode}${chapterName(r)?' · '+html(chapterName(r)):''}</small></td><td>${number(r.views)}</td><td>${number(r.viewers)}</td><td>${r.views?Math.min(100,Math.round(r.completes/r.views*100)):0}%</td><td>${number((Number(r.seconds)/60).toFixed(1))}</td><td>${number(r.unlocks)}</td><td>${number(r.paid)}</td><td>${number(r.free)}</td></tr>`).join(''):'<tr><td colspan="8" class="empty">ยังไม่มียอดชม เริ่มอ่านหรือเล่นคลิปเพื่อทดสอบ</td></tr>';
}
$('#stats-story').addEventListener('change',e=>{if(!report)return;statsStory=e.target.value;const url=new URL(location.href);if(statsStory)url.searchParams.set('story',statsStory);else url.searchParams.delete('story');history.replaceState(null,'',url);renderEpisodeStats()});
async function refresh(){urls.forEach(u=>{if(u.startsWith('blob:'))URL.revokeObjectURL(u)});urls=[];works=await call('works');await renderWorks();let data=await call('stats');if(!admin&&c.mode==='demo'){const own=new Set(works.map(w=>w.id)),paid=data.orders.filter(o=>o.status==='paid'),coins=paid.reduce((n,o)=>n+o.coins,0);data={...data,pricing:{bahtPerCoin:coins?paid.reduce((n,o)=>n+o.amount/100,0)/coins:0},events:data.events.filter(e=>own.has(e.story)),spends:data.spends.filter(s=>own.has(s.story)),orders:[]}}renderStats(data);}
async function preview(id){selected=works.find(w=>w.id===id);if(!selected)return;$('#review-title').textContent=selected.title+' · ตอน '+selected.episode;$('#review-summary').textContent=selected.summary;$('#review-actions').hidden=!admin||selected.status!=='pending';$('#review-note').value='';$('#preview').textContent='กำลังโหลดเนื้อหา…';$('#review-dialog').showModal();let content='';for(const file of selected.files){const url=await asset(file);urls.push(url);if(selected.format==='drama')content+=`<video src="${html(url)}" controls playsinline preload="metadata"></video>`;else if(selected.format==='comic')content+=`<img src="${html(url)}" alt="หน้าการ์ตูน">`;else{const text=await fetch(url).then(r=>r.text());content+=`<pre>${html(text)}</pre>`}}$('#preview').innerHTML=content;}
$('#works').addEventListener('click',e=>{const b=e.target.closest('[data-preview]');if(b)busy(b,()=>preview(b.dataset.preview))});
$('#new-work')?.addEventListener('click',()=>$('#upload-dialog').showModal());
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$('#'+b.dataset.close).close()));$('#review-dialog').addEventListener('close',()=>{$('#preview').querySelector('video')?.pause()});
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderWorks()}));
$('#upload-form').elements.format.addEventListener('change',e=>{const f=e.target.value;$('#content-files').accept=f==='drama'?'video/mp4,video/webm':f==='comic'?'image/webp,image/jpeg,image/png':'text/plain';$('#content-files').multiple=f==='comic';$('#content-files').value='';$('#file-help').textContent=f==='drama'?'MP4 / WebM ไม่เกิน 250 MB · 1 ไฟล์ต่อตอน':f==='comic'?'WebP / JPG / PNG ไม่เกิน 10 MB ต่อภาพ · เรียงหน้าในชื่อไฟล์ 001, 002…':'ไฟล์ .txt ภาษาไทย UTF-8 ไม่เกิน 1 MB'});
$('#upload-form').addEventListener('submit',e=>{e.preventDefault();busy($('#submit-work'),async()=>{const form=new FormData(e.target),files=[...$('#content-files').files].sort((a,b)=>a.name.localeCompare(b.name,undefined,{numeric:true}));await submit({...Object.fromEntries(form),rights:form.has('rights')},$('#cover-file').files[0],files);$('#upload-dialog').close();e.target.reset();notify('ส่งผลงานแล้ว รอทีมตอนต่อตรวจ');await refresh()})});
for(const [id,decision] of [['approve','published'],['reject','rejected']])$('#'+id).addEventListener('click',()=>busy($('#'+id),async()=>{await call('moderate',selected.id,decision,$('#review-note').value);$('#review-dialog').close();notify(decision==='published'?'อนุมัติแล้ว ผลงานขึ้นหน้าค้นพบ':'ส่งคำแนะนำให้ Creator แล้ว');await refresh()}));
$('#refresh').addEventListener('click',()=>busy($('#refresh'),refresh));
$('#export').addEventListener('click',()=>{if(!report)return;const quote=v=>'"'+String(v).replace(/"/g,'""')+'"';const rows=[['เรื่อง','ตอน','ชื่อตอน','ยอดชม / อ่าน','ผู้ชม / อ่าน','จบ','วินาที','ปลดล็อก','เหรียญซื้อ','เหรียญฟรี'],...tableRows.map(r=>[name(r.story),r.episode,chapterName(r),r.views,r.viewers,r.completes,r.seconds,r.unlocks,r.paid,r.free])];const url=URL.createObjectURL(new Blob(['\ufeff'+rows.map(r=>r.map(quote).join(',')).join('\r\n')],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='torntor-episode-stats.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
$('#login').addEventListener('submit',e=>{e.preventDefault();busy(e.target.querySelector('button'),async()=>{const f=new FormData(e.target);await signIn(f.get('email'),f.get('password'));e.target.reset();location.reload()})});
$('#join').addEventListener('click',()=>busy($('#join'),async()=>{await api('join',{});location.reload()}));
async function init(){c=await config();$('#mode').textContent=c.mode==='demo'?'โหมดทดลอง · ข้อมูลและไฟล์อยู่บนอุปกรณ์นี้ · ไม่รับเงินจริง':c.mode==='live'?'เชื่อมระบบจริง · สิทธิ์ตามบัญชีที่เข้าสู่ระบบ':c.mode==='test'?'โหมดทดสอบ Gateway · ไม่ใช่เงินจริง':'เชื่อมต่อไม่ได้ ลองรีเฟรช';if($('#connections'))$('#connections').innerHTML=[['ฐานข้อมูล',c.ready],['บัญชีสมาชิก',!!c.auth],['ไฟล์ส่วนตัว',c.storage],['PromptPay / TrueMoney / บัตร',c.payments]].map(([label,ready])=>`<div class="integration"><span>${label}</span><span class="${ready?'checkmark':'pending-label'}">${ready?'เชื่อมแล้ว':'รอเชื่อม'}</span></div>`).join('');if(c.mode!=='demo'){if(!token()){$('#login-panel').hidden=false;$('#dashboard').hidden=true;return}const me=await api('me');$('#admin-link').hidden=me.role!=='admin';if(me.role==='viewer'){$('#login-panel').hidden=false;$('#login').hidden=true;$('#join').hidden=admin;$('#dashboard').hidden=true;return}if(admin&&me.role!=='admin')throw Error('บัญชีนี้ไม่มีสิทธิ์ Admin');}if(c.mode==='demo')await demo.wallet();await refresh();}
init().catch(e=>{$('#dashboard').hidden=true;notify(e.message)});
