import {test,mock} from 'node:test';
import assert from 'node:assert/strict';
const queries=[];let profile={id:'verified-user',role:'viewer'};
mock.module('@neondatabase/serverless',{namedExports:{neon:()=>({query:async(text,params)=>{queries.push({text,params});if(text.startsWith('SELECT * FROM tt_users'))return [profile];if(text.includes('tt_limit'))return [{allowed:true}];return []}})}});
const {default:handler}=await import('../../api/torntor.js');
function response(){return {headers:{},statusCode:null,body:null,setHeader(k,v){this.headers[k]=v},status(s){this.statusCode=s;return this},json(b){this.body=b;return this}}}
const originalEnv={...process.env},originalFetch=globalThis.fetch;
function configure(){process.env.TORNTOR_MODE='test';process.env.TORNTOR_DATABASE_URL='postgres://fake:fake@fake.example/fake';process.env.TORNTOR_ORIGIN='https://www.myclover.com';process.env.TORNTOR_AUTH_URL='https://auth.example';process.env.TORNTOR_AUTH_PUBLIC_KEY='public-test';globalThis.fetch=async()=>({ok:true,json:async()=>({id:'verified-user'})});queries.length=0;profile={id:'verified-user',role:'viewer'};}
test('unauthenticated requests cannot access admin/creator/wallet',async()=>{configure();for(const action of ['stats','works','wallet']){const res=response();await handler({method:'GET',headers:{},query:{action},url:'/api/torntor'},res);assert.equal(res.statusCode,401);assert.equal(res.body.error,'SIGN_IN_REQUIRED')}assert.equal(queries.length,0)});
test('client supplied admin role cannot bypass database role',async()=>{configure();const res=response();await handler({method:'POST',headers:{origin:'https://www.myclover.com',authorization:'Bearer fake.jwt.test'},query:{action:'moderate'},body:{id:'work',decision:'published',role:'admin'},url:'/api/torntor'},res);assert.equal(res.statusCode,403);assert.equal(res.body.error,'ACCESS_DENIED');assert.equal(queries.some(q=>q.text.includes('UPDATE tt_works')),false)});
test('creator queries are scoped to verified user, not supplied owner',async()=>{configure();profile.role='creator';const res=response();await handler({method:'GET',headers:{authorization:'Bearer fake.jwt.test'},query:{action:'works',owner:'someone-else'},url:'/api/torntor'},res);assert.equal(res.statusCode,200);const workQuery=queries.find(q=>q.text.includes('FROM tt_works'));assert.match(workQuery.text,/owner=\$1/);assert.deepEqual(workQuery.params,['verified-user'])});
test('cross-origin mutation rejected before auth/DB',async()=>{configure();const res=response();await handler({method:'POST',headers:{origin:'https://evil.example',authorization:'Bearer fake.jwt.test'},query:{action:'daily'},body:{},url:'/api/torntor'},res);assert.equal(res.statusCode,403);assert.equal(queries.length,0)});
test('demo is non-transactional on server and does not expose keys',async()=>{configure();process.env.TORNTOR_MODE='demo';process.env.TORNTOR_OMISE_SECRET_KEY='skey_test_fake';const res=response();await handler({method:'GET',headers:{},query:{action:'config'},url:'/api/torntor'},res);assert.equal(res.body.mode,'demo');assert.equal(JSON.stringify(res.body).includes('skey_'),false);const denied=response();await handler({method:'POST',headers:{origin:'https://www.myclover.com'},query:{action:'daily'},body:{},url:'/api/torntor'},denied);assert.equal(denied.statusCode,503)});
test.after(()=>{globalThis.fetch=originalFetch;for(const k of Object.keys(process.env))if(!(k in originalEnv))delete process.env[k];Object.assign(process.env,originalEnv)});
