import {config,call,api,token} from './client.js';
import {demo} from './demo.js';
import {packs,html,nextMidnight} from './rules.js';
let c,order=null,pack=packs[0],method='promptpay',callback,notice,activePoll=false;
const $=s=>document.querySelector(s);
export async function setupWallet(onUpdate,toast){callback=onUpdate;notice=toast;c=await config();const area=$('#wallet-dialog');area.insertAdjacentHTML('beforeend',`<div class="daily-reward"><span><strong>ของขวัญประจำวัน</strong><small>20 เหรียญ · สะสมได้ · เริ่มวันใหม่ 00:00 น.</small></span><button id="claim-daily">รับ 20 เหรียญ</button></div><p class="wallet-coin-detail" id="wallet-detail"></p><p class="wallet-links"><a href="/short/studio/">Creator Studio ↗</a> <a href="/short/admin/" id="wallet-admin">Admin ↗</a></p><button id="wallet-signin" hidden>เข้าสู่ระบบบัญชี</button>`);
 const dlg=document.createElement('dialog');dlg.id='checkout-dialog';dlg.className='small-dialog';dlg.innerHTML=`<button class="dialog-close icon-button" id="checkout-close" aria-label="ปิดชำระเงิน">×</button><p class="section-kicker">TORNTOR WALLET</p><h2>เติมเหรียญ</h2><p id="checkout-pack"></p><div class="payment-methods"><button data-method="promptpay" aria-pressed="true"><strong>PromptPay</strong><small>สแกน QR</small></button><button data-method="truemoney" aria-pressed="false"><strong>TrueMoney</strong><small>Wallet</small></button><button data-method="card" aria-pressed="false"><strong>บัตร</strong><small>เครดิต / เดบิต</small></button></div><p class="wallet-disclaimer" id="checkout-mode"></p><div id="payment-result" role="status"></div><button class="button primary full-width" id="checkout-pay">ดำเนินการต่อ</button><div class="demo-payment-actions" hidden><button id="simulate-paid">จำลองจ่ายสำเร็จ</button><button id="simulate-failed">จำลองจ่ายไม่สำเร็จ</button></div><button id="check-payment" hidden>ตรวจสถานะการจ่าย</button>`;document.body.append(dlg);
 $('#checkout-close').onclick=()=>dlg.close();dlg.addEventListener('close',()=>{activePoll=false});
 dlg.querySelectorAll('[data-method]').forEach(b=>b.onclick=()=>{if(order)return;method=b.dataset.method;dlg.querySelectorAll('[data-method]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));});
 $('#claim-daily').onclick=async()=>{const b=$('#claim-daily');b.disabled=true;try{await update(await call('daily'));notice('รับ 20 เหรียญแล้ว เก็บสะสมได้')}catch(e){notice(readable(e.message));b.disabled=false}};
 $('#checkout-pay').onclick=async()=>{const b=$('#checkout-pay');b.disabled=true;try{if(c.mode!=='demo'&&!token())throw Error('SIGN_IN_REQUIRED');if(c.mode==='demo'){order=await call('order',pack.id,method);$('#payment-result').innerHTML='<div class="test-payment-mark">✦</div><strong>รายการทดลองพร้อมแล้ว</strong><p>เลือกผลการชำระเงินเพื่อเทสระบบ<br>ไม่มี QR หรือข้อมูลบัตรสำหรับจ่ายเงินจริง</p>';$('.demo-payment-actions').hidden=false;}else{if(!c.payments)throw Error('PAYMENT_NOT_CONFIGURED');const nonce=await paymentToken();order=await call('order',pack.id,method,nonce);if(order.qr){const url=new URL(order.qr);if(url.protocol==='https:')$('#payment-result').innerHTML=`<img class="payment-qr" src="${html(url.href)}" alt="QR สำหรับชำระเงิน"><p>ชำระแล้วกดตรวจสถานะ</p>`;}if(order.redirect){const url=new URL(order.redirect);if(url.protocol!=='https:')throw Error('PAYMENT_PROVIDER_ERROR');sessionStorage.setItem('torntor:pending-order',order.id);location.assign(url.href);return;}$('#check-payment').hidden=false;if(order.wallet)await update(order.wallet);poll(order.id);}b.hidden=true;}catch(e){notice(readable(e.message))}finally{b.disabled=false}};
 for(const [id,status] of [['simulate-paid','paid'],['simulate-failed','failed']])$('#'+id).onclick=async()=>{if(!order)return;const buttons=[...$('.demo-payment-actions').querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{const result=await demo.settle(order.id,status);await update(result.wallet);$('.demo-payment-actions').hidden=true;$('#payment-result').textContent=status==='paid'?`สำเร็จ ได้รับ ${result.coins} เหรียญทดลอง`:'ไม่สำเร็จ · ไม่เพิ่มเหรียญ';notice(status==='paid'?'เติมเหรียญทดลองสำเร็จ':'รายการทดลองไม่สำเร็จ')}catch(e){notice(e.message)}finally{buttons.forEach(b=>b.disabled=false)}};
 $('#check-payment').onclick=()=>poll(order?.id);
 $('#wallet-signin').onclick=()=>location.assign('/short/studio/');
 document.querySelectorAll('[data-pack]').forEach(b=>{const p=packs.find(p=>p.id===b.dataset.pack);b.querySelector('span').textContent=p?'฿'+p.amount/100:'เหรียญ';});
 area.querySelector('.wallet-disclaimer').textContent=c.mode==='demo'?'โหมดทดลอง · ไม่มีการรับเงินจริง':c.mode==='test'?'Gateway ทดสอบ · ไม่รับเงินจริง':'เครดิตเหรียญหลังตรวจสอบการชำระสำเร็จ';
 $('#wallet-title').textContent='เหรียญของคุณ';$('.balance-box > span').textContent='ยอดคงเหลือ';$('#wallet-signin').hidden=c.mode==='demo'||!!token();$('#wallet-admin').hidden=c.mode!=='demo';
 if(c.mode==='demo'||token()){await update(await call('wallet'));await update(await call('daily'));}else{$('#claim-daily').disabled=true;$('#wallet-detail').textContent='เข้าสู่ระบบเพื่อใช้เหรียญและรับของขวัญรายวัน';}
 const pending=new URLSearchParams(location.search).get('order')||sessionStorage.getItem('torntor:pending-order');if(pending&&c.mode!=='demo'&&token()){order={id:pending};dlg.showModal();$('#checkout-pack').textContent='ตรวจรายการชำระเงิน';$('#checkout-pay').hidden=true;await poll(pending);}
 const checkDay=async()=>{if(c.mode==='demo'||token())try{await update(await call('daily'))}catch{}setTimeout(checkDay,Math.max(1000,nextMidnight()-Date.now()+1000))};setTimeout(checkDay,Math.max(1000,nextMidnight()-Date.now()+1000));
 document.addEventListener('visibilitychange',()=>{if(!document.hidden&&(c.mode==='demo'||token()))call('daily').then(update).catch(()=>{})});
}
async function update(w){callback(w);$('#claim-daily').textContent=w.claimed?'รับแล้ววันนี้':'รับ 20 เหรียญ';$('#claim-daily').disabled=w.claimed;$('#wallet-detail').textContent=`เหรียญฟรี ${w.free} · เหรียญ${c.mode==='demo'?'เติมทดลอง':'ซื้อ'} ${w.paid}`;}
export function openCheckout(id){pack=packs.find(p=>p.id===String(id))||packs[0];order=null;method='promptpay';$('#wallet-dialog').close();$('#checkout-pack').textContent=`${pack.coins} เหรียญ · ฿${pack.amount/100}`;$('#checkout-mode').textContent=c.mode==='demo'?'โหมดทดลอง ไม่มีการเรียกเก็บเงิน':c.mode==='test'?'ทดสอบกับ Gateway ใช้ข้อมูลทดสอบเท่านั้น':'รับเหรียญหลังตรวจสอบการชำระสำเร็จ';$('#payment-result').textContent='';$('#checkout-pay').hidden=false;$('.demo-payment-actions').hidden=true;$('#check-payment').hidden=true;document.querySelectorAll('[data-method]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.method==='promptpay')));$('#checkout-dialog').showModal();}
async function paymentToken(){if(!window.OmiseCard){await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.omise.co/omise.js';s.onload=resolve;s.onerror=()=>reject(Error('PAYMENT_PROVIDER_ERROR'));document.head.append(s)})}window.OmiseCard.configure({publicKey:c.publicKey,locale:'th',frameLabel:'ตอนต่อ'});$('#checkout-dialog').close();return new Promise((resolve,reject)=>{let created=false;window.OmiseCard.open({amount:pack.amount,currency:'THB',defaultPaymentMethod:method==='card'?'credit_card':method,otherPaymentMethods:'',onCreateTokenSuccess:nonce=>{created=true;$('#checkout-dialog').showModal();resolve(nonce)},onFormClosed:()=>{if(!created){$('#checkout-dialog').showModal();reject(Error('ยกเลิกการชำระเงิน'))}}})});}
async function poll(id){if(!id||c.mode==='demo')return;activePoll=true;try{const value=await api('order-status',{id});await update(value.wallet);$('#payment-result').textContent=value.order.status==='paid'?'ชำระสำเร็จ เพิ่มเหรียญแล้ว':`สถานะ: ${value.order.status}`;if(value.order.status==='paid')sessionStorage.removeItem('torntor:pending-order');else if(value.order.status==='pending'&&$('#checkout-dialog').open&&activePoll)setTimeout(()=>poll(id),5000);}catch(e){notice(readable(e.message))}}
export function readable(error){return {SIGN_IN_REQUIRED:'เข้าสู่ระบบก่อนทำรายการ',PAYMENT_NOT_CONFIGURED:'กำลังรอเชื่อมบัญชีร้านค้า',INTEGRATION_NOT_CONFIGURED:'กำลังรอเชื่อมระบบจริง',CHECK_EXISTING_ORDER:'มีรายการค้างอยู่ ตรวจสถานะรายการเดิมก่อน',ACCESS_DENIED:'บัญชีนี้ไม่มีสิทธิ์ทำรายการ',INSUFFICIENT_COINS:'เหรียญไม่พอ'}[error]||error;}
