export * from './game-copy-v9a.js?v=1.0a-core';
import * as oldCopy from './game-copy-v9a.js?v=1.0a-core';
import {EVENTS,STAGES,ORGANIZATION_XIRCLE_MONTHS,TRAVEL_MONTHS,XGEN_SINGLE_MONTH_TARGET,calculateEconomy,getBestNextActions,canOfferFullSetFastLane} from './game-data.js';
const fmt=v=>Math.round(Number(v||0)).toLocaleString('th-TH');
function selected(s){const a=[...(s.prospects||[]),...(s.customers||[]),...(s.team||[])];return a.find(p=>p.id===s.selectedPersonId)||a[0]||null}
function routine(s){const p=selected(s),full=canOfferFullSetFastLane(s,p);return{scene:'routine_builder',progress:76,eyebrow:'ROUTINE · อ่านเคสก่อนเลือก',title:`วาง Routine ให้ ${p?.name||'คนนี้'}`,reason:'อ่านบริบทตรงหน้าก่อน · ทางเลือกที่แรงขึ้นจะเปิดเมื่อ Skill, Trust และผลลัพธ์ที่คุณสร้างมามากพอ',speaker:p?.name||'ลูกค้า',dialogue:p?.quote?`“${p.quote}”`:(p?.status||'อยากเริ่มจากสิ่งที่ทำได้จริง'),facts:[['❤️ Trust',`${fmt(p?.trust||0)} / 100`],['📈 Readiness',`${fmt(p?.readiness||0)} / 100`],['🚀 ครบชุด',full?'เปิดแล้ว':'ยังไม่เหมาะกับเคสนี้']],routineBuilder:{fitProducts:p?.fitProducts||[],fullSetEnabled:full,choices:[['control','เริ่มจาก C','เริ่มจากพฤติกรรมเดียวที่ทำซ้ำได้ · ยังไม่ต้องซื้อสินค้า'],['fit','ดู ABCD','ใช้ A / B / D เท่าที่ตรงกับบริบทและสิ่งที่ฟังมา'],['all','ครบชุด',full?'ทางลัดที่แรงกว่า · ใช้เมื่อเคสนี้พร้อมจริง':'🔒 ยังไม่ควรเสนอ · สร้าง Skill, Trust และผลลัพธ์ก่อน']]},actions:[],routineEvent:EVENTS.CHOOSE_MANAGEMENT_ROUTINE}}
function org(s){const r=s.lastOrganizationReport||{},e=calculateEconomy(s),m=Number(s.month||13),xc=ORGANIZATION_XIRCLE_MONTHS.includes(m),trip=s.year2Path==='xgen'&&TRAVEL_MONTHS.includes(m)?s.activeTravel:null,path=s.year2Path==='xgen'?'XGEN ORGANIZATION':'XLEAD ORGANIZATION',scene=trip?`travel_${String(trip.destination||'').toLowerCase()}`:xc?'the-xircle':'management_org',title=trip?`✈️ ${trip.destination} · Recognition Trip`:xc?`🏕️ The Xircle · เดือน ${m}`:`Organization Year · เดือน ${m}`,reason=trip?`ยินดีด้วย! ผลงานของทีมพาคุณผ่านทริป ${trip.destination} · ฉากนี้จะอยู่จนกดผ่านเดือน`:xc?'เดือนพิเศษของทีม · Retention, Referral, Comeback และ Candidate Readiness ได้แรงส่งเพิ่ม':s.year2Path==='xgen'?'XGEN Path · ระบบเดินเอง แต่ลูกค้าและทีมยังมีทั้งโต พัก หยุด และกลับมา':'XLEAD Path · ระบบยังเดินต่อ แต่ไม่มี ③ Organization 5% และไม่มี Recognition Trip';return{scene,progress:100,eyebrow:`${path} · MONTH ${m}`,title,reason,speaker:trip?'🏆 TEAM RECOGNITION':xc?'THE XIRCLE · RESET · RECONNECT · RISE':'ORGANIZATION REPORT',dialogue:trip?`ทีมที่คุณสร้างในปีแรกพาคุณมาถึง ${trip.destination}`:r.month?`เดือน ${r.month} · ลูกค้าสุทธิ ${r.netCustomers>=0?'+':''}${fmt(r.netCustomers)} · ทีมสุทธิ ${r.netXvisors>=0?'+':''}${fmt(r.netXvisors)} · รายได้ ฿${fmt(r.income)}`:'กดเดือนละครั้ง ระบบจะรัน Xcademy ×4, Open House ×1 และ The Xircle ตามรอบให้เอง',facts:[['📊 TGV ล่าสุด',`${fmt(r.tgv||s.organization?.lastMonthTGV||0)} XV`],['💰 รายได้ล่าสุด',`฿${fmt(r.income||0)}`],['❤️ ลูกค้า Active',fmt(s.organization?.aggregate?.activeCustomers||0)],['🌱 X-VISOR / XLEAD',`${fmt(s.organization?.aggregate?.xvisorCount||0)} / ${fmt(s.organization?.aggregate?.xleadCount||0)}`]],management:null,monthSummary:null,actions:[{label:'▶ ผ่านไปอีก 1 เดือน',event:EVENTS.END_MONTH,icon:'month',cost:0}]}}
function xgen(s){const t=Math.max(0,Number(s.economy?.personalXV||0)+Number(s.economy?.teamXV||0));return{...oldCopy.getStageContent(s),scene:'xgen',eyebrow:'🏆 XGEN · SINGLE-MONTH QUALIFICATION',title:'แตะ 3,000,000 XV ในเดือนเดียวแล้ว',reason:'Qualification ผ่านถาวรในรอบนี้ และ ③ Organization 5% เริ่มคิดจากเดือนนี้ทันที',speaker:'XOS · Organization',dialogue:`TGV เดือนนี้ ${fmt(t)} XV · เป้าหมาย ${fmt(XGEN_SINGLE_MONTH_TARGET)} XV`,facts:[['ช่วงที่วัด','เดือนเดียว'],['Qualification','ผ่านแล้ว'],['③ เดือนนี้',`฿${fmt(Math.round(t*.05))}`]],actions:getBestNextActions(s,3)}}
export function getStageContent(s){if(s.stage===STAGES.MANAGEMENT_ROUTINE)return routine(s);if(s.organizationMode&&!s.runComplete)return org(s);if(s.sceneReport?.kind==='xgen-qualified-1b')return xgen(s);const b=oldCopy.getStageContent(s);if((s.stage===STAGES.MANAGEMENT||s.runMode==='NEW_GAME_PLUS')&&!s.organizationMode&&!s.runComplete)return{...b,actions:getBestNextActions(s,3)};return b}
