import { EVENTS, STAGES } from "./game-data.js";

const action = (label, event, options = {}) => ({ label, event, ...options });

const base = {
  eyebrow: "เป้าหมายของคุณ",
  note: "",
  actions: [],
  progress: 0,
};

export function getStageContent(state) {
  const name = state.customer?.name || state.team?.[0]?.name || "มิ้นท์";
  const copy = {
    [STAGES.OPENING]: {
      ...base,
      scene: "opening",
      progress: 0,
      title: "เริ่มเส้นทาง X-VISOR",
      reason: "เริ่มจากตัวเอง ดูแลคนแรก แล้วค่อยสร้างทีมที่ช่วยกันดูแลคนได้",
      speaker: "X-VISOR QUEST",
      dialogue: "เกมนี้จะพาคุณลองทำงานจริงทีละขั้น โดยไม่ต้องรู้คำศัพท์มาก่อน",
      actions: [action("เริ่มเส้นทาง", EVENTS.START_PATH, { icon: "play" })],
    },
    [STAGES.SELF_INTRO]: {
      ...base,
      scene: "home",
      progress: 4,
      title: "เริ่มจากเป็นผู้ใช้ก่อน",
      reason: "ก่อนดูแลคนอื่น คุณควรรู้ว่าประสบการณ์ของลูกค้าเป็นอย่างไร",
      speaker: "ก้าวแรก",
      dialogue: "ตอนนี้คุณยังไม่มีลูกค้า ไม่มีทีม และยังไม่ต้องรีบขายอะไร",
      actions: [action("เริ่มใช้ RoutineX", EVENTS.START_SELF, { icon: "box" })],
    },
    [STAGES.SELF_USED]: {
      ...base,
      scene: "home_product",
      progress: 8,
      title: "วัดข้อมูลตั้งต้นของคุณ",
      reason: "ข้อมูลจริงช่วยให้เลือกสิ่งที่ควรเริ่มเปลี่ยนก่อนหนึ่งอย่าง",
      speaker: "RoutineX เริ่มแล้ว",
      dialogue: "ขั้นต่อไป ลองวัด Xircle เพื่อดูว่าตอนนี้ควรเริ่มจากตรงไหน",
      actions: [action("ไปวัด Xircle", EVENTS.GO_SELF_MEASURE, { icon: "scale" })],
    },
    [STAGES.SELF_MEASURE_INTRO]: {
      ...base,
      scene: "self_measure",
      progress: 12,
      title: "ขึ้น Xircle Scale",
      reason: "การวัดไม่ได้จบที่ตัวเลข แต่ต้องแปลเป็นสิ่งที่ทำต่อได้",
      speaker: "Xircle",
      dialogue: "ยืนให้นิ่งสักครู่ แล้วดูข้อมูลของคุณไปพร้อมกัน",
      actions: [action("เริ่มวัดตัวเอง", EVENTS.START_SELF_SCAN, { icon: "scan" })],
    },
    [STAGES.SELF_SCANNING]: {
      ...base,
      scene: "self_scanning",
      progress: 15,
      title: "กำลังวัดข้อมูลของคุณ",
      reason: "Xircle กำลังอ่านข้อมูลตั้งต้น",
      speaker: "Xircle",
      dialogue: "กำลังวัด…",
      status: "scan",
    },
    [STAGES.SELF_RESULT]: {
      ...base,
      scene: "self_result",
      progress: 18,
      title: "เลือก Next Action หนึ่งอย่าง",
      reason: "ไม่ต้องแก้ทุกอย่างพร้อมกัน เริ่มจากสิ่งเล็กที่ทำต่อได้",
      speaker: "สิ่งที่ควรทำต่อ",
      dialogue: "จัดช่วงเช้าให้สม่ำเสมอ: ดื่มน้ำ กินมื้อแรก และเริ่มวันในเวลาใกล้เดิม",
      resultCards: [
        ["พลังงาน", "ควรใส่ใจ", "warn"],
        ["ความสม่ำเสมอ", "ยังแกว่ง", "warn"],
        ["Body Trend", "จุดเริ่มต้น", "neutral"],
      ],
      actions: [action("เลือกแผนช่วงเช้า", EVENTS.CHOOSE_NEXT_ACTION, { icon: "check" })],
    },
    [STAGES.EXPERIENCE_INTRO]: {
      ...base,
      scene: "routine",
      progress: 22,
      title: "ลองทำด้วยตัวเอง 28 วัน",
      reason: "คุณจะได้เข้าใจทั้งวันที่ทำได้ดีและวันที่ต้องกลับมาตั้งหลักใหม่",
      speaker: "RoutineX 28 วัน",
      dialogue: "เมื่อมีประสบการณ์ของตัวเอง คุณจะคุยกับลูกค้าได้จากสิ่งที่เคยผ่านจริง",
      actions: [action("เริ่ม 28 วัน", EVENTS.START_EXPERIENCE, { icon: "calendar" })],
    },
    [STAGES.EXPERIENCE_RUNNING]: {
      ...base,
      scene: "routine_running",
      progress: 30,
      title: "ทำต่อทีละวัน",
      reason: "ความสม่ำเสมอสำคัญกว่าการทำได้สมบูรณ์ทุกวัน",
      speaker: "28 วันของคุณ",
      dialogue: "กำลังบันทึกประสบการณ์…",
      status: "montage",
    },
    [STAGES.ACADEMY_INTRO]: {
      ...base,
      scene: "academy",
      progress: 34,
      title: "เรียนวิธีดูแลคนให้เดินต่อ",
      reason: "ใช้ข้อมูล ฟังคน และช่วยเลือก Next Action ที่เหมาะกับเขา",
      speaker: "Xcademy",
      dialogue: "คุณมีประสบการณ์ของตัวเองแล้ว ต่อไปเรียน CARE, Xircle และการติดตามลูกค้า",
      actions: [action("ไปเรียน Xcademy", EVENTS.OPEN_ACADEMY, { icon: "book" })],
    },
    [STAGES.ACADEMY]: {
      ...base,
      scene: "academy_lesson",
      progress: 38,
      title: "เตรียมสอบ Certification",
      reason: "ต้องใช้เอง เรียน และเข้าใจการดูแล ก่อนเริ่มดูแลคนจริง",
      speaker: "หลักที่ต้องจำ",
      dialogue: "Change เริ่มจากตัวเอง · Attract ฟังให้เข้าใจ · Result ดูแลให้เห็นผล · Elevate ช่วยคนเติบโต",
      actions: [action("ไปสอบ Certification", EVENTS.START_CERTIFICATION, { icon: "certificate" })],
    },
    [STAGES.CERTIFICATION]: {
      ...base,
      scene: "certification",
      progress: 42,
      title: "เลือกวิธีดูแลที่เหมาะที่สุด",
      reason: "ถ้าลูกค้าเริ่มหลุดจากแผน คุณควรทำอะไรเป็นอย่างแรก?",
      speaker: state.lastEvent === "CERTIFICATION_RETRY" ? "ลองอีกครั้ง" : "Certification",
      dialogue: state.lastEvent === "CERTIFICATION_RETRY"
        ? "เป้าหมายไม่ใช่รีบขายเพิ่ม แต่ช่วยให้เขากลับมาทำต่อได้"
        : "เลือกคำตอบที่ทำให้ลูกค้าเดินต่อได้จริง",
      choices: [
        action("ช่วยหา Next Action เล็กที่สุด", EVENTS.ANSWER_CERTIFICATION, { value: "next_action", icon: "check" }),
        action("เสนอสินค้าเพิ่มทันที", EVENTS.ANSWER_CERTIFICATION, { value: "sell_more", kind: "secondary" }),
        action("รอให้เขากลับมาเอง", EVENTS.ANSWER_CERTIFICATION, { value: "wait", kind: "secondary" }),
      ],
    },
    [STAGES.CERTIFIED]: {
      ...base,
      scene: "certified",
      progress: 46,
      title: "เริ่มเดือน 1 ด้วยลูกค้า 0 คน",
      reason: "คนแรกต้องเริ่มจากการออกไปทำความรู้จัก ไม่ใช่กดขายทันที",
      speaker: "Certified X-VISOR",
      dialogue: "จากนี้คุณเริ่มดูแลลูกค้าได้แล้ว",
      milestone: "CERTIFIED",
      actions: [action("เริ่มเดือน 1", EVENTS.START_MONTH, { icon: "flag" })],
    },
    [STAGES.MONTH_EMPTY]: {
      ...base,
      scene: "empty_office",
      progress: 50,
      title: "รู้จักคนใหม่ 1 คน",
      reason: "งานแรกไม่ใช่ขาย แค่เริ่มจากฟังว่าใครอยากเปลี่ยนอะไร",
      speaker: "Clover Neighborhood",
      dialogue: "ตอนนี้ยังไม่มีใครนัดกับคุณ เก้าอี้ฝั่งลูกค้ายังว่างอยู่",
      actions: [action("ออกไปพบคน", EVENTS.FIND_PERSON, { icon: "walk", cost: 1 })],
    },
    [STAGES.PERSON_MET]: {
      ...base,
      scene: "mint_arrives",
      progress: 54,
      title: `ฟังว่า${name}อยากเปลี่ยนอะไร`,
      reason: "ตอนนี้ยังไม่ต้องรีบเสนอ ลองเข้าใจชีวิตจริงของเขาก่อน",
      speaker: `รู้จัก “${name}” แล้ว`,
      dialogue: `${name}บอกว่า ช่วงบ่ายมักไม่มีแรง แล้วกลับบ้านก็ไม่อยากทำอะไร`,
      actions: [action(`คุยกับ${name}`, EVENTS.TALK, { icon: "talk", cost: 1 })],
    },
    [STAGES.TALKED]: {
      ...base,
      scene: "consultation",
      progress: 57,
      title: `ชวน${name}วัด Xircle`,
      reason: "ตอนนี้คุณรู้สิ่งที่เขากังวลแล้ว ลองดูข้อมูลจริงร่วมกัน",
      speaker: name,
      dialogue: "“ช่วงบ่ายเราง่วงมาก แล้วพอกลับบ้านก็ไม่อยากทำอะไรแล้ว”",
      actions: [
        action("ชวนวัด Xircle", EVENTS.INVITE_MEASUREMENT, { icon: "scale", cost: 2 }),
        action("คุยต่ออีกนิด", EVENTS.TALK_MORE, { icon: "talk", cost: 1, kind: "secondary" }),
      ],
    },
    [STAGES.TALKED_READY]: {
      ...base,
      scene: "consultation",
      progress: 59,
      title: `ชวน${name}วัด Xircle`,
      reason: "คุณเข้าใจเป้าหมายของเขาชัดขึ้นแล้ว ถึงเวลาคุยจากข้อมูลจริง",
      speaker: name,
      dialogue: "“ถ้าเริ่มจากเรื่องเดียว เราอยากมีแรงช่วงบ่ายมากขึ้น”",
      actions: [action("ชวนวัด Xircle", EVENTS.INVITE_MEASUREMENT, { icon: "scale", cost: 2 })],
    },
    [STAGES.MEASUREMENT_INTRO]: {
      ...base,
      scene: "customer_measure",
      progress: 62,
      title: `วัด Xircle ให้${name}ครั้งแรก`,
      reason: "การวัดช่วยให้คุณทั้งคู่คุยจากสิ่งที่เห็นร่วมกัน ไม่ต้องเดา",
      speaker: "Xircle Scale",
      dialogue: `${name}พร้อมแล้ว ยืนให้นิ่งสักครู่`,
      actions: [action("เริ่มวัด", EVENTS.START_MEASUREMENT, { icon: "scan", cost: 2 })],
    },
    [STAGES.MEASURING]: {
      ...base,
      scene: "customer_scanning",
      progress: 64,
      title: `กำลังวัดข้อมูลของ${name}`,
      reason: "ผลจะถูกแปลเป็นสิ่งที่ควรทำต่อหนึ่งอย่าง",
      speaker: "Xircle",
      dialogue: "กำลังวัด…",
      status: "scan",
    },
    [STAGES.MEASURED]: {
      ...base,
      scene: "customer_result",
      progress: 67,
      title: `คุยเรื่องแผนที่เหมาะกับ${name}`,
      reason: "ตอนนี้คุณมีทั้งเป้าหมายของเขาและข้อมูลตั้งต้นแล้ว",
      speaker: `ผลครั้งแรกของ${name}`,
      dialogue: "เริ่มจากทำช่วงเช้าให้สม่ำเสมอก่อน ยังไม่ต้องแก้ทุกอย่างพร้อมกัน",
      resultCards: [
        ["พลังงาน", "ต้องใส่ใจ", "warn"],
        ["ความสม่ำเสมอ", "ยังแกว่ง", "warn"],
        ["Body Trend", "เริ่มต้น", "neutral"],
      ],
      actions: [action("คุยเรื่องแผนต่อ", EVENTS.DISCUSS_PLAN, { icon: "plan" })],
    },
    [STAGES.OFFER_READY]: {
      ...base,
      scene: "offer",
      progress: 70,
      title: `เสนอ RoutineX ให้${name}`,
      reason: "เขารู้ว่าอยากเปลี่ยนอะไร และคุณมีข้อมูลพอจะอธิบายแผนแล้ว",
      speaker: "ความพร้อม: ค่อนข้างพร้อม",
      dialogue: "ได้วัดแล้ว · เข้าใจเป้าหมาย · เชื่อใจคุณมากขึ้น",
      actions: [
        action("เสนอ RoutineX", EVENTS.SELL, { icon: "box", cost: 1, detail: "฿7,490 · 7,000 XV" }),
        action("ยังไม่เสนอ", EVENTS.DEFER_OFFER, { icon: "later", kind: "secondary" }),
      ],
    },
    [STAGES.SALE_RECEIPT]: {
      ...base,
      scene: "sale",
      progress: 74,
      title: "ดูว่ายอดขาย XV และรายได้ต่างกันอย่างไร",
      reason: "ทุกครั้งที่ขายสำเร็จ ตัวเลขทั้งสามจะเปลี่ยนแต่ไม่ใช่เลขเดียวกัน",
      speaker: "ขายสำเร็จ!",
      dialogue: `${name}เริ่ม RoutineX แล้ว`,
      milestone: "FIRST SALE",
    },
    [STAGES.CARE_START]: {
      ...base,
      scene: "care_start",
      progress: 77,
      title: `เริ่มดูแล${name}ต่อ`,
      reason: "ขายได้คือจุดเริ่มต้น ผลลัพธ์จะเกิดจากสิ่งที่ทำหลังจากนี้",
      speaker: "วันที่ 1 ของแผน",
      dialogue: `${name}มี Next Action ที่ชัดแล้ว ต่อไปต้องติดตามว่าเขาทำต่อได้จริงไหม`,
      actions: [action("เริ่มดูแลต่อ", EVENTS.START_CARE, { icon: "heart" })],
    },
    [STAGES.FOLLOWUP_DUE]: {
      ...base,
      scene: "followup_due",
      progress: 80,
      title: `ทักติดตาม${name}`,
      reason: `${name}ทำแผนมา 7 วันแล้ว ถึงเวลาฟังว่าอะไรทำได้และอะไรติดขัด`,
      speaker: "XOS เตือนให้ดูแล",
      dialogue: "วันนี้ควรทักมิ้นท์ ไม่ใช่เพราะต้องขายเพิ่ม แต่เพื่อช่วยให้เขาเดินต่อ",
      actions: [action("ทักติดตาม", EVENTS.FOLLOW_UP, { icon: "message", cost: 1 })],
    },
    [STAGES.FOLLOWUP_RESULT]: {
      ...base,
      scene: "followup",
      progress: 83,
      title: `ช่วย${name}เลือกสิ่งที่จะทำต่อ`,
      reason: "การติดตามที่ดีเปลี่ยนปัญหาให้เป็น Next Action ที่ทำได้จริง",
      speaker: name,
      dialogue: "“ช่วงนี้ทำได้เกือบทุกวัน แต่วันทำงานรีบมากจนพลาดมื้อเช้า”",
      actions: [action("ช่วยวาง Next Action", EVENTS.SET_NEXT_ACTION, { icon: "plan" })],
    },
    [STAGES.REMEASURE_READY]: {
      ...base,
      scene: "consultation",
      progress: 85,
      title: `นัด${name}วัดซ้ำ`,
      reason: "การวัดซ้ำทำให้เห็นว่าพฤติกรรมที่ทำต่อเนื่องเปลี่ยนอะไรบ้าง",
      speaker: "ครบ 28 วัน",
      dialogue: `${name}ทำช่วงเช้าได้สม่ำเสมอขึ้นแล้ว ลองกลับไปดูข้อมูลอีกครั้ง`,
      actions: [action("นัดวัดซ้ำ", EVENTS.START_REMEASUREMENT, { icon: "scale", cost: 2 })],
    },
    [STAGES.REMEASURING]: {
      ...base,
      scene: "customer_scanning",
      progress: 87,
      title: `กำลังเทียบผลของ${name}`,
      reason: "ดูแนวโน้มก่อนและตอนนี้ ไม่ต้องไล่ตัวเลขมากเกินไป",
      speaker: "Xircle",
      dialogue: "กำลังเปรียบเทียบ…",
      status: "scan",
    },
    [STAGES.REMEASURED]: {
      ...base,
      scene: "remeasured",
      progress: 90,
      title: "บันทึก Success Case แรก",
      reason: `${name}ไม่ได้แค่ซื้อสินค้า แต่เริ่มเห็นความเปลี่ยนแปลงของตัวเองแล้ว`,
      speaker: name,
      dialogue: "“เห็นแบบนี้แล้วอยากทำต่อเลย”",
      comparison: [
        ["พลังงาน", "ต้องใส่ใจ", "ดีขึ้น"],
        ["ความสม่ำเสมอ", "ยังแกว่ง", "สม่ำเสมอขึ้น"],
        ["Body Trend", "เริ่มต้น", "ทิศทางดี"],
      ],
      actions: [action("บันทึก Success Case", EVENTS.SAVE_SUCCESS, { icon: "star" })],
    },
    [STAGES.SUCCESS_CASE]: {
      ...base,
      scene: "success",
      progress: 92,
      title: `ดูแล${name}ให้เดินต่อ`,
      reason: "เมื่อคนเห็นผล ความเชื่อใจ โอกาสซื้อซ้ำ และการบอกต่อจะดีขึ้น",
      speaker: "Success Case แรก",
      dialogue: `${name}เริ่มเห็นความเปลี่ยนแปลงจากข้อมูลและสิ่งที่ทำต่อเนื่อง`,
      milestone: "RESULT",
      actions: [action("ดูแลต่อ", EVENTS.CONTINUE_CARE, { icon: "heart" })],
    },
    [STAGES.XVISOR_INTEREST]: {
      ...base,
      scene: "interest",
      progress: 94,
      title: `เล่าเส้นทาง X-VISOR ให้${name}ฟัง`,
      reason: "ความสนใจนี้เกิดหลังจากเขาเห็นผลและเข้าใจการดูแล ไม่ใช่จากการชวนทันที",
      speaker: name,
      dialogue: "“ถ้าเราอยากช่วยคนอื่นแบบที่คุณทำ ต้องเริ่มยังไง?”",
      actions: [action("เล่าเส้นทางให้ฟัง", EVENTS.EXPLAIN_XVISOR, { icon: "path" })],
    },
    [STAGES.CANDIDATE]: {
      ...base,
      scene: "candidate",
      progress: 95,
      title: `ช่วย${name}ผ่าน Xcademy และ Certification`,
      reason: "ตอนนี้เขายังไม่ใช่ X-VISOR ต้องเรียน ทดลอง และผ่านมาตรฐานก่อน",
      speaker: `${name}เริ่มเรียน Xcademy`,
      dialogue: "คุณจะไม่ทำแทน แต่ช่วยให้เขาเข้าใจวิธีเริ่มจากตัวเองและดูแลคนแรก",
      actions: [action("ช่วยเตรียมตัว", EVENTS.PREPARE_CANDIDATE, { icon: "book", cost: 1 })],
    },
    [STAGES.FIRST_G1]: {
      ...base,
      scene: "first_g1",
      progress: 97,
      title: `พา${name}เริ่มดูแลคนแรก`,
      reason: "บทบาทของคุณเริ่มเปลี่ยน จากทำเองไปเป็นช่วยให้คนอื่นทำได้",
      speaker: "X-VISOR คนแรกในทีม",
      dialogue: `${name}ผ่าน Certification แล้ว เขายังใหม่และยังไม่มีลูกค้า`,
      milestone: "FIRST G1",
      actions: [action(`พา${name}เริ่มคนแรก`, EVENTS.START_MEMBER, { icon: "mentor" })],
    },
    [STAGES.WEEKLY_INVITE]: {
      ...base,
      scene: "weekly_ready",
      progress: 98,
      title: "เริ่ม Weekly ของทีม",
      reason: "Weekly ช่วยหลายคนฝึก ดูเคส และรู้ว่าควรทำอะไรต่อพร้อมกัน",
      speaker: "วันนี้มีเรื่องช่วยทีม 3 อย่าง",
      dialogue: "เคสลูกค้าที่เริ่มหลุด · วิธีชวนคนมาวัด · ใครควร follow-up ก่อน",
      actions: [action("เริ่ม Weekly", EVENTS.START_WEEKLY, { icon: "meeting", cost: 2 })],
    },
    [STAGES.WEEKLY_RUNNING]: {
      ...base,
      scene: "weekly",
      progress: 99,
      title: "ช่วยทีมคิดจากเคสจริง",
      reason: "คุณกำลังช่วยให้ทีมมั่นใจและทำงานได้ด้วยตัวเองมากขึ้น",
      speaker: "Weekly Meeting",
      dialogue: "กำลังแชร์เคสและตั้ง Next Action…",
      status: "meeting",
    },
    [STAGES.WEEKLY_RESULT]: {
      ...base,
      scene: "weekly_done",
      progress: 100,
      title: "ดูภาพรวมของเดือนแรก",
      reason: "คุณเริ่มจากลูกค้า 0 คน และตอนนี้มีทั้ง Success Case กับ X-VISOR คนแรกในทีม",
      speaker: "Weekly จบแล้ว",
      dialogue: `${name}รู้แล้วว่าจะเริ่มหาคนแรกและชวนวัด Xircle อย่างไร`,
      meetingResults: [
        "มิ้นท์รู้ว่าจะเริ่มคุยกับใครก่อน",
        "ทีมเห็นว่า Xircle ใช้ตอนไหน",
        "ทุกคนมี Next Action ของตัวเอง",
      ],
      actions: [
        action("ดูสรุปเส้นทาง", EVENTS.FINISH_SLICE, { icon: "summary" }),
        { label: "ดูรายได้เดือนนี้", ui: "income", icon: "coin", kind: "secondary" },
      ],
    },
    [STAGES.COMPLETE]: {
      ...base,
      scene: "complete",
      progress: 100,
      title: "จากทำเอง สู่การพัฒนาคน",
      reason: "ก้าวถัดไปคือช่วยมิ้นท์ดูแลลูกค้าคนแรก จนเขาเริ่มทำได้ด้วยตัวเอง",
      speaker: "เดือน 1 เริ่มมีแรงส่งแล้ว",
      dialogue: "คุณใช้ Xircle เพื่อเข้าใจคน ขายจากข้อมูล ดูแลจนเห็นผล และสร้าง X-VISOR คนแรกจากความเชื่อใจ",
      future: "เมื่อทีมเริ่มดูแลลูกค้าได้จริง รายได้ช่อง Direct Mentoring จึงค่อยเปิดหลังคุณเป็น XLEAD",
      actions: [
        { label: "ดูรายได้เดือนนี้", ui: "income", icon: "coin" },
        { label: "เริ่มเส้นทางใหม่", ui: "reset", icon: "reset", kind: "secondary" },
      ],
    },
  };

  return copy[state.stage] || copy[STAGES.OPENING];
}

export const TERM_HELP = Object.freeze({
  XV: "คะแนนยอดที่ใช้คำนวณขั้นรายได้และยอดทีม",
  XOS: "เครื่องมือที่ช่วยให้เห็นว่าใครทำต่อ ใครเริ่มหลุด และใครควรได้รับการติดต่อ",
  XLEAD: "X-VISOR ที่เริ่มพัฒนา X-VISOR คนอื่นให้ทำงานได้จริง",
});
