import {randomUUID,randomBytes,createHash} from 'node:crypto';
import {neon} from '@neondatabase/serverless';
import {stories} from '../short/library.js';
import {packs,methods,validateFile,validateSubmission} from '../short/platform/rules.js';
import {gatewayReady,createCharge,settleCharge} from './_lib/torntor-payment.js';
import {signedObject,verifyObject} from './_lib/torntor-storage.js';
const known=new Map(stories.map(s=>[s.id,s]));
const mode=()=>process.env.TORNTOR_MODE||'demo';
function publicConfig(){return {mode:mode(),ready:!!process.env.TORNTOR_DATABASE_URL,payments:gatewayReady(),publicKey:gatewayReady()?process.env.TORNTOR_OMISE_PUBLIC_KEY:null,auth:process.env.TORNTOR_AUTH_URL&&process.env.TORNTOR_AUTH_PUBLIC_KEY?{url:process.env.TORNTOR_AUTH_URL,key:process.env.TORNTOR_AUTH_PUBLIC_KEY}:null,daily:20,timezone:'Asia/Bangkok',storage:!!process.env.TORNTOR_S3_BUCKET};}
async function user(sql,req){const token=String(req.headers.authorization||'').match(/^Bearer ([\w.\-]+)$/)?.[1];if(!token||!process.env.TORNTOR_AUTH_URL)throw Object.assign(Error('SIGN_IN_REQUIRED'),{status:401});const r=await fetch(process.env.TORNTOR_AUTH_URL+'/auth/v1/user',{headers:{Authorization:'Bearer '+token,apikey:process.env.TORNTOR_AUTH_PUBLIC_KEY},signal:AbortSignal.timeout(10000)});if(!r.ok)throw Object.assign(Error('SIGN_IN_REQUIRED'),{status:401});const auth=await r.json();if(!auth.id)throw Error('INVALID_ACCOUNT');await sql.query('INSERT INTO tt_users(id) VALUES($1) ON CONFLICT DO NOTHING',[auth.id]);return (await sql.query('SELECT * FROM tt_users WHERE id=$1',[auth.id]))[0];}
async function visitor(sql,req,res){
 if(req.headers.authorization)return user(sql,req);
 const incoming=String(req.headers.cookie||'').match(/(?:^|;\s*)tt_visitor=([a-zA-Z0-9_-]{43})(?:;|$)/)?.[1];
 const digest=v=>createHash('sha256').update(v).digest('hex');
 if(incoming){const row=(await sql.query('SELECT user_id FROM tt_visitors WHERE token_hash=$1 AND expires>now()',[digest(incoming)]))[0];if(row)return {id:row.user_id,role:'viewer'};}
 const ip=digest(String(req.headers['x-forwarded-for']||req.socket?.remoteAddress||'unknown').split(',')[0]);const quota=(await sql.query("SELECT tt_limit($1,'visitor',30) AS allowed",['ip:'+ip]))[0];if(!quota.allowed)throw Object.assign(Error('RATE_LIMITED'),{status:429});
 const id='guest:'+randomUUID(),secret=randomBytes(32).toString('base64url');await sql.transaction([sql.query('INSERT INTO tt_users(id) VALUES($1)',[id]),sql.query("INSERT INTO tt_visitors(token_hash,user_id,expires) VALUES($1,$2,now()+interval '30 days')",[digest(secret),id])]);res.setHeader('Set-Cookie',`tt_visitor=${secret}; Path=/api/torntor; HttpOnly; Secure; SameSite=Strict; Max-Age=2592000`);return {id,role:'viewer'};
}
function role(u,required){if(u.role!=='admin'&&u.role!==required)throw Object.assign(Error('ACCESS_DENIED'),{status:403});}
async function wallet(sql,u){const profile=(await sql.query('SELECT free,paid FROM tt_users WHERE id=$1',[u.id]))[0];const unlocked=await sql.query('SELECT story,episode FROM tt_unlocks WHERE user_id=$1',[u.id]);const daily=await sql.query("SELECT 1 FROM tt_daily WHERE user_id=$1 AND day=(now() AT TIME ZONE 'Asia/Bangkok')::date",[u.id]);return {...profile,balance:Number(profile.free)+Number(profile.paid),free:Number(profile.free),paid:Number(profile.paid),unlocked:unlocked.map(x=>`${x.story}:${x.episode}`),claimed:daily.length>0,mode:mode()};}
async function episode(sql,id,ep){if(known.has(id)){const story=known.get(id);if(!Number.isInteger(ep)||ep<1||ep>story.episodes)throw Error('INVALID_EPISODE');return {price:ep<=3?0:10,format:story.format};}const w=(await sql.query("SELECT * FROM tt_works WHERE id=$1 AND episode=$2 AND status='published'",[id,ep]))[0];if(!w)throw Error('NOT_PUBLISHED');return w;}
async function listWorks(sql,u,published=false){const rows=await sql.query(published?"SELECT * FROM tt_works WHERE status='published' ORDER BY created DESC LIMIT 100":u.role==='admin'?'SELECT * FROM tt_works ORDER BY created DESC LIMIT 100':'SELECT * FROM tt_works WHERE owner=$1 ORDER BY created DESC LIMIT 100',published||u.role==='admin'?[]:[u.id]);for(const row of rows){const assets=await sql.query('SELECT id,type,size,role FROM tt_assets WHERE work=$1 ORDER BY created,id',[row.id]);row.cover=assets.find(a=>a.role==='cover');row.files=assets.filter(a=>a.role==='page');}return {works:rows};}
async function handle(sql,req,res,action,b){
 if(action==='published')return listWorks(sql,null,true);
 if(action==='asset'){const publicCover=(await sql.query("SELECT a.key FROM tt_assets a JOIN tt_works w ON w.id=a.work WHERE a.id=$1 AND a.role='cover' AND w.status='published'",[b.id]))[0];if(publicCover)return {url:signedObject(publicCover.key)};}
 if(action==='asset'){const freePage=(await sql.query("SELECT a.key FROM tt_assets a JOIN tt_works w ON w.id=a.work WHERE a.id=$1 AND w.price=0 AND w.status='published'",[b.id]))[0];if(freePage)return {url:signedObject(freePage.key)};}
 if(action==='webhook'){if(!gatewayReady())throw Error('PAYMENT_NOT_CONFIGURED');const id=b.data?.id;if(!/^chrg_(test|live)_[a-zA-Z0-9]+$/.test(id||''))throw Error('INVALID_CHARGE');return settleCharge(sql,id);}
 const u=action==='view'?await visitor(sql,req,res):await user(sql,req);
 if(req.method==='POST'){const quota=(await sql.query('SELECT tt_limit($1,$2,$3) AS allowed',[u.id,action,action==='view'||action==='upload'?120:20]))[0];if(!quota.allowed)throw Object.assign(Error('RATE_LIMITED'),{status:429});}
 if(action==='me')return {id:u.id,role:u.role};
 if(action==='join'){await sql.query("UPDATE tt_users SET role='creator' WHERE id=$1 AND role='viewer'",[u.id]);return {joined:true};}
 if(action==='wallet')return wallet(sql,u);
 if(action==='daily'){await sql.query('SELECT tt_claim($1)',[u.id]);return wallet(sql,u);}
 if(action==='unlock'){const ep=await episode(sql,b.story,Number(b.episode));await sql.query('SELECT tt_unlock($1,$2,$3,$4)',[u.id,b.story,Number(b.episode),ep.price]);return wallet(sql,u);}
 if(action==='order'){
  if(u.blocked)throw Error('ACCOUNT_REVIEW_REQUIRED');if(!gatewayReady())throw Error('PAYMENT_NOT_CONFIGURED');const pack=packs.find(p=>p.id===b.pack);if(!pack||!methods.includes(b.method))throw Error('INVALID_PACK');
  // One pending checkout per account prevents accidental retries creating duplicate charges.
  const pending=await sql.query("SELECT id FROM tt_orders WHERE user_id=$1 AND status='pending'",[u.id]);if(pending.length)throw Error('CHECK_EXISTING_ORDER');
  const order={id:randomUUID(),user_id:u.id,pack:pack.id,coins:pack.coins,amount:pack.amount,method:b.method,mode:mode()};
  await sql.query('INSERT INTO tt_orders(id,user_id,pack,coins,amount,method,mode) VALUES($1,$2,$3,$4,$5,$6,$7)',[order.id,u.id,order.pack,order.coins,order.amount,order.method,order.mode]);
  let charge;try{charge=await createCharge(order,b.token);}catch(e){if(['INVALID_PAYMENT_TOKEN','INVALID_PACK','PAYMENT_PROVIDER_ERROR'].includes(e.message))await sql.query("UPDATE tt_orders SET status='failed' WHERE id=$1",[order.id]);throw e;}await sql.query('UPDATE tt_orders SET charge_id=$2 WHERE id=$1',[order.id,charge.id]);await settleCharge(sql,charge.id);
  return {id:order.id,status:charge.status,qr:charge.source?.scannable_code?.image?.download_uri,redirect:charge.authorize_uri,wallet:await wallet(sql,u)};
 }
 if(action==='order-status'){const o=(await sql.query('SELECT * FROM tt_orders WHERE id=$1 AND user_id=$2',[b.id,u.id]))[0];if(!o)throw Error('ORDER_NOT_FOUND');if(o.charge_id)await settleCharge(sql,o.charge_id);return {order:(await sql.query('SELECT id,status,coins,amount,method,mode FROM tt_orders WHERE id=$1',[o.id]))[0],wallet:await wallet(sql,u)};}
 if(action==='view'){const ep=await episode(sql,b.story,Number(b.episode));if(ep.price&&!(await sql.query('SELECT 1 FROM tt_unlocks WHERE user_id=$1 AND story=$2 AND episode=$3',[u.id,b.story,Number(b.episode)])).length)throw Error('LOCKED_EPISODE');if(!/^[a-zA-Z0-9-]{8,80}$/.test(b.session||''))throw Error('INVALID_SESSION');await sql.query('INSERT INTO tt_views(user_id,story,episode,session,format,seconds,complete) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(user_id,story,episode,session) DO UPDATE SET seconds=greatest(tt_views.seconds,EXCLUDED.seconds),complete=tt_views.complete OR EXCLUDED.complete',[u.id,b.story,Number(b.episode),b.session,ep.format,Math.max(0,Math.min(86400,Math.round(Number(b.seconds)||0))),b.complete===true]);return {recorded:true};}
 if(action==='works'){role(u,'creator');return listWorks(sql,u);}
 if(action==='upload'){role(u,'creator');validateFile({type:b.type,size:Number(b.size)},b.format,b.role);if(!['cover','page'].includes(b.role))throw Error('INVALID_ASSET');const id=randomUUID(),key=`quarantine/${u.id}/${id}`;const url=signedObject(key,'PUT',b.type);await sql.query('INSERT INTO tt_assets(id,owner,key,type,size,role) VALUES($1,$2,$3,$4,$5,$6)',[id,u.id,key,b.type,Number(b.size),b.role]);return {id,url};}
 if(action==='submit'){
  role(u,'creator');const data=validateSubmission(b);if(!Array.isArray(b.assets)||b.assets.length<2||b.assets.length>101||new Set(b.assets).size!==b.assets.length)throw Error('INVALID_ASSETS');
  const assets=await sql.query('SELECT * FROM tt_assets WHERE id=ANY($1::text[]) AND owner=$2 AND work IS NULL',[b.assets,u.id]);if(assets.length!==b.assets.length||assets.filter(a=>a.role==='cover').length!==1||assets.find(a=>a.role==='cover').id!==b.assets[0])throw Error('INVALID_ASSETS');if(data.format!=='comic'&&assets.length!==2)throw Error('INVALID_ASSETS');for(const asset of assets){validateFile(asset,data.format,asset.role);await verifyObject(asset);}const id=randomUUID();
  await sql.query('SELECT tt_submit($1,$2,$3::jsonb,$4::text[])',[id,u.id,JSON.stringify(data),b.assets]);return {id,status:'pending'};
 }
 if(action==='moderate'){role(u,'admin');if(!['published','rejected'].includes(b.decision)||b.decision==='rejected'&&!b.note?.trim())throw Error('INVALID_REVIEW');const w=(await sql.query("SELECT * FROM tt_works WHERE id=$1 AND status='pending'",[b.id]))[0];if(!w)throw Error('ALREADY_REVIEWED');const assets=await sql.query('SELECT * FROM tt_assets WHERE work=$1',[b.id]);if(b.decision==='published')for(const asset of assets)await verifyObject(asset);const changed=await sql.query("WITH updated AS (UPDATE tt_works SET status=$2,note=$3,reviewer=$4,reviewed=now() WHERE id=$1 AND status='pending' RETURNING *) INSERT INTO tt_audit(actor,event,work,revision,note) SELECT $4,$2,id,revision,$3 FROM updated RETURNING work",[b.id,b.decision,String(b.note||'').slice(0,1000),u.id]);if(!changed.length)throw Error('ALREADY_REVIEWED');return {reviewed:true};}
 if(action==='asset'){const a=(await sql.query('SELECT a.*,w.status,w.price,w.episode,w.owner AS creator FROM tt_assets a JOIN tt_works w ON w.id=a.work WHERE a.id=$1',[b.id]))[0];if(!a)throw Error('FILE_NOT_FOUND');const review=u.role==='admin'||u.id===a.creator;if(!review&&(a.status!=='published'||a.price&&a.role!=='cover'&&!(await sql.query('SELECT 1 FROM tt_unlocks WHERE user_id=$1 AND story=$2 AND episode=$3',[u.id,a.work,a.episode])).length))throw Object.assign(Error('ACCESS_DENIED'),{status:403});return {url:signedObject(a.key)};}
 if(action==='stats'){role(u,'creator');const owner=u.role==='admin'?null:u.id;const filter='($1::text IS NULL OR story IN (SELECT id FROM tt_works WHERE owner=$1) OR story IN (SELECT story FROM tt_catalog_owners WHERE owner=$1))';const rows=await sql.query(`SELECT story,episode,count(*) FILTER(WHERE seconds>=CASE WHEN format='drama' THEN 3 ELSE 10 END OR complete AND seconds>=3)::int AS views,count(DISTINCT user_id)::int AS viewers,COALESCE(sum(seconds),0)::int AS seconds,count(*) FILTER(WHERE complete)::int AS completes FROM tt_views WHERE ${filter} AND (seconds>=CASE WHEN format='drama' THEN 3 ELSE 10 END OR complete AND seconds>=3) GROUP BY story,episode`,[owner]);const spends=await sql.query(`SELECT story,episode,count(*)::int AS unlocks,sum(free)::int AS free,sum(paid)::int AS paid FROM tt_unlocks WHERE ${filter} GROUP BY story,episode`,[owner]);const orders=owner?[]:await sql.query('SELECT id,coins,amount,method,status,mode,fee,refunded,at FROM tt_orders WHERE mode=$1 ORDER BY at DESC LIMIT 500',[mode()]);const pricing=(await sql.query("SELECT COALESCE(sum(amount-fee-refunded)::numeric/NULLIF(sum(coins),0)/100,0)::float8 AS unit FROM tt_orders WHERE status='paid' AND mode=$1",[mode()]))[0];const receipts=owner?null:(await sql.query("SELECT COALESCE(sum(amount),0)::float8/100 AS gross,COALESCE(sum(fee),0)::float8/100 AS fees,COALESCE(sum(refunded),0)::float8/100 AS refunds FROM tt_orders WHERE status='paid' AND mode=$1",[mode()]))[0];return {rows,spends,orders,receipts,pricing:{bahtPerCoin:Math.max(0,pricing.unit)},mode:mode()};}
 throw Object.assign(Error('NOT_FOUND'),{status:404});
}
export default async function handler(req,res){res.setHeader('Cache-Control','private, no-store');res.setHeader('X-Content-Type-Options','nosniff');const action=String(req.query?.action||new URL(req.url,'https://local').searchParams.get('action')||'config');try{
 const gets=['config','published','wallet','me','works','stats'];if(req.method!==(gets.includes(action)?'GET':'POST'))return res.status(405).json({error:'METHOD_NOT_ALLOWED'});
 if(action==='config')return res.status(200).json(publicConfig());
 if(mode()==='demo'||!process.env.TORNTOR_DATABASE_URL)return res.status(503).json({error:'INTEGRATION_NOT_CONFIGURED'});
 if(req.method==='POST'&&action!=='webhook'&&req.headers.origin!==new URL(process.env.TORNTOR_ORIGIN).origin)return res.status(403).json({error:'INVALID_ORIGIN'});
 const raw=typeof req.body==='string'?req.body:JSON.stringify(req.body||{});if(Buffer.byteLength(raw)>65536)return res.status(413).json({error:'PAYLOAD_TOO_LARGE'});const b=JSON.parse(raw);
 const sql=neon(process.env.TORNTOR_DATABASE_URL);return res.status(200).json(await handle(sql,req,res,action,b));
 }catch(e){const allowed=['SIGN_IN_REQUIRED','ACCESS_DENIED','INTEGRATION_NOT_CONFIGURED','PAYMENT_NOT_CONFIGURED','INSUFFICIENT_COINS','ACCOUNT_REVIEW_REQUIRED','RATE_LIMITED','ALREADY_REVIEWED','CHECK_EXISTING_ORDER'];const code=allowed.find(code=>e.message?.includes(code));const message=code||'REQUEST_FAILED';return res.status(e.status||400).json({error:message});}}
